### ISSUE TITLE
Network Scan as optional parameter

### ISSUE THREAD

**Issue by nibelungen** [tzapu/WiFiManager#10]
Make the scan for AP as optional.
In my case there are up to 15 different Networks available - it takes a lot of time to scan and list
all these Networks - sometimes the page did not load at all, i commented out the setting and everything worked fine. So make this feature optional would be great.

**Comment by tzapu** [comment]
added 
https://github.com/tzapu/WiFiManager/commit/8f38a0fbaf2ff42461dde8f57399871497561e26

cheers
