### ISSUE TITLE
AP Webserver not responding after WiFiManager connected to WiFi

### ISSUE THREAD

**Issue by TMaxedCode** [tzapu/WiFiManager#1023]
#### Hardware
**WiFimanager Branch/Release:**
- [x] Master
- [ ] Development

**Esp8266/Esp32:**
- [x] ESP8266
- [ ] ESP32

**ESP Core Version:	2.4.0, staging**
- [ ] 2.3.0
- [x] 2.4.0
- [ ] staging (master/dev)

###Serial Monitor Log
```
*WM: THIS MAY CAUSE AP NOT TO START UP PROPERLY. YOU NEED TO COMMENT IT OUT AFTER ERASING THE DATA.
*WM: 
*WM: Configuring access point... 
*WM: ssid
*WM: password
*WM: Custom AP IP/GW/Subnet
*WM: AP IP address: 
*WM: 192.168.4.1
*WM: HTTP server started
*WM: WiFi save
*WM: Sent wifi save page
*WM: Connecting to new AP
*WM: Connecting as wifi client...
*WM: Status:
*WM: 0
*WM: [ERROR] WiFi.begin res:
*WM: 6
*WM: Connection result: 
*WM: 3
connected...yeey :)
192.XXX.XXX.XXX
*WM: freeing allocated params!

```

### Description
I changed  your code wherein it makes the esp8266 go STA mode after successfully connecting to a WiFi. I changed it to AP_STA mode instead of just sta mode so I can update a text in the webserver. However, this didn't go as planned because the webserver stopped responding once the esp8266 connected to the wifi. How would this be fixed?

**Comment by tablatronix** [comment]
The webserver shutsdown when cp exits use non blocking mode in development branch

**Comment by TMaxedCode** [comment]
@tablatronix Thanks, will check it out.
