### ISSUE TITLE
After void setup fail connection to wifi, it don't try to connect again on loop

### ISSUE THREAD

**Issue by AlgoON-product** [tzapu/WiFiManager#1032]
Hi,
I'm using a Wemos D1 mini Pro, the library work well the only problem is that when the esp fail the initial connection to wifi (caused by the router off), if the router return online the esp dont't try again to connect to wifi.
In setup function to connect WiFi i use the function .autoConnect().
bye

**Comment by alfo** [comment]
You should set a timeout so the D1 mini reboots if there's no signal and nobody logs into the config portal:

`const unsigned long CONNECT_TIMEOUT = 30; // How long to attempt to connect to saved WiFi before going into AP mode
const unsigned long AP_TIMEOUT = 60; // Wait 20 Seconds in the config portal before trying again the original WiFi creds


wm.setConnectTimeout(CONNECT_TIMEOUT);
wm.setTimeout(AP_TIMEOUT);`
