### ISSUE TITLE
Need help vith DEV configportal.

### ISSUE THREAD

**Issue by usane1** [tzapu/WiFiManager#1038]
Hi!
I need a little help with nonblocking configportal.
I've managed to make my project from the nonblocking example, but there is one more thing i want to achieve. I don't know if its possible. So far if i set up the wifi then it works fine. If the router failing and recovering the ESP reconnect fine and it doesnt bother the main loop.
However, can i achive somehow that if the program in the ESP  start without wifi (router shutdown) then if the wifi is up after the program started, the ESP connect to it if it was configured earlier?

**Comment by tablatronix** [comment]
ESP already does that automatically,  you can just check for connected now and then. But esp autoreconnect in the background

**Comment by tablatronix** [comment]
` if(WiFi.status() == WL_CONNECTED)`

**Comment by usane1** [comment]
Thank you.
