### ISSUE TITLE
portal does not work on port 3000

### ISSUE THREAD

**Issue by a9965** [tzapu/WiFiManager#1040]
Hi. On port 80 it works without problems, but as soon as a port change it stops working. I am doing something wrong?
Thank you

**Comment by tablatronix** [comment]
hmm, ill check

**Comment by tablatronix** [comment]
It looks like the captive portal redirect ignores the port , you will have to disable captive portal
`wm.setCaptivePortalEnable(false);` for it to work.

I will see if it can be fixed to handle that, also add a setter to set the http port without changing the source code.


- [ ] fix cp redirect with port
- [ ] add port setter

**Comment by tablatronix** [comment]
you can now set webserver port, redirects work, captive portal will not of course
