### ISSUE TITLE
Load config portal as client (not AP)

### ISSUE THREAD

**Issue by nospam2k** [tzapu/WiFiManager#1041]
I have a feeling this will have been a question already asked but I can't seem to find it, so sorry in advance. Is it possible to just load the captive portal as a client? I'm being a bit lazy but I want to be able to update settings using the custom parameters option so I don't have to write my own portal. I know I can just reset the configuration and load as an AP but I mainly want to be able to change other parameters without dumping the config remotely so I will need the client to remain connected.

**Comment by tablatronix** [comment]
startconfigportal()

**Comment by tablatronix** [comment]
* OnDemandWebPortal.ino

**Comment by nospam2k** [comment]
Great! Thanks!
