### ISSUE TITLE
ESP8266 new version error 2.7.1

### ISSUE THREAD

**Issue by brnyza** [tzapu/WiFiManager#1049]
I'm trying to use AutoConnect exemple, and is not working.

AutoConnect.ino.cpp:1:

C:\Users\b.yuzo\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.1/tools/sdk/libc/xtensa-lx106-elf/include/sys/pgmspace.h:25:130: error: 'const char HTTP_HEAD []' redeclared as different kind of symbol

   #define PROGMEM __attribute__((section( "\".irom.text." __FILE__ "." __STRINGIZE(__LINE__) "."  __STRINGIZE(__COUNTER__) "\"")))

**Comment by tablatronix** [comment]
Fixed in 0.15
https://github.com/tzapu/WiFiManager/releases
