### ISSUE TITLE
WifiManager with LittleFS

### ISSUE THREAD

**Issue by apateluk** [tzapu/WiFiManager#1055]
It's looking like SPIFFS is being deprecated and replaced with littleFS. Are there any issues with switching my code (based on the examples) to use littleFS ? Im not sure if WiFiManager stores wifi credentials in the same filesystem.

Thanks

**Comment by tablatronix** [comment]
The examples only need to be updated

**Comment by rvt** [comment]
Note: I have been using LittleFS with the development version just fine.

**Comment by tablatronix** [comment]
#1437 
Basic example, no json or params
