### ISSUE TITLE
Add back button

### ISSUE THREAD

**Issue by tablatronix** [tzapu/WiFiManager#1058]
Sometimes it is hard to find the back button in captive portals, add a back/home button

**Comment by tablatronix** [comment]
3c0c3ff93e819f05298df40b06a48147864dcf13

`_showBack` to enable, no setter yet still testing how this should work best, might be better as part of the header

**Comment by dontsovcmc** [comment]
f**king flags... design should be more flexible. In this case everybody can easily add any buttons, styles...  WifiManager has terrible class interface, so there are a lot of request about feature, that will be used in 0.1% cases.

First of all, it's needed to separate work with network, webserver, templates.

**Comment by tablatronix** [comment]
wm was never designed to be a web interface for personal projects with templating etc

**Comment by tablatronix** [comment]
#158 

async server supports some basic templating built in

**Comment by dontsovcmc** [comment]
I know, but you increase complexity without good code and autotests, so you have a lot of bugs inside wm, inside framework and etc..
I want to help refactor wm to be flexible and simple.

**Comment by tablatronix** [comment]
I have said it before, make an issue and write a roadmap for refactoring, all I have been doing is abstracting stuff out and cleaning it up, so it can be structured and maintained.

I also disagree with it being any more complex or buggy then when I started...

**Comment by dontsovcmc** [comment]
I will write some great ideas ;)

**Comment by tablatronix** [comment]
Just be aware that the majority of users just install a library, open an example and copy paste code, they are not going to be building assets externally, or frameworks, or even uploading files..

If there is a arduino webserver capable library solution for building webapp, id liek to see it.
I have been building my own vanilla js frameworks for my projects, newer micros might have room for jquery and bootstrap but just because you can doesn't mean you should

**Comment by dontsovcmc** [comment]
Of course. It should be simple for beginners and flex for advanced.
