### ISSUE TITLE
2.0.2-alpha does not prefill selected SSID from the list

### ISSUE THREAD

**Issue by joysfera** [tzapu/WiFiManager#1066]
I have removed the rest of entries because this is some kind of a javascript/HTML bug that is not related to my ESP32 Pico D4 hardware, or the Arduino-ESP32 1.0.4 core, or the Arduino 1.8.12 IDE.

### Description

In the HTML dialog with the list of available WiFi networks if you pick an AP by "clicking" on it the AP/SSID name is not copied over to the SSID input field.

Thus no matter what Password you then enter the subsequent WiFi client login check fails because the AP name is either not set at all or an incorrent (the old/previous) AP name is used.

Re-typing the SSID name into the SSID input field manually works around this issue. But I am sure "clicking" on the AP list entries used to copy the selected SSID to the SSID input list not so long ago so this is a recently introduced bug.

**Comment by tablatronix** [comment]
Is this the alpha dev version ?
What browser?

**Comment by tablatronix** [comment]
let me make sure my last commit didnt cause this, I didnt test it

**Comment by tablatronix** [comment]
I did shit, it was a one line comment, but there are no lines in the source doh

**Comment by tablatronix** [comment]
Sorry about that, pushed fix
