### ISSUE TITLE
IS there a way to disable automatic redirection to portal after AP connect?

### ISSUE THREAD

**Issue by Hoel** [tzapu/WiFiManager#1071]
#### Hardware
**WiFimanager Branch/Release:**
- [x] Master
- [ ] Development

**Esp8266/Esp32:**
- [x] ESP8266
- [ ] ESP32

**Hardware:			ESP-12e, esp01, esp25**
- [ ] ESP01
- [ ] ESP12 E/F/S (nodemcu, wemos, feather)
- [x] Other ESP8285

**ESP Core Version:	2.4.0, staging**
- [ ] 2.3.0
- [x] 2.4.0
- [ ] staging (master/dev)

### Description

Problem description

I need to pass an UUID as parameter of the portal URL, and the only way i found  is to use two QR code:
•  the first QR code sets the mobile to the correct AP
•  the second QR code loads the portal with the UUID as URL parameter.
For this to work i need to prevent the mobile from loading automatically the portal after AP conncetion (192.168.4.1 in this case), is there a way to do this in wifimanager?

**Comment by tablatronix** [comment]
In the alpha/dev version you can disable the captive portal

**Comment by Hoel** [comment]
ok nice, i will give a try. Just to clarify : i dont want to totally disable the captive portal, i want to disable the fact that it is called automatically after the AP is connected, so i can call it manually in a second time (via QR code)

**Comment by tablatronix** [comment]
ConfigPortal is what runs.

CaptivePortal is what auto redirects on wifi connection

**Comment by Hoel** [comment]
ahh it makes sense, thank you for the insights.
