### ISSUE TITLE
error when compiling with NodeMCU v1.0

### ISSUE THREAD

**Issue by Biroooo** [tzapu/WiFiManager#1079]
# Basic Infos

trying to compile with different pc (all windows 10), with different ide (all updated to the latest version), and different NodeMCU v1.0 (all of the same model) I get the same error:

exit status 1
Error during compilation for the NodeMCU 1.0 board (ESP-12E Module).

### Debug Messages

Arduino:1.8.12 (Windows 10), Scheda:"NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, All Flash Contents, 115200"

In file included from C:\Users\leona\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.1/tools/sdk/libc/xtensa-lx106-elf/include/sys/stdio.h:6:0,

                 from C:\Users\leona\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.1/tools/sdk/libc/xtensa-lx106-elf/include/stdio.h:63,

                 from C:\Users\leona\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.1\cores\esp8266/Arduino.h:32,

                 from sketch\wifimanager.ino.cpp:1:

C:\Users\leona\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.1/tools/sdk/libc/xtensa-lx106-elf/include/sys/pgmspace.h:25:130: error: 'const char HTTP_HEAD []' redeclared as different kind of symbol

   #define PROGMEM __attribute__((section( "\".irom.text." __FILE__ "." __STRINGIZE(__LINE__) "."  __STRINGIZE(__COUNTER__) "\"")))

                                                                                                                                  ^

C:\Users\leona\OneDrive\Documenti\Arduino\libraries\WhareHauoraWiFiManager/WiFiManager.h:25:24: note: in expansion of macro 'PROGMEM'

 const char HTTP_HEAD[] PROGMEM            = "<!DOCTYPE html><html lang=\"en\"><head><meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\"/><title>{v}</title>";

                        ^

In file included from C:\Users\leona\OneDrive\Desktop\wifimanager\wifimanager.ino:6:0:

C:\Users\leona\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.1\libraries\ESP8266WebServer\src/ESP8266WebServer.h:34:39: error: previous declaration of 'HTTPMethod HTTP_HEAD'

 enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_HEAD, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };

                                       ^

exit status 1
Errore durante la compilazione per la scheda NodeMCU 1.0 (ESP-12E Module).

Questo report potrebbe essere più ricco di informazioni abilitando l'opzione
"Mostra un output dettagliato durante la compilazione"
in "File -> Impostazioni"

**Comment by tablatronix** [comment]
fixed in 0.15
