### ISSUE TITLE
Respond to client save config before going to STA?

### ISSUE THREAD

**Issue by OBorce** [tzapu/WiFiManager#1086]
Is it possible for the portal to wait and get a response whether or not the configuration succeeded?

**Comment by tablatronix** [comment]
The portal actually shuts down to connect, so e have to relaunch it and have the client ajax wait and reconnect. It is possible but has not been implemented yet.

**Comment by OBorce** [comment]
Not very knowledgeable in this, just starting out, but is it possible to have it as simultaneous AP + STA
thus being able to both serve the portal and try to connect to WiFi at the same time?
so as to not lose connection?

**Comment by tablatronix** [comment]
sta is very unstable when in that mode, connections are not as reliable

**Comment by OBorce** [comment]
unstable as in it might not connect, or will connect but can disconnected?
if the second I was thinking of using it as in just to confirm that the credentials work, send response to the portal that it has been configured, and restart as STA only.

**Comment by tablatronix** [comment]
Connections fails, because you are locked on the same channel as the softap.

**Comment by OBorce** [comment]
so there is no solution to knowing that the connection failed without manually checking?

**Comment by tablatronix** [comment]
Like I said, I have not come up with a decent solution for this yet. So it has not been implemented. I mean you could always do something in your code..

**Comment by Zodiac-69** [comment]
Have you looked at how the guy's on ESPEasy - Letscontrolit do it?
They keep AP and STA mode on after connection to a you wifi network, you can then see the IP address that you are connected to on your Wifi network and still access the unit via your original access unit on 192.168.4.1

**Comment by tablatronix** [comment]
That is the solution, but it is not the best solution as I have explained below, it can cause connection failures.
