### ISSUE TITLE
Update changes in 0.10

### ISSUE THREAD

**Issue by elieyal** [tzapu/WiFiManager#109]
Hi,
@tzapu, can you please update the documentation on what is changed/fixed in 0.10?

**Comment by tzapu** [comment]
will do, until then:
- some css changes
- bug fixes and speed improvements
- added an alternative to waitForConnectResult() for debugging

**Comment by elieyal** [comment]
Very much appreciated!!
Thank you :-)

**Comment by tzapu** [comment]
added
cheers
