### ISSUE TITLE
ESP32 Compatible?

### ISSUE THREAD

**Issue by ZebNZ** [tzapu/WiFiManager#1093]
Hi all,

I see in the .cpp file it has:
#if defined(ESP8266) || defined(ESP32)
My question is can this work with an ESP32? If ti can what do I need to do?

I know I would need to use different libraries.....
#include <ESP8266WiFi.h>          
replace with:
#include <WiFi.h>          

#include <ESP8266WebServer.h>
replace with:
#include <WebServer.h>

#include <WiFiManager.h> 

Thanks,

Zeb

**Comment by ZebNZ** [comment]
It looks like in the library it decides what libraries to use based on what you define (ESP8266 or ESP32), so I would only need to change the libraries in the .ino file.

So how do you define what board you're using?

**Comment by ZebNZ** [comment]
All working :)

Just initialize your libraries like this:
#include <FS.h>
#include "SPIFFS.h"
#include <WebServer.h>
#include <DNSServer.h>
#include <WiFi.h>
#include <WiFiManager.h>
#include <ArduinoJson.h>

And you might need to add this at the top of the setup()
```
  bool begin(bool formatOnFail=true, const char * basePath="/spiffs", uint8_t maxOpenFiles=10);
  SPIFFS.begin(true); //if it has started
```

Thanks,

Zeb

**Comment by tablatronix** [comment]
The development branch fully supports both esp8266 and esp32, there is nothing you should need to do special

**Comment by ZebNZ** [comment]
@tablatronix that's awesome! Thanks for your help!
