### ISSUE TITLE
Updating code to JSON 6

### ISSUE THREAD

**Issue by ZebNZ** [tzapu/WiFiManager#1095]
Hi all,

I am using JSON 6 but this code is using JSON 5 commands. How easily can I convert it to JSON 6? is there anything that needs to be changed in the libraries?

Thanks,

Zeb

**Comment by tablatronix** [comment]
which code?

**Comment by ZebNZ** [comment]
AutoConnect with Parameters

**Comment by ZebNZ** [comment]
@tablatronix here's the link
[https://github.com/tzapu/WiFiManager/blob/master/examples/AutoConnectWithFSParameters/AutoConnectWithFSParameters.ino](https://github.com/tzapu/WiFiManager/blob/master/examples/AutoConnectWithFSParameters/AutoConnectWithFSParameters.ino)

**Comment by tablatronix** [comment]
Sorry, I forgot this is in hotfixes and has not been released.

check the hotfixes branch there should fixed versions.

**Comment by tablatronix** [comment]
- [ ] release .16 with json fixes

**Comment by ZebNZ** [comment]
@tablatronix fixed, thank you!

**Comment by sergionaf** [comment]
Where can I find the release .16 wiht json fixes ?

**Comment by abdoshamma** [comment]
Did you find it anywhere?
