### ISSUE TITLE
Additional settings in WiFiManager.cpp

### ISSUE THREAD

**Issue by nibelungen** [tzapu/WiFiManager#11]
Adding some values to set the ip address in AP Mode.

Add these lines:

  IPAddress local_ip = IPAddress(10, 0, 0, 1);
  IPAddress gateway_ip = IPAddress(10, 0, 0, 1);
  IPAddress subnet_ip = IPAddress(255, 255, 255, 0);
  WiFi.softAPConfig(local_ip, gateway_ip, subnet_ip);

to void WiFiManger::begin(char const *apName) 

will set the IP Address - maybe needed in some case.

Would be great to set as parameter in main code.

Best regards.

**Comment by tzapu** [comment]
added in https://github.com/tzapu/WiFiManager/commit/87911808abcf164d945a13f6e853e6e485b62ee4

cheers
