### ISSUE TITLE
setConfigPortalTimeout but autoconnect still exits back to program even though not connected to any wifi 

### ISSUE THREAD

**Issue by davidkjackson54** [tzapu/WiFiManager#1101]
I have setConfigPortalTimeout(180) set as follows:

wifiManager.setAPStaticIPConfig(IPAddress(172, 217, 28, 1), IPAddress(172, 217, 28, 1), IPAddress(255,255,255,0));
wifiManager.setConfigPortalTimeout(180);            // give the configuration portal 3 minutes to complete 
wifiManager.autoConnect();
Serial.println("Connected...");

I am testing with a wifi hotspot to see what happens when wifi goes offline.
WiFiManager is correctly waiting for 180 seconds, then goes into AP mode
I see the AP SSID appear on my phone but I do not want to  reconfigure - so I leave it and wait.
Then WifiManager exits from wifiManager.autoConnect and continues - without having connected to any wifi. 

How do I fix this? I don't want it to continue if it hasn't connected to any wifi.   This scenario is just to test what happens if the wifi is unavailable for any reason. so under normal circumstances, I would not wish to configure a new SSID etc.  

*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Status:
*WM: 0
*WM: Using last saved values, should be faster
*WM: Connection result: 
*WM: 1
*WM:
*WM: Configuring access point...
*WM: ESP13649403
*WM: Custom AP IP/GW/Subnet
*WM: AP IP address: 
*WM: 172.217.28.1
*WM: HTTP server started
Connected...                                                <This Serial.print is from my progam after returning from wifiManager.autoConnect
*WM: freeing allocated params!
WiFi connected - ESP IP address: (IP unset)

 

#### Hardware
**WiFimanager Branch/Release:**
- [X] Master
- [ ] Development

**Esp8266/Esp32:**
- [X] ESP8266
- [ ] ESP32

**Hardware:			ESP-12e, esp01, esp25**
- [ ] ESP01
- [X] ESP12 E/F/S (nodemcu, wemos, feather)
- [ ] Other

**ESP Core Version:	2.4.0, staging**
- [ ] 2.3.0
- [X ] 2.4.0
- [ ] staging (master/dev)

### Description

Problem description

### Settings in IDE

Module:  			NodeMcu, Wemos D1

Additional libraries: 
mdsn

**Comment by davidkjackson54** [comment]
I have resolved this.

**Comment by tablatronix** [comment]
Thats is exactly what that setting is for
