### ISSUE TITLE
Non-essential connection

### ISSUE THREAD

**Issue by jorgele** [tzapu/WiFiManager#1105]
Hi. My project uses the Wi-Fi connection as a non-essential addition. Can it be indicated in any way that if the connection is not achieved or the configuration portal is not entered, all related functions are aborted and the program continues without an internet connection? Thank you.

**Comment by jorgele** [comment]
Sorry, I already found out how to do it. Thank you

**Comment by tablatronix** [comment]
You can use a configportal timeout , but. since esp autoconnect I would just do background connection checking And deal with it that way instead of using autoconnect
