### ISSUE TITLE
Execute an action after an AutoReconnect event

### ISSUE THREAD

**Issue by jorgele** [tzapu/WiFiManager#1110]
How can I execute an action after an AutoReconnect event? Let me explain: My project includes a connection to a firebase stream, but when the internet goes down, that connection is lost. Then, using WiFi.setAutoReconnect (true) I can recover my internet, but not the connection with firebase. Is there a callback that I can use to make a new connection with firebase or anything else? Thank you

**Comment by tablatronix** [comment]
You can use events on esp32, or use a loop and just check for

```C++

 (savedlaststatus != WiFi.status() && (WiFi.status() == WL_CONNECTED))
```

This is not WM related.
