### ISSUE TITLE
How and where is save to SSID and password?

### ISSUE THREAD

**Issue by makyazi** [tzapu/WiFiManager#1120]
İ want to reset to saved data . I didn't find to where is save to SSID . Can you show me please?

**Comment by tablatronix** [comment]
This is just esp library stuff
wm.resetSettings()

**Comment by LinhIThust** [comment]
@tablatronix i want to know exactly how to save the ssid and password. can you tell me?
Are they stored in EEPROM or somewhere else?

**Comment by tablatronix** [comment]
They are stored by the esp library not WM
