### ISSUE TITLE
Spiffs gets erased after ssid and password save

### ISSUE THREAD

**Issue by Qbunjo** [tzapu/WiFiManager#1123]
## POST SERIAL OUTPUT !

Issues without basic info will be ignored or closed!

Please fill the info fields, it helps to get you faster support ;)

if you have a stack dump decode it:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.rst

for better debug messages:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.rst

----------------------------- Remove above -----------------------------

#### Hardware
**WiFimanager Branch/Release:**
- [ x] Master
- [ ] Development

**Esp8266/Esp32:**
- [x ] ESP8266
- [ ] ESP32

**Hardware:			ESP-12e, esp01, esp25**
- [ ] ESP01
- [x ] ESP12 E/F/S (nodemcu, wemos, feather)
- [ ] Other

**ESP Core Version:	2.4.0, staging**
- [ ] 2.3.0
- [x ] 2.4.0
- [ ] staging (master/dev)

### Description

Hi there, 
I Just added your manager to my project. 
https://github.com/The-Coobaz/hunter-hack 
 I use spiffs to keep web page and css. But When I added the manager, after saving ssid and pass, The spiffs gets cleared. I don't know why id does happen, since I can't find in your library place where the credentials gets saved. 

### Settings in IDE

Module:  			NodeMcu, Wemos D1

Additional libraries: 

### Sketch

```cpp

#include <Arduino.h>

void setup() {

}

void loop() {

}
```

### Debug Messages

```
messages here
```

**Comment by tablatronix** [comment]
The esp saves the credentials on its own. So I suspect you have a esp lib issue or corrupt memory, do a full erase.

**Comment by Qbunjo** [comment]
Whoah! What a prompt answer! I will examine that.

**Comment by tablatronix** [comment]
also may sound dumb, but make sure you are not calling spiff.format.... lol

**Comment by Qbunjo** [comment]
Noo, I am not that dumb :)

**Comment by Qbunjo** [comment]
Hi. I did as you advised. Did full erase and updated library to current dev version. Everything works now. Thanks for your hint.
