### ISSUE TITLE
I need WM to connect to my network, then open up the captive portal on the device I am using to link my ESP to the network

### ISSUE THREAD

**Issue by nheyland** [tzapu/WiFiManager#1131]
#### Hardware
**WiFimanager Branch/Release:**
- [X ] Master
- [ ] Development

**Esp8266/Esp32:**
- [ X] ESP8266
- [ ] ESP32

**Hardware:			ESP-12e, esp01, esp25**
- [ ] ESP01
- [X ] ESP12 E/F/S (nodemcu, wemos, feather)
- [ ] Other

**ESP Core Version:	2.4.0, staging**
- [ X] 2.3.0
- [ ] 2.4.0
- [ ] staging (master/dev)

### Description

How can I connect the web manager to a network that has its own captive portal? For example, In college I need to log in to the wifi with my username and password, how can I use WM to do this? It only gives me the option to type in the network name and password, is there any way I can have WM open up the captive portal so I can log into my college network? 

### Settings in IDE

Module:  			NodeMcu, Wemos D1

Additional libraries: 

### Sketch

```cpp

#include <Arduino.h>

void setup() {

}

void loop() {

}
```

### Debug Messages

```
messages here
```

**Comment by tablatronix** [comment]
You cannot
