### ISSUE TITLE
question：How to send the input wifi password to ESP8266

### ISSUE THREAD

**Issue by wwdok** [tzapu/WiFiManager#1134]
Hi, freinds, I think accessing to a LAN website to configure the wifi password is an interesting thing, i am curious about how to make the input wifi password to ESP8266, where is the relavent code ? Thanks !

**Comment by tablatronix** [comment]
Esp begin() the esp does it

**Comment by wwdok** [comment]
@tablatronix Thanks for your reply, i am going to dive into it ~
