### ISSUE TITLE
Where is the Data stored ??

### ISSUE THREAD

**Issue by Animeshdhakal** [tzapu/WiFiManager#1136]
I want to know a simple question that Where are the ssid and password stored ? Is it on the EEPROM ?? Hope Anyone Knows !!

**Comment by tablatronix** [comment]
The esp library handles this

**Comment by Animeshdhakal** [comment]
I want to store relay state without the eeprom so how can I do it with esp library???

**Comment by tablatronix** [comment]
you cannot, you have to use your own code and save to flash or spiffs, or littlefs

**Comment by Animeshdhakal** [comment]
I want store only 0 and 1 4 times so is there any code I can find ?

**Comment by tablatronix** [comment]
here is some code i wrote that saves to flash, used for reset counting.

https://gist.github.com/tablatronix/efa5d525d704e4b8b9ece31af0c99fdf

Maybe it will give you a place to start
