### ISSUE TITLE
Keep portal on after connect to one network

### ISSUE THREAD

**Issue by SkyBadPT** [tzapu/WiFiManager#1138]
#### Hardware
**WiFimanager Branch/Release:**
- [ ] Master
- [x ] Development

**Esp8266/Esp32:**
- [x ] ESP8266
- [ ] ESP32

**Hardware:			ESP-12e, esp01, esp25**
- [ ] ESP01
- [x ] ESP12 E/F/S (nodemcu, wemos, feather)
- [ ] Other

**ESP Core Version:	2.4.0, staging**
- [ ] 2.3.0
- [ ] 2.4.0
- [x ] staging (master/dev)

### Description

Can't make the portal keep on after connecting to a network and I do not want to use a button to make it on, I just want it to not go off after connecting to a network

`void setup() {
    delay(1000);
    Serial.begin(115200);

    WiFiManager wifiManager;
    wifiManager.resetSettings();
    wifiManager.startConfigPortal("test123", "123456789");
    Serial.println("connected...yeey :)");`

**Comment by tablatronix** [comment]
use the non blocking examples
