### ISSUE TITLE
Can't use wifiManager.resetSettings(); inside loop

### ISSUE THREAD

**Issue by ITstreet1** [tzapu/WiFiManager#1152]
### Basic Infos
Arduino IDE 1.8.12

#### Hardware
**WiFimanager Branch/Release:**
- [ ] Master
- [ ] Development

**Esp8266/Esp32:**
- [x ] ESP8266
- [ ] ESP32

**Hardware:			ESP-12e, esp01, esp25**
- [ ] ESP01
- [x ] ESP12 E/F/S (nodemcu, wemos, feather)
- [ ] Other

**ESP Core Version:	2.4.0, staging**
- [ ] 2.3.0
- [ ] 2.4.0
- [ ] staging (master/dev)

### Description

In example sketch AutoConnectWithFSPParameters.ino, there is a wifiManager.resetSettings(); function, which can reset settings of SPIFFS data. As wifiManager is declared inside setup, I can not use this function inside a loop with a button. Or maybe there is a way, that I don't know.

### Settings in IDE

Module:  			Generic ESP8266 Module

Additional libraries: 

### Sketch

```cpp

#include <Arduino.h>

void setup() {
// didn't change a thing from an example
}

void loop() {
wifiManager.resetSettings();
}
```

### Debug Messages

```
exit status 1
'wifiManager' was not declared in this scope
```

**Comment by EgHubs** [comment]
Just redeclare it!
 ```
    if ( digitalRead(TRIGGER_PIN) == LOW) {
        WiFiManager wifiManager;
        wifiManager.resetSettings();
        delay(500);
        resetFunc();
      }
```
and resetFunc is declared before the void setup() function
`void(* resetFunc) (void) = 0; //declare reset function @ address 0
`

**Comment by tablatronix** [comment]
Yeah this is a scope issue, basic C++, not a wm issue

**Comment by ChernikovS1971** [comment]
To use wifiManager.resetSettings() see the OnDemand example. 
Well described here: https://dronebotworkshop.com/wifimanager/

**Comment by ChernikovS1971** [comment]
[EgHubs](https://github.com/EgHubs) 
thank! your code works!
