### ISSUE TITLE
[QUESTION] ControlManager Existing after connecting to network from captive portal

### ISSUE THREAD

**Issue by Karmakstylez** [tzapu/WiFiManager#1153]
Hello,

Is there a way to keep the ControlManager accessible instead of wiping the settings and start over again so you can change the WiFi or reset the info via de captive portal?

Please let me know.

~Karmakstylez

**Comment by andrezanna** [comment]
Hello, i'm interested in this too.
Thanks

**Comment by flomerz95** [comment]
Hi I think that's not possible with the current version. The problem is that the controller must change from ap mode to sta mode to check your inserted WiFi credentials. During the start of the sta mode the ap mode will be disabled which will close the config portal...

**Comment by tablatronix** [comment]
Yes in the dev and alpha version, you can ondemand and non blocking start the webserver on sta mode also

**Comment by tablatronix** [comment]
#500
