### ISSUE TITLE
is there a forum about tzapu wifimanager

### ISSUE THREAD

**Issue by ldijkman** [tzapu/WiFiManager#1160]
sorry not an issue
is there a forum about tzapu wifimanager
i have some questions that does not fit the isseus here

for my tft touch thermostat
https://www.youtube.com/watch?v=qNYT64CaLEI
https://oshwlab.com/l.dijkman/esp32-dev-kit-38-pin-to-spi-touch-tft

**Comment by tablatronix** [comment]
I can throw a discord together or a gitter

**Comment by ramanraja** [comment]
@tablatronix: Please do. It would be greatly helpful for many of us. Thanks.

**Comment by ldijkman** [comment]
i see you can add a discussion link / tab / button to github
i think its pritty new

https://github.com/ldijkman/ART-ESP32-Touch-TFT-Thermostat/discussions

**Comment by tablatronix** [comment]
Hmm ill look into it but this is not my repo so I might not have access to manage it

**Comment by tablatronix** [comment]
I added a gitter to the readme for now
