### ISSUE TITLE
WiFiManager.cpp:15:0: error: unterminated #if

### ISSUE THREAD

**Issue by fretsbiz** [tzapu/WiFiManager#1164]
I ran into the following  issue while trying to upload the FastLED Webserver that requires WiFiManager onto a Wemos D1 Mini:

C:\Users\me\Documents\Arduino\libraries\WiFiManager-development\WiFiManager.cpp:15:0: error: unterminated #if
 #if defined(ESP8266) || defined(ESP32)

After placing a #endif after the above boolean in WiFiManager.cpp the compile/upload stopped complaining,

Additionally, I am unable to to see the AP broadcasting  and therefore can't login to it in order to select a WiFi network and set a passwd.....plus I don't know where I should be posting for further help regarding the access point.  Please advise. Thanks.

**Comment by tablatronix** [comment]
Ok let me check I just merged some stuff
