### ISSUE TITLE
HTTP_UPDATE_OK naming collision

### ISSUE THREAD

**Issue by markg85** [tzapu/WiFiManager#1169]
#### Hardware
**WiFimanager Branch/Release:**
- [ ] Master
- [x] Development

**Esp8266/Esp32:**
- [ ] ESP8266
- [x] ESP32

I'm adding update functionality to an ESP32 project. For that i'm using the `HTTPUpdate.h` file that comes with the ESP32 framework.
It, in it's header has this:
```cpp
enum HTTPUpdateResult {
    HTTP_UPDATE_FAILED,
    HTTP_UPDATE_NO_UPDATES,
    HTTP_UPDATE_OK
};

typedef HTTPUpdateResult t_httpUpdate_return; // backward compatibility
```

This collides with the `strings_en.h` file (soft reminder why: C++ enum is without the class in between is global scope):
```cpp
const char HTTP_UPDATE_OK[] PROGMEM = "<div class='msg P'><strong>Update OK!</strong> Device Rebooting now...</div>";
```

In my opinion both projects are wrong here.
WiFiManager should probably namespace these things as these names are definitely easy to use by other projects too.
And the ESP folks should have done `enum class HTTPUpdateResult`. Though adding that now adds a load more compile errors.

The "easiest" fix is to throw a namespace around those string messages. Though that does give a bit of pain in the rest of the WiFiManager source to fix the result of that namespace.

Other then that, i quite like WiFiManager now :) I had my issues with it in the beginning but ever since using the development branch it's - ironically - working super stable!

Cheers,
Mark

**Comment by tablatronix** [comment]
I thought I had an issue for namespacing, ill make one
