### ISSUE TITLE
How to connect and disconnect to wifi cyclically

### ISSUE THREAD

**Issue by jordan1982** [tzapu/WiFiManager#1191]
## PLEASE TRY DEVELOPMENT BRANCH before submitting bugs on release or master, in case they were already fixed. ##

Issues without basic info will be ignored or closed!

Please fill the info fields, it helps to get you faster support ;)

if you have a stack dump decode it:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.rst

for better debug messages:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.rst

----------------------------- Remove above -----------------------------

#### Hardware
WiFimanager Branch/Release:  Development

Esp8266/Esp32: 

Hardware:			ESP-12e, esp01, esp25

Core Version:      	2.4.0, staging

### Description

Problem description

### Settings in IDE

Module:  			NodeMcu, Wemos D1

Additional libraries: 

### Sketch

```cpp

#include <Arduino.h>

void setup() {

}

void loop() {

}
```

### Debug Messages

```
messages here
```
Hi,
I would need to connect and disconnect cyclically. I give an example:
The user enters the data via the web interface (ssid, password, mqtt server, mqtt user, mqtt password etc), the system waits 5 minutes and then connects to mqtt sends the message and then disconnects from mqtt and wifi. After another 5 minutes it reconnects to the previous wifi and repeats the loop.
How can I connect and disconnect from wifi through your library?

**Comment by svdrummer** [comment]
Google ESP.Sleep() that's how we do it.

**Comment by tablatronix** [comment]
Same way you would with any esp code.. nothing special here

**Comment by jordan1982** [comment]
With esp.sleep  the data entered in the configuration page are lost?
Thanks for the help you can give me

**Comment by tablatronix** [comment]
data such as wifi ? or custom params?

**Comment by jordan1982** [comment]
wifi and custom params

**Comment by tablatronix** [comment]
well custom params have to be saved somewhere, esp wont remember then sleep is really a reboot
