### ISSUE TITLE
setConfigPortalTimeout

### ISSUE THREAD

**Issue by pdelprat** [tzapu/WiFiManager#1193]
Hello,

Thanks for this excellent library,

It"s seems that setConfigPortalTimeout parameter is near millisecond than second,

I use version 2.0.3-alpha with ESP-12F,

Have a nice day, 
Pascal

**Comment by tablatronix** [comment]
Hmm did it change? Whats the issue?

**Comment by pdelprat** [comment]
I need to specify wm.setConfigPortalTimeout (60000) to be able to use portal since 60 seconds

**Comment by tablatronix** [comment]
That doesn't make sense what do your logs show?
It is seconds

**Comment by pdelprat** [comment]
Sorry, it was a hardware issue. I can't reproduce the problem on many other devices. Thanks
