### ISSUE TITLE
Continue if Wifi not available, do not enter AP Mode. is that possible?

### ISSUE THREAD

**Issue by Primus007** [tzapu/WiFiManager#1197]
#### Hardware
WiFimanager Branch/Release:  Development
Esp8266
Hardware:			ESP-12e
Core Version:      	2.7.1, staging
Module:  			Wemos D1

If I have already configured a wifi, but if this is not available, then the AP configuration mode is started automatically. 
can i prevent that? 
I would like my program to continue working normally, even if the WiFi is not available. The AP configuration mode should only be started when a button is pressed and in no other cases.

Is that possible? if yes, how?

**Comment by tablatronix** [comment]
yeah do not use autoconnect or set enableconfigportal false
