### ISSUE TITLE
A bit more on-demand

### ISSUE THREAD

**Issue by richardwilliamson** [tzapu/WiFiManager#120]
Hello,

Great Library!

I've put in a couple of pull requests, hope I've done it right as I haven't done a great deal with Github before. I think my use case may be a bit different to that intended so I thought I would put a couple of notes..
- I am using the library with a remote control device which has an interface (with buttons), the user can start up the web-config on demand when required
- The user should be able to decide whether to have a static or DHCP IP 
- The user may set the device up while not in range of the current network

The above I think I have made work with the pull requests I put through, there are a couple more things I still need to look at:
- The user may go into the AP for reasons other than changing the network, so I am thinking about making an option where the SSID and password can be pre-populated with the current details that are in use (even if they don't work)

Thanks!

**Comment by MiloshCZ** [comment]
Hi richardwilliamson,
I agree with everything what you said :-D

**Comment by tzapu** [comment]
hi, sorry for not getting around to this yet, it s been a hectic week.

i want to document and launch the current version, then add this. 

thank you very much for both pull requests and appreciation and feedback

**Comment by richardwilliamson** [comment]
Hello

That's great! Thanks!! I will put in another pull request soon too as I have done some other stuff which you may or may not like!

Richard

**Comment by tzapu** [comment]
bring em on :d
