### ISSUE TITLE
Show extra page after connection successful

### ISSUE THREAD

**Issue by juliovedovatto** [tzapu/WiFiManager#1207]
I'm trying to figure out if there is a way to show a extra configuration page after connection successful.

I'm developing a ESP application that user will have to provide credentials in order to use the service. So I was imagining showing an extra page after the connected credentials, without closing the configuration portal.

Is this possible or do I need to rely on custom parameters?

**Comment by tablatronix** [comment]
This has been addressed in other issues of the same request, at this time no, for more info try to find those related issues.

**Comment by juliovedovatto** [comment]
@tablatronix thanks for the quickly reply

I navigated through the opened issues and didn't find anything related to my question.

 Could you point a issue/direction/keywords so I can check?  Thanks

**Comment by tablatronix** [comment]
ill try to write it up one day, but there are a few...
ummm

#1024

**Comment by tablatronix** [comment]
This will be on the roadmap after this release

**Comment by litamin** [comment]
@tablatronix you mean there will eventually be a way to display the assigned IP (in browser) after successful connection? If so: YAAAS! ;)
