### ISSUE TITLE
issue in onDemandWebPortal.ino example

### ISSUE THREAD

**Issue by rdb1977** [tzapu/WiFiManager#1218]
https://github.com/tzapu/WiFiManager/blob/1e10ffa49a0b3009eb76fac7c49fc7fb2c67f2aa/examples/OnDemand/OnDemandWebPortal/onDemandWebPortal.ino#L41-L45
instead of line
https://github.com/tzapu/WiFiManager/blob/1e10ffa49a0b3009eb76fac7c49fc7fb2c67f2aa/examples/OnDemand/OnDemandWebPortal/onDemandWebPortal.ino#L43
should be

 wm.stopWebPortal();

**Comment by sstopkin** [comment]
It's already fixed and can be closed
https://github.com/tzapu/WiFiManager/blob/master/examples/OnDemand/OnDemandWebPortal/onDemandWebPortal.ino#L44
