### ISSUE TITLE
Console window should use html special character escaping

### ISSUE THREAD

**Issue by krahabors** [tzapu/WiFiManager#123]
Console window in web interface does not show serial output, which contains html-formatted strings, \<html\> for example. That output is present in telnet session, connected to the same device, but is completely missing in web console.

**Comment by tzapu** [comment]
hello,

i am confused, which console window in web interface?

cheers
alex

**Comment by krahabors** [comment]
Ooops, sorry, it's wrong project I commented in:)
Please delete this issue, if possible.

**Comment by tzapu** [comment]
:))), no worries, if it s another project of mine, please let me know through an issue
if there another similar project, i d also like to know :D, i like cool projects :D

**Comment by krahabors** [comment]
No, that was about jeelabs/esp-link, which I also use extensively, together with yours excellent tool.
