### ISSUE TITLE
WiFiManager.cpp:1182:35: error: 'HTTPAuthMethod' has not been declared      

### ISSUE THREAD

**Issue by fani1016** [tzapu/WiFiManager#1241]
Hello everyone,

I tried an example of WiFiManager Library on my NodeMCU, but i got following errors:

In file included from C:\USER\arduino-1.8.13\libraries\WiFiManager-master\WiFiManager.cpp:13:0:
C:\USER\arduino-1.8.13\libraries\WiFiManager-master\WiFiManager.h:34:2: warning: #warning "ARDUINO_ESP8266_RELEASE_2_3_0, some WM features disabled" [-Wcpp]
 #warning "ARDUINO_ESP8266_RELEASE_2_3_0, some WM features disabled" 
  ^
C:\USER\arduino-1.8.13\libraries\WiFiManager-master\WiFiManager.cpp: In member function 'void WiFiManager::handleRequest()':

C:\USER\arduino-1.8.13\libraries\WiFiManager-master\WiFiManager.cpp:1182:35: error: 'HTTPAuthMethod' has not been declared
     server->requestAuthentication(HTTPAuthMethod::BASIC_AUTH); // DIGEST_AUTH
                                   ^
C:\USER\arduino-1.8.13\libraries\WiFiManager-master\WiFiManager.cpp: In member function 'String WiFiManager::getInfoData(String)':

C:\USER\arduino-1.8.13\libraries\WiFiManager-master\WiFiManager.cpp:2028:44: error: 'class ESP8266WiFiClass' has no member named 'softAPSSID'
     p.replace(FPSTR(T_1),htmlEntities(WiFi.softAPSSID()));

Kindly help me solving this problem.

Thanks.

**Comment by tablatronix** [comment]
ok let me look, you are clearly using a very old version of the esp lib

**Comment by fani1016** [comment]
Yeah, i updated and everything works fine now.
Thanks for your reply.

**Comment by tablatronix** [comment]
I added a fix that might prevent this

**Comment by peeta-rudy** [comment]
Hi I use the newest version of wifimanager 2.0.5-beta and I got the same error. 
Please help me solving this problem.
Thanks

**Comment by Alives** [comment]
It looks like code was added to enable authentication then was bypassed.  What is the status with authentication?  I'd like to protect the `/params` and `/update` pages.

**Comment by tablatronix** [comment]
I think the only issue was that it doesnt work in captive portal browsers, So instead of trying to restrict this, we would benefit more from html auth
