### ISSUE TITLE
Ardunio 1.6.8 tested?

### ISSUE THREAD

**Issue by elieyal** [tzapu/WiFiManager#125]
Hi tzapu,
Was the latest release tested with Ardunio 1.6.8?
 would not want to upgrade the Ardunio to the latest just to find out that it's not working :-)I
Thanks.

**Comment by tzapu** [comment]
hi
i haven not tested it myself. it shouldn t have a problem really...

**Comment by kaeferfreund** [comment]
seems that there ist some issues with the esp8266 board "plugin" on 1.6.8 in general

**Comment by tablatronix** [comment]
I use it, no problems here.

**Comment by cfrodca** [comment]
No problem here!
