### ISSUE TITLE
Suppress Password

### ISSUE THREAD

**Issue by dbridgedale** [tzapu/WiFiManager#1256]
Just a suggestion.  autoConnect prints the SSID and Password to the serial port.  An option to suppress the password would be nice.

#### Hardware
WiFimanager Branch/Release:  Master

Esp8266/Esp32: 

Hardware:			ESP-12e, esp01, esp25

Core Version:      	2.4.0, staging

### Description

Problem description

### Settings in IDE

Module:  			NodeMcu, Wemos D1

Additional libraries: 

### Sketch

```cpp
#BEGIN
#include <Arduino.h>

void setup() {

}

void loop() {

}
#END
```

### Debug Messages

```
messages here
```

**Comment by tablatronix** [comment]
Only if you have debugging enabled
