### ISSUE TITLE
Add home Wifi network (SSID and PSK) to the sketch.

### ISSUE THREAD

**Issue by CyberLeito** [tzapu/WiFiManager#1259]
Add an existing wifi network to connect to. So we dont have to set it up using AutoConnectAP every time I upload a sketch. I want to add a wifi network programmatically to list of saved WiFi, kind of hardcoding one wifi into it.
If anyone has done this please respond.

**Comment by tablatronix** [comment]
// to preload autoconnect for test fixtures or other uses that skip esp sta config
    bool          preloadWiFi(String ssid, String pass);
