### ISSUE TITLE
The library is no longer in Arduino?

### ISSUE THREAD

**Issue by FeatureSpitter** [tzapu/WiFiManager#1278]
![imagem](https://user-images.githubusercontent.com/39516190/128376532-fbdfe948-f62d-4479-aaf9-e4039e9e5323.png)

This is the only result I get

**Comment by dronecz** [comment]
It is still in library manager 😉 

![image](https://user-images.githubusercontent.com/16454728/129422629-fdd0e697-3e97-4b36-86b5-c0e925007063.png)

**Comment by tablatronix** [comment]
I adjusted the library file to see if it helps, removed myself from authors and added tzapu to the description, for some reason the library search sucks

**Comment by tablatronix** [comment]
Ok this seems to have fixed it, definitely an arduino bug, anyone know where to report those?
