### ISSUE TITLE
Callback for OTA update

### ISSUE THREAD

**Issue by Mollayo** [tzapu/WiFiManager#1285]
It would be useful to have a callback before the OTA update. The OTA update sometimes can be corrupted because of timer interrupts. The idea would be to have a method "setPreOtaUpdateCallback()" to set a user-defined callback. This callback would be called just before uploading the new firmware so that the user can disable all the interrupts that may corrupt the OTA update.

This does not require much work of implementation. If you agree, I can implement this feature myself and make a pull request.

**Comment by tablatronix** [comment]
Hmm feel free might have to see how it could effect uploads with any delays

**Comment by Mollayo** [comment]
Voilà. Done.
