### ISSUE TITLE
Suggestion to add option to exit config portal after customer parameters have been saved

### ISSUE THREAD

**Issue by Pius171** [tzapu/WiFiManager#1289]
#### Hardware
WiFimanager Branch/Release:  Master

Esp8266/Esp32: ESP8266

Hardware:			ESP-12e

Core Version:      	3.0.2

### cant save custom parameters because until  config portal is closed

I try to save my custom parameters to LittleFS but since the config portal is blocking i can't until the portal is closed or i go back home and and exist the config portal. I think there should be the buttons after you have saved your custom parameters one to go back "home" and another to to exit the portal.

Thanks for reading.

Module:  			NodeMcu,

**Comment by tablatronix** [comment]
There is there is also a non blocking mode
