### ISSUE TITLE
Using __FlashStringHelper for customHTML

### ISSUE THREAD

**Issue by Mollayo** [tzapu/WiFiManager#1291]
__FlashStringHelper can be used for customHTML; this is useful for reducing the memory usage of WifiManager. However, this would require to make the following modifications to the WiFiManagerParameter class:

- Make the _customHTML parameter as protected instead of private.
- Make the getCustomHTML() method virtual so that this method can be overridden by the child class.

With these modifications, it would then be possible to implement a WiFiManagerParameter child class to implement a CustomHTML that uses __FlashStringHelper.  See below. 

If you agree, I can implement this feature myself and make a pull request.

```javascript
String flashStrBuffer;

class FlashCustomHTMLParameter : public WiFiManagerParameter {
public:
    FlashCustomHTMLParameter(const __FlashStringHelper *str):WiFiManagerParameter(NULL)
    {
      _customHTML=(const char*)str;
    }
    const char* getCustomHTML() const {
      // Convert __FlashStringHelper* to const char* using the String class
      flashStrBuffer=(const __FlashStringHelper*)_customHTML;
      return flashStrBuffer.c_str();
    }
};
```

**Comment by tablatronix** [comment]
hmm why did I think this was already supported?

**Comment by tablatronix** [comment]
Can you have this PR ready soon? I need to make a release should I wait ?

**Comment by Mollayo** [comment]
Ok. I will do it within today.

**Comment by Mollayo** [comment]
I just made the pull request.
