### ISSUE TITLE
Typo in OnDemandWebPortal example

### ISSUE THREAD

**Issue by sauvant** [tzapu/WiFiManager#1295]
in line 44 it should read
        wm.stopWebPortal();
instead of
        wm.startWebPortal();

**Comment by ClemensGruber** [comment]
Btw there is also a typo in the Config version: /examples/OnDemand/OnDemandConfigPortal/OnDemandConfigPortal.ino

In line 28 there is code for resetting settings: 
```
    //reset settings - for testing
    //wifiManager.resetSettings();
```
but some lines before WiFiManager was initialized by
```
    WiFiManager wm;   
```
so `wm.resetSettings();` is working.

**Comment by tablatronix** [comment]
Thanks
