### ISSUE TITLE
autoConnect() does not respect setEnableConfigPortal() when there are no WiFi credentials saved

### ISSUE THREAD

**Issue by gotlaufs** [tzapu/WiFiManager#1297]
#### Hardware
WiFimanager Branch/Release: 2.0.4-beta+sha.8984863

Esp8266/Esp32: ESP32

Hardware:			NodeMCU ESP32-S

Core Version:      	2.4.0, staging

### Description
When there are no WiFi credentials stored, if I specify `setEnableConfigPortal(false)`, `autoConnect()` still opens config portal and does not return.

### Settings in IDE

Module:  			NodeMCU ESP32-S

Additional libraries: 

### Sketch

```cpp
#include <Arduino.h>
WiFiManager wm;
void setup() {
  wm.setEnableConfigPortal(false);
  wm.autoConnect(); // <- This should return if unable to connect
}

void loop() {

}
#END
```

### Debug Messages

```
*wm:[1] AutoConnect 
*wm:[1] No Credentials are Saved, skipping connect 
*wm:[2] Starting Config Portal 
*wm:[2] Disabling STA 
*wm:[2] Enabling AP 
*wm:[1] StartAP with SSID:  ESP32_EC4F5FC
*wm:[2] AP has anonymous access! 
*wm:[1] AP IP address: 192.168.4.1
*wm:[1] Starting Web Portal 
*wm:[2] HTTP server started 
*wm:[2] Config Portal Running, blocking, waiting for clients... 
```

**Comment by tablatronix** [comment]
Thanks, good catch
