### ISSUE TITLE
Hostname does not work 

### ISSUE THREAD

**Issue by VladimirVecera** [tzapu/WiFiManager#1300]
I'm trying to set a hostname, but it doesn't work. I still have esp32-987C40 on my wifi despite CTRL + F5.
What am I doing wrong?

`wm.setHostname("WifiName");`

ESP32 core 2.0.0
Version wifimanager: 2.0.4

**Comment by tablatronix** [comment]
Which hostname are you looking at?

**Comment by VladimirVecera** [comment]
I want to have my own hostname, ie "WifiName", but the hostname cannot be set, wifimanager ignores the settings and if I look in the router, the name remains the same, ie esp32-987C40

**Comment by tablatronix** [comment]
Perhaps you are not calling autoconnect, either way mine works fine..

![Screen Shot 2021-10-05 at 7 17 52 PM](https://user-images.githubusercontent.com/807787/136121373-7e89a353-2e22-4b61-8145-93f9672fee41.png)
![Screen Shot 2021-10-05 at 7 19 29 PM](https://user-images.githubusercontent.com/807787/136121376-248f38a0-9894-4197-9fd0-4facaae2be58.png)
![Screen Shot 2021-10-05 at 7 20 08 PM](https://user-images.githubusercontent.com/807787/136121382-e8b9852e-db02-423e-bcd0-a6c413f21c2d.png)
