### ISSUE TITLE
save wifi failing on esp32 s2, stuck in wait?

### ISSUE THREAD

**Issue by tablatronix** [tzapu/WiFiManager#1310]
*wm:[1] Connecting to NEW AP: MyHotspot
*wm:[1] connectTimeout not set, ESP waitForConnectResult... 

failed and timeout

**Comment by learn05** [comment]
this also happened to some ESP32 devices, thought its a problem in device itself.

i hope if you an ansser my question regarding saving STatic IP config settings afterreset

**Comment by tablatronix** [comment]
It happened again but I didn't have debugging on, ugh. I am assuming some issue with a missing or unknown event in the esp32 event listener and the waitforloop maybe

**Comment by tablatronix** [comment]
Probably fixed in esp32, i have not expereienced this recently, anyone else?
