### ISSUE TITLE
How to use on PlatformIO and ESP32

### ISSUE THREAD

**Issue by marcolino7** [tzapu/WiFiManager#1313]
Just one quick question, to use on PlatformIO the esp32, I have to use branch esp32s2

Thanks

**Comment by tablatronix** [comment]
it should all be in master now

since pio wont pull in beta releases you will probably have to add lib from github

**Comment by Sulomus** [comment]
I am facing now the same issue with error code:
`File "ESP8266WiFi.h" can't be open . (dependency of "WiFiManager.h")`

Did you somehow resolve the issue?

**Comment by Kakomis** [comment]
I get this message .pio\libdeps\nodemcu-32s\WiFiManager\WiFiManager.h:92:20: fatal error: Update.h: No such file or directory

**Comment by tablatronix** [comment]
hmm, That file is in the esp32 framework.. not sure maybe a lib_ldf mode issue?

**Comment by Kakomis** [comment]
Yes, you're right, lib_ldf_mode = deep+ fixed it.

**Comment by tablatronix** [comment]
I have had to do that alot recently and I am not sure exactly why..
