### ISSUE TITLE
After the router failure, the wifimanager will not be accepted again 

### ISSUE THREAD

**Issue by VladimirVecera** [tzapu/WiFiManager#1316]
It so happened that the child inadvertently turned off the router from the power supply. ESP32, which was connected to this router via wifi, cannot connect now and will fall into configportal, where it will remain hanging. After about an hour, I will plug in the router, but ESP32 will no longer connect.

Is it possible to set it to wifimanager so that it can try to connect again after a certain time? 

    wm.setConnectTimeout(60);
    wm.setTimeout(120);
    wm.setConfigPortalTimeout(60);
    wm.setMenu(menu);
    wm.setClass("invert"); // dark theme
    wm.setScanDispPerc(true); // display percentages instead of graphs for RSSI
    wm.setAPCallback(configModeCallback); // callbacks
    wm.setSaveConfigCallback(saveWifiCallback); // callbacks
    wm.setSaveParamsCallback(saveParamCallback); // callbacks
    wm.setBreakAfterConfig(true); // callbacks Wifi

**Comment by tablatronix** [comment]
Do you have serial logs? It should not erase credentials and should connect on reboot, that sounds strange
