### ISSUE TITLE
NO APConnect with customised MAC address

### ISSUE THREAD

**Issue by ArcadeD3vil** [tzapu/WiFiManager#1318]
Hi there,
when using a customized mac address with an ESP32, 
i can´t reach the APConnect front page or by standard 192.168.4.1

using this setting:

uint8_t new_mac[] = {0x01, 0x02, 0x03 ,0x04, 0x05, 0x06};
esp_base_mac_addr_set(new_mac);

is it a bug or do i missing something?

Thanks for any help ;-)
Cheers !!

**Comment by tablatronix** [comment]
hmm not sure, not tested at all, is this a wm issue?

**Comment by tablatronix** [comment]
Can you reproduce without WM ?

**Comment by tablatronix** [comment]
Will reopen if you provide sample code and logs
