### ISSUE TITLE
No/Gibberish serial output on Olimex MOD-WIFI-ESP8266

### ISSUE THREAD

**Issue by codmpm** [tzapu/WiFiManager#132]
Hi tzapu,

just found WiFiManager and it is exactly what I need - great work! Sadly I ran into problems when using the [MOD-WIFI-ESP8266-DEV](https://www.olimex.com/Products/IoT/MOD-WIFI-ESP8266-DEV/open-source-hardware) from Olimex. I can't get serial output to work. All I see is something like this: "�n��������#�n��r" at 115200 Baud. When I switch to 74880 Baud I get this output: 

```
ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1264, room 16 
tail 0
chksum 0x42
csum 0x42
~ld
```

...looks like the bootloader. `rst cause:2` is correct, as I used the attached reset button. `boot mode:(3,6)` seems correct, as `3` indicates boot from flash.

I've tested my code on the [Adafruit Huuza-Board](https://www.adafruit.com/products/2471) to double check and I get serial output as expected. WiFiManager itself runs on the Olimex-board as I see the AP and get redirected to the captive portal.

The Adafruit Board is using a Level-Shifter for the serial output. It get's powered with 5V from my Foca FTDI Adapter which works fine. The Olimex-board gets powered from the same Foca FTDI Adapter with 3.3V. It has switchable voltage and if I don't use WiFiManager I can get serial output as expected from the Olimex board.

Do you have any idea what I can do to get this fixed? Should get in contact with the Olimex support?

Thank you,
Patrik

**Comment by tzapu** [comment]
hi, that looks like the boot loader support at 74880.
and then nothing from your sketch.
do you have serial begin in your sketch before wifi manager? does this happen to any example provided? how about some esp8266 examples?

**Comment by codmpm** [comment]
Hi tzapu,

thanks for your fast reply. I'm using the [AutoConnectWithFeedbackLED](https://github.com/tzapu/WiFiManager/tree/master/examples/AutoConnectWithFeedbackLED) example without any modifications. 

    void setup() {
    // put your setup code here, to run once:
    Serial.begin(115200);
    //...
    }

The exacty same code works on the Huzza-board. The only difference is the board definition: (http://arduino.esp8266.com/stable/package_esp8266com_index.json), as I use the appropriate ones for the Huzza- or the Olimex-board. 

Thnx,
Patrik

**Comment by tzapu** [comment]
hi,

i don t have an olimex board to test unfortunately, i am not sure what could be different.

if you use generic board with appropiate settings, does it still happen?
