### ISSUE TITLE
WPA3 Support

### ISSUE THREAD

**Issue by lbhm** [tzapu/WiFiManager#1324]
I am new to the Arduino community so please excuse me if this is the wrong place to ask.

I am planning a small sensor project at home and part of it is that I would like to connect a Lolin D1 Mini to my home WiFi using the WiFiManager library. The catch is that my WiFi is running WPA3 and I would not like to revert to a lower security standard (i.e., WPA2). 

Therefore, my question is: **Does WiFiManager support connecting to WPA3 networks?** 

I found some documentation on the Expressif website indicating that ESP8266/ESP32 chips are able to connect to WPA3 networks from the hardware side ([[1]](https://docs.espressif.com/projects/espressif-esp-faq/en/latest/software-framework/wifi.html?highlight=wpa3#do-espressif-s-chips-support-wpa3)) but other sources indicated that software support is not a given ([[2]](https://www.reddit.com/r/esp8266/comments/9eh363/wpa3/)).

I am glad for any help on this topic!

[1] https://docs.espressif.com/projects/espressif-esp-faq/en/latest/software-framework/wifi.html?highlight=wpa3#do-espressif-s-chips-support-wpa3
[2] https://www.reddit.com/r/esp8266/comments/9eh363/wpa3/

**Comment by richarddeweerd** [comment]
This is more a tool chain issue than an WiFiManager issue. 

The latest ESP-IDF versions 4.0 and above do support WPA3. If you use platform.io with the latest platform-espressif32 package (3.4.0) there should be no problem. That is based on ESP-IDF 4.3.1
