### ISSUE TITLE
Example for the integration of the mqtt-server

### ISSUE THREAD

**Issue by m-wulffde** [tzapu/WiFiManager#1330]
The instructions on the homepage describe how to integrate an mqtt server.
once WiFiManager returns control to your application, read and save the new values using the WiFiManagerParameter object.
Unfortunately I can't find an example for this.

WiFiManager wifiManager;
WiFiManagerParameter A_Winkel("parameterId", "Parameter Label", "Winkel 1-4", 40);
wifiManager.addParameter(&A_Winkel);
Serial.println("A_Winkel: ");
Serial.println(A_Winkel.getValue());
// winkel = (A_Winkel.getValue());

Which call should follow for permanent saving?
The issues #1280 would be ingenious.

**Comment by tablatronix** [comment]
The FS examples show how to save stuff, use littlefs or spiffs, not a wm issue
