### ISSUE TITLE
Captive Portal Not launching in Android

### ISSUE THREAD

**Issue by varunwyest** [tzapu/WiFiManager#1335]
The portal is not launching on Android, I have to click on IP address to open the portal. Is the Captive portal supposed to launch automatically.

**Comment by tablatronix** [comment]
There is much discussion on this and google dns issues, see esp issues

**Comment by bwjohns4** [comment]
@tablatronix , do you know of any links to these esp issues? I'd like to read more on this.

**Comment by tablatronix** [comment]
https://www.google.com/search?q=github+esp8266+esp32+android+captive+portal+google+dns&ei=R0_8YZS6BtunqtsP0K--0Ag&ved=0ahUKEwjU-bqFw-T1AhXbk2oFHdCXD4oQ4dUDCA4&uact=5&oq=github+esp8266+esp32+android+captive+portal+google+dns&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABKBAhGGABQsQdYqA9gqBBoAnACeACAAUiIAeYDkgEBN5gBAKABAcgBCMABAQ&sclient=gws-wiz
