### ISSUE TITLE
If it does not connect to the saved wifi, restart 

### ISSUE THREAD

**Issue by VladimirVecera** [tzapu/WiFiManager#1343]
I can't figure out exactly what the Wifimanager settings will look like in this build:

If the wifi is not saved, enter the configportal immediately using the set AP (ssid, pass) and leave it for 5-10 minutes before setting up a new wifi.
Restart after saving
Once the wifi is saved but still can't connect, reboot. Do not turn on any configportal.

Will you please advise?

**Comment by tablatronix** [comment]
these are the funcs you will need

`getWiFiIsSaved()`
`setConfigPortalTimeout()`
`setEnableConfigPortal()`
