### ISSUE TITLE
WiFiManager should make defensive copy of hostname

### ISSUE THREAD

**Issue by lptr** [tzapu/WiFiManager#1348]
#### Hardware
WiFimanager Branch/Release:  2.0.5-beta
Hardware:			ESP32

### Description

`WiFiManager::setHostname(char*)` should make a defensive copy of parameter value instead of storing the raw parameter value. Currently it is possible to e.g. pass a `hostname` value that gets freed up before `WiFi.setHostname()` etc., resulting in a corrupted hostname being set.

Note: `setCustomHeadElement(char*)` probably suffers from the same problem.

**Comment by tablatronix** [comment]
YES, I forgot all about this, but saw that a couple weeks ago

**Comment by tablatronix** [comment]
No idea what works best here, ideas? I just changed it to string , it should copy and it seems to work now
