### ISSUE TITLE
EXIT button cannot work in non-blocking mode

### ISSUE THREAD

**Issue by stacklover** [tzapu/WiFiManager#1353]
#### Hardware
WiFimanager Branch/Release:  Master

The EXIT button in the Portal does not work in non blocking mode, because:

void WiFiManager::handleExit() faithfully sets "abort = true",

but "abort" is only checked in the while(1) loop in blocking mode

if one uses non blocking mode it is not checked and there is no method to read this private variable.

I believe it should be handled in the "boolean WiFiManager::process()" function in a similar way it is handled while in blocking mode?

I will try to do that :)

**Comment by tablatronix** [comment]
I guess the question should be, should it work ? Do we want it to ?

**Comment by stacklover** [comment]
An EXIT button should work the same way in blocking and non-blocking mode, right?
If one could have a callback function to handle it, it should also work the same.
My solution right now is and works how I would expect it to (added stuff between the "++++++":

/**
 * [process description]
 * @access public
 * @return {[type]} [description]
 */
boolean WiFiManager::process(){
    // process mdns, esp32 not required
    #if defined(WM_MDNS) && defined(ESP8266)
    MDNS.update();
    #endif
//+++++++++++++++++++++++
    // check for abort set
    if(abort){
      #ifdef WM_DEBUG_LEVEL
      DEBUG_WM(DEBUG_DEV,F("configportal abort"));
      #endif
      shutdownConfigPortal();
      abort = false; // prevent repetitive calling
    }
//+++++++++++++++++++++++

    if(webPortalActive || (configPortalActive && !_configPortalIsBlocking)){
        uint8_t state = processConfigPortal();
        return state == WL_CONNECTED;
    }
    return false;
}

**Comment by tablatronix** [comment]
I mean do you always want to allow an end user to stop portal? 
I might have to add access control mechanism

**Comment by tablatronix** [comment]
#982

**Comment by stacklover** [comment]
I think, you miss the point: there is an "EXIT" button automatically presented in the portal. And therefore it should work exactly like an end user expects it to.
It is discussable, whether that button should be displayed optionally, aka "setShowExitButton(bool)", but as long as it is shown it should work.
Currently I am happy having that button and with my small patch it is working as I expect it.

Needless to say, after 2-3 days learning curve, the WiFiManager does exactly what I need for my application:
* optional(!) WiFi setup (because WiFi connection is optional)
* optional parameter changing (from factory defaults) in own submenu (setParamsPage(true))
* the portal is only started when a button is pressed (need physical access to start the portal, it never starts on its own)
* WiFi stays off unless its configured
* the application itself continues to run while the portal is open (quite important)

Thanks for this very good project!

**Comment by tablatronix** [comment]
The menu is customizable

**Comment by stacklover** [comment]
![IMG_1370](https://user-images.githubusercontent.com/16916615/152371168-c5c127ae-47aa-4732-8d22-cf848c44b475.PNG)
This is what I get without doing anything special to have that EXIT button!
If you think, that should not be this way, we have to figure out why it is that way ;)

**Comment by stacklover** [comment]
ALL I do configure is this:

void wifiman_setup() {
  wifiManager.setDebugOutput(true);
  wifiManager.setSaveParamsCallback(SaveParamsCallback);
  wifiManager.setBreakAfterConfig(true);
  wifiManager.setConfigPortalBlocking(false);
  wifiManager.setShowPassword(true);
  wifiManager.setParamsPage(true);
  wifiManager.setDarkMode(true);
  // Enter all Custom Parameters
  for (PARAMETER *p = parameters; p->name != NULL; p++) {
    p->wpar = new WiFiManagerParameter(p->name, p->name);
    wifiManager.addParameter(p->wpar);
  }

**Comment by tablatronix** [comment]
#1354

**Comment by tablatronix** [comment]
lol in the code

` * HTTPD CALLBACK exit, closes configportal if blocking, if non blocking undefined`

**Comment by stacklover** [comment]
didn't see that, though I had added a printf there to see whether its called at all ;)
