### ISSUE TITLE
Version 2.0.7-alpha breaks arduino build

### ISSUE THREAD

**Issue by Jueff** [tzapu/WiFiManager#1359]
### Basic Infos
WiFimanager 2.0.7-alpha
compiledwith Arduino IDE for Esp32, core Version 1.0.4

### Description
ESP core 1.0.4 doesn't implement the member function WiFiClass::softAPSSID.
as 2.0.7-alpha uses this method the build fails.

```
C:\Users\USER\DOCUME~1\Arduino\LIBRAR~1\WiFiManager\WiFiManager.cpp: In member function 'String WiFiManager::getInfoData(String)':
C:\Users\USER\DOCUME~1\Arduino\LIBRAR~1\WiFiManager\WiFiManager.cpp:2097:44: error: 'class WiFiClass' has no member named 'softAPSSID'
     p.replace(FPSTR(T_1),htmlEntities(WiFi.softAPSSID()));
                                            ^
C:\Users\USER\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi
```
Caused by other issues I currently can't update to a newer core version.

**Comment by tablatronix** [comment]
oops I fixed this in the wrong branch
