### ISSUE TITLE
generate code from hmtl template

### ISSUE THREAD

**Issue by javl** [tzapu/WiFiManager#136]
I think it would be useful to have a way to convert the html template to the needed variables (`const char HTTP_STYLE[] PROGMEM`, etc.). 
That would allow for an easier way to update the portal page (and maybe other pages in the future, like with project specific settings).

Before I start writing a (python) script to do this: is there indeed no way at the moment to convert your `extra/WifiManager.template.html` file? Or am I missing something?

**Comment by tzapu** [comment]
hi, that would be quite nice, it would be so much easier to keep everything in sync 
i have always done it manually, the changes have been in batches and not that big, but you never know when some unwanted snippet ges missed ...
for simplicity, those defines could be in a separate .h file as well

what a great idea, thank you very much
