### ISSUE TITLE
Troubles if SSID includes "-"

### ISSUE THREAD

**Issue by LennartVin** [tzapu/WiFiManager#1360]
I have set up the simple example. However, when I click on a network where the SSID includes a "-" and try to connect to it, I receive the error stating "AP not found".
I can connect to the SSID when I enter the SSID manually. This means that by clicking on the SSID on the Connection site the SSID is not correctly transferred to the textbox

**Comment by tablatronix** [comment]
What version ?
Did you try the newest beta?

**Comment by tablatronix** [comment]
ok maybe I broke this
#1361

**Comment by tablatronix** [comment]
nah works for me just fine

**Comment by tablatronix** [comment]
this makes no sense!

Upload

```
*wm:[3] Method: POST
*wm:[3] [ARG] param s test–dashes
*wm:[3] [ARG] param p 12345678
*wm:[3] Sent wifi save page 
*wm:[2] processing save 
```

**Comment by tablatronix** [comment]
I reverted that, I added it because IDF was having issues, and now this is.. string looks clean, Ill need to check the length of the c_str and termination maybe.. and make sure there is refs here

**Comment by tablatronix** [comment]
yup there is 2 extra characters in there.. hmm

**Comment by tablatronix** [comment]
I reverted and pushed another beta, ugh sorry about that, ill test elsewhere

**Comment by tablatronix** [comment]
Strangely it doesn't seem to be the other entities, & works fine

**Comment by JonathanCaes** [comment]
Just reading on this. The issue I had with not connecting to WiFi using PlatformIO (https://github.com/tzapu/WiFiManager/issues/1358) is probably the same issue. 
Since reading this I have pulled the new beta into PlatformIO and everything works again.

**Comment by JohnvanderPol2** [comment]
Same issue Dash in SSID is converted to e28093 #1372
there is something that converts the - into a multi byte character, this prevents the SSID to be found
#1372 contains some more analysis
I will try the current beta if it fixes it.

**Comment by tablatronix** [comment]
hmm #1361

**Comment by JohnvanderPol2** [comment]
It still worked in 2.0.5-Beta  
In 2.0.8 and 2.0.9 it failed.

I did not check yet with 2.0.6 and 2.0.7.
If I do, I will try to update the info.
For now I have at least a workaround.

**Comment by tablatronix** [comment]
This was just fixed in git, or it was just broken, I will test it again

**Comment by tablatronix** [comment]
This should be fixed
