### ISSUE TITLE
ESPAlexa - WiFiManager incompatibility

### ISSUE THREAD

**Issue by GoTVm** [tzapu/WiFiManager#1387]
#### Hardware
WiFimanager Branch/Release:  Master

Esp8266/Esp32: ESP8266

Hardware:			ESP-12e

Core Version:      	2.4.0

### Description

WiFiManager interferes with ESPAlexa because they both use a WebServer. This could be fixed by passing the webserver WiFiManager is using to ESPAlexa, but I can't seem to find where it creates it so as to pass it as a parameter. Therefore I'm wondering if there is any workaround so I can implement this into my ESPAlexa sketch.

### Settings in IDE

Module:  			NodeMcu

Additional libraries: 
ESPAlexa.h

### Sketch

```cpp
#BEGIN
#include <ESP8266WebServer.h>
#include <DNSServer.h>
#include <WiFiManager.h>
#include <ESP8266WiFi.h>
#include <BfButton.h>
#include <Espalexa.h>

#define LED 3
#define WIFI_RST 2

#define DEV_NAME ...

WiFiManager wm;
BfButton btn(BfButton::STANDALONE_DIGITAL, WIFI_RST, true, LOW);
Espalexa espalexa;
EspalexaDevice* led;


void stripToggle(uint8_t br, uint32_t rgb) {
  analogWrite(LED, br);
}

void pressCB(BfButton *btn, BfButton::press_pattern_t pattern) {
  if (pattern == BfButton::LONG_PRESS) {
    if (!wm.startConfigPortal(DEV_NAME)) {
      Serial.println("failed to connect and hit timeout");
      delay(2000);
      ESP.reset();
    }
  }
}


void setup() {
  WiFi.mode(WIFI_STA);
  WiFi.hostname(DEV_NAME);
  WiFi.persistent(true);
  WiFi.setAutoConnect(true);
  WiFi.setAutoReconnect(true);
  

  wm.setConfigPortalTimeout(120);
  wm.setConnectTimeout(30);
  wm.setTimeout(120);
  wm.autoConnect(DEV_NAME);

  btn.onPressFor(pressCB, 3000);

  pinMode(LED, OUTPUT);

  led = new EspalexaDevice(DEV_NAME, stripToggle);
  espalexa.addDevice(led);
  espalexa.begin();
}

void loop() {
  espalexa.loop();
  btn.read();
}
#END
```

### Debug Messages

No debug messages. The sketch compiles correctly but doesn't work as intended.

**Comment by GoTVm** [comment]
SOLVED: followed [this guide](https://github.com/Aircoookie/Espalexa/issues/99) on ESPAlexa's GitHub on how to make them work together and so far it seems to work without issue.

**Comment by tablatronix** [comment]
Ah I see, yeah anything trying to use a webserver , ideally espalexa should have a way to start and stop its webserver also, and not do it in constructor or whatever it is doing. Also yeah passing a single webserver to both libraries would be useful also
