### ISSUE TITLE
Error complie demo app in Adurino 1.8 + WiFi manager 2.0.10

### ISSUE THREAD

**Issue by cstirasatian** [tzapu/WiFiManager#1392]
### Hi I was tried to complie basic demo app  on lasted wifimanager 2.x but I got error follow. However try with with wifimnager 0.16 is work without error

Arduino: 1.8.19 (Windows Store 1.8.57.0) (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

C:\Users\cstir\Documents\Arduino\libraries\WiFiManager\WiFiManager.cpp: In member function 'String WiFiManager::getInfoData(String)':

C:\Users\cstir\Documents\Arduino\libraries\WiFiManager\WiFiManager.cpp:2112:44: error: 'class ESP8266WiFiClass' has no member named 'softAPSSID'

     p.replace(FPSTR(T_1),htmlEntities(WiFi.softAPSSID()));

                                            ^

exit status 1

Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by tablatronix** [comment]
Thanks, I think this is fixed in the repo, but not the lib manager yet. Ill make a new beta
