### ISSUE TITLE
Autofill AP stops after single quote in name

### ISSUE THREAD

**Issue by andersmmg** [tzapu/WiFiManager#1398]
#### Hardware
WiFimanager Branch/Release:  Master

Esp8266/Esp32: Esp8266

Hardware: Wemos D1 Mini

Core Version: 2.4.0, staging

### Description

Tapping an AP with an single quote in the name doesn't fill correctly.
E.g. "Cat's Network" would show in the list of found APs, tapping it only fills the field with "Cat", so everything before the first single quote.

### Settings in IDE

Module: Wemos D1

Happens with any bare WiFiManager example I tested.

**Comment by tablatronix** [comment]
#1413 
This should be fixed I think
