### ISSUE TITLE
Add a new page after esp32 is connected to wifi.

### ISSUE THREAD

**Issue by kargarisaac** [tzapu/WiFiManager#1402]
Hi,

I want to add a feature to WiFi Manager and need some tips. The goal is to get from the user some information in addition to the WiFi credentials. I want to open a new page after the user enters wifi credentials and push the button to save. In my case, When the esp32 connects to the internet, it goes to deep sleep because it uses a battery and the power is very limited. Next I want to open a new page for that user to get additional data. This data will be sent to cloud through internet without the esp32 being active.

The pipeline:

board powers up --> set wifi credentials --> save --> esp32 connects to wifi --> goes to deep sleep --> a new page will pop up --> user enters additional data --> data will be sent to cloud through internet (not esp32)

Thank you in advance

**Comment by jayvdw13** [comment]
any progress on this?

**Comment by tablatronix** [comment]
There are at least 2 ways to do this
