### ISSUE TITLE
Compile error with latest betas in combination with neopixelbus

### ISSUE THREAD

**Issue by akamming** [tzapu/WiFiManager#1405]
#### Hardware
WiFimanager Branch/Release:  Master, as of 2.0.10-beta

Esp8266

Hardware:			Wemos D1

Core Version:      	3.0.2

### Description

1st of all thanx for this great peace of software, using it a lot.  I only had a very weird problem:

As of beta 2.0.10-beta (also checked on 2.0.11, when reverting to 2.0.9 all is fine) i get i compile error in another library (https://github.com/Makuna/NeoPixelBus) :

`
Arduino:1.8.19 (Windows 10), Board:"LOLIN(WEMOS) D1 mini (clone), 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, DOUT (compatible), 40MHz, 4MB (FS:2MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

In file included from C:\Users\kammi493\Documents\Arduino\WordclockV3\WordclockV3.ino:37:

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColor.h: In constructor 'RgbColor::RgbColor(uint8_t, uint8_t, uint8_t)':

C:\Users\kammi493\Documents\Arduino\libraries\WiFiManager/WiFiManager.h:49:28: error: anachronistic old-style base class initializer [-fpermissive]

   49 | #define G(string_literal)  (String(FPSTR(string_literal)).c_str())

      |                            ^

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColor.h:47:15: note: in expansion of macro 'G'

   47 |         R(r), G(g), B(b)

      |               ^

In file included from C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/NeoPixelBus.h:53,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\ledfunctions.h:29,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\WordclockV3.ino:39:

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColor.h:47:24: error: no matching function for call to 'RgbColorBase::RgbColorBase(const char*)'

   47 |         R(r), G(g), B(b)

      |                        ^

In file included from C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColor.h:30,

                 from C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/NeoPixelBus.h:53,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\ledfunctions.h:29,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\WordclockV3.ino:39:

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColorBase.h:33:8: note: candidate: 'constexpr RgbColorBase::RgbColorBase()'

   33 | struct RgbColorBase

      |        ^~~~~~~~~~~~

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColorBase.h:33:8: note:   candidate expects 0 arguments, 1 provided

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColorBase.h:33:8: note: candidate: 'constexpr RgbColorBase::RgbColorBase(const RgbColorBase&)'

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColorBase.h:33:8: note:   no known conversion for argument 1 from 'const char*' to 'const RgbColorBase&'

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColorBase.h:33:8: note: candidate: 'constexpr RgbColorBase::RgbColorBase(RgbColorBase&&)'

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColorBase.h:33:8: note:   no known conversion for argument 1 from 'const char*' to 'RgbColorBase&&'

In file included from C:\Users\kammi493\Documents\Arduino\WordclockV3\WordclockV3.ino:37:

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColor.h: In constructor 'RgbColor::RgbColor(uint8_t)':

C:\Users\kammi493\Documents\Arduino\libraries\WiFiManager/WiFiManager.h:49:28: error: anachronistic old-style base class initializer [-fpermissive]

   49 | #define G(string_literal)  (String(FPSTR(string_literal)).c_str())

      |                            ^

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColor.h:57:24: note: in expansion of macro 'G'

   57 |         R(brightness), G(brightness), B(brightness)

      |                        ^

In file included from C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/NeoPixelBus.h:53,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\ledfunctions.h:29,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\WordclockV3.ino:39:

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColor.h:57:51: error: no matching function for call to 'RgbColorBase::RgbColorBase(const char*)'

   57 |         R(brightness), G(brightness), B(brightness)

      |                                                   ^

In file included from C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColor.h:30,

                 from C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/NeoPixelBus.h:53,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\ledfunctions.h:29,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\WordclockV3.ino:39:

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColorBase.h:33:8: note: candidate: 'constexpr RgbColorBase::RgbColorBase()'

   33 | struct RgbColorBase

      |        ^~~~~~~~~~~~

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColorBase.h:33:8: note:   candidate expects 0 arguments, 1 provided

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColorBase.h:33:8: note: candidate: 'constexpr RgbColorBase::RgbColorBase(const RgbColorBase&)'

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColorBase.h:33:8: note:   no known conversion for argument 1 from 'const char*' to 'const RgbColorBase&'

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColorBase.h:33:8: note: candidate: 'constexpr RgbColorBase::RgbColorBase(RgbColorBase&&)'

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColorBase.h:33:8: note:   no known conversion for argument 1 from 'const char*' to 'RgbColorBase&&'

In file included from C:\Users\kammi493\Documents\Arduino\WordclockV3\WordclockV3.ino:37:

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/Rgb48Color.h: In constructor 'Rgb48Color::Rgb48Color(uint16_t, uint16_t, uint16_t)':

C:\Users\kammi493\Documents\Arduino\libraries\WiFiManager/WiFiManager.h:49:28: error: anachronistic old-style base class initializer [-fpermissive]

   49 | #define G(string_literal)  (String(FPSTR(string_literal)).c_str())

      |                            ^

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/Rgb48Color.h:47:15: note: in expansion of macro 'G'

   47 |         R(r), G(g), B(b)

      |               ^

In file included from C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/NeoPixelBus.h:55,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\ledfunctions.h:29,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\WordclockV3.ino:39:

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/Rgb48Color.h:47:24: error: no matching function for call to 'RgbColorBase::RgbColorBase(const char*)'

   47 |         R(r), G(g), B(b)

      |                        ^

In file included from C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColor.h:30,

                 from C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/NeoPixelBus.h:53,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\ledfunctions.h:29,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\WordclockV3.ino:39:

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColorBase.h:33:8: note: candidate: 'constexpr RgbColorBase::RgbColorBase()'

   33 | struct RgbColorBase

      |        ^~~~~~~~~~~~

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColorBase.h:33:8: note:   candidate expects 0 arguments, 1 provided

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColorBase.h:33:8: note: candidate: 'constexpr RgbColorBase::RgbColorBase(const RgbColorBase&)'

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColorBase.h:33:8: note:   no known conversion for argument 1 from 'const char*' to 'const RgbColorBase&'

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColorBase.h:33:8: note: candidate: 'constexpr RgbColorBase::RgbColorBase(RgbColorBase&&)'

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColorBase.h:33:8: note:   no known conversion for argument 1 from 'const char*' to 'RgbColorBase&&'

In file included from C:\Users\kammi493\Documents\Arduino\WordclockV3\WordclockV3.ino:37:

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/Rgb48Color.h: In constructor 'Rgb48Color::Rgb48Color(uint16_t)':

C:\Users\kammi493\Documents\Arduino\libraries\WiFiManager/WiFiManager.h:49:28: error: anachronistic old-style base class initializer [-fpermissive]

   49 | #define G(string_literal)  (String(FPSTR(string_literal)).c_str())

      |                            ^

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/Rgb48Color.h:57:24: note: in expansion of macro 'G'

   57 |         R(brightness), G(brightness), B(brightness)

      |                        ^

In file included from C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/NeoPixelBus.h:55,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\ledfunctions.h:29,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\WordclockV3.ino:39:

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/Rgb48Color.h:57:51: error: no matching function for call to 'RgbColorBase::RgbColorBase(const char*)'

   57 |         R(brightness), G(brightness), B(brightness)

      |                                                   ^

In file included from C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColor.h:30,

                 from C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/NeoPixelBus.h:53,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\ledfunctions.h:29,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\WordclockV3.ino:39:

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColorBase.h:33:8: note: candidate: 'constexpr RgbColorBase::RgbColorBase()'

   33 | struct RgbColorBase

      |        ^~~~~~~~~~~~

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColorBase.h:33:8: note:   candidate expects 0 arguments, 1 provided

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColorBase.h:33:8: note: candidate: 'constexpr RgbColorBase::RgbColorBase(const RgbColorBase&)'

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColorBase.h:33:8: note:   no known conversion for argument 1 from 'const char*' to 'const RgbColorBase&'

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColorBase.h:33:8: note: candidate: 'constexpr RgbColorBase::RgbColorBase(RgbColorBase&&)'

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbColorBase.h:33:8: note:   no known conversion for argument 1 from 'const char*' to 'RgbColorBase&&'

In file included from C:\Users\kammi493\Documents\Arduino\WordclockV3\WordclockV3.ino:37:

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbwColor.h: In constructor 'RgbwColor::RgbwColor(uint8_t, uint8_t, uint8_t, uint8_t)':

C:\Users\kammi493\Documents\Arduino\libraries\WiFiManager/WiFiManager.h:49:28: error: anachronistic old-style base class initializer [-fpermissive]

   49 | #define G(string_literal)  (String(FPSTR(string_literal)).c_str())

      |                            ^

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbwColor.h:47:15: note: in expansion of macro 'G'

   47 |         R(r), G(g), B(b), W(w)

      |               ^

In file included from C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/NeoPixelBus.h:61,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\ledfunctions.h:29,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\WordclockV3.ino:39:

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbwColor.h:47:13: error: unnamed initializer for 'RgbwColor', which has no base classes

   47 |         R(r), G(g), B(b), W(w)

      |             ^

In file included from C:\Users\kammi493\Documents\Arduino\WordclockV3\WordclockV3.ino:37:

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbwColor.h: In constructor 'RgbwColor::RgbwColor(uint8_t)':

C:\Users\kammi493\Documents\Arduino\libraries\WiFiManager/WiFiManager.h:49:28: error: anachronistic old-style base class initializer [-fpermissive]

   49 | #define G(string_literal)  (String(FPSTR(string_literal)).c_str())

      |                            ^

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbwColor.h:57:15: note: in expansion of macro 'G'

   57 |         R(0), G(0), B(0), W(brightness)

      |               ^

In file included from C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/NeoPixelBus.h:61,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\ledfunctions.h:29,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\WordclockV3.ino:39:

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbwColor.h:57:13: error: unnamed initializer for 'RgbwColor', which has no base classes

   57 |         R(0), G(0), B(0), W(brightness)

      |             ^

In file included from C:\Users\kammi493\Documents\Arduino\WordclockV3\WordclockV3.ino:37:

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbwColor.h: In constructor 'RgbwColor::RgbwColor(const RgbColor&)':

C:\Users\kammi493\Documents\Arduino\libraries\WiFiManager/WiFiManager.h:49:28: error: anachronistic old-style base class initializer [-fpermissive]

   49 | #define G(string_literal)  (String(FPSTR(string_literal)).c_str())

      |                            ^

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbwColor.h:66:9: note: in expansion of macro 'G'

   66 |         G(color.G),

      |         ^

In file included from C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/NeoPixelBus.h:61,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\ledfunctions.h:29,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\WordclockV3.ino:39:

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/RgbwColor.h:65:19: error: unnamed initializer for 'RgbwColor', which has no base classes

   65 |         R(color.R),

      |                   ^

In file included from C:\Users\kammi493\Documents\Arduino\WordclockV3\WordclockV3.ino:37:

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/Rgbw64Color.h: In constructor 'Rgbw64Color::Rgbw64Color(uint16_t, uint16_t, uint16_t, uint16_t)':

C:\Users\kammi493\Documents\Arduino\libraries\WiFiManager/WiFiManager.h:49:28: error: anachronistic old-style base class initializer [-fpermissive]

   49 | #define G(string_literal)  (String(FPSTR(string_literal)).c_str())

      |                            ^

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/Rgbw64Color.h:48:15: note: in expansion of macro 'G'

   48 |         R(r), G(g), B(b), W(w)

      |               ^

In file included from C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/NeoPixelBus.h:62,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\ledfunctions.h:29,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\WordclockV3.ino:39:

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/Rgbw64Color.h:48:13: error: unnamed initializer for 'Rgbw64Color', which has no base classes

   48 |         R(r), G(g), B(b), W(w)

      |             ^

In file included from C:\Users\kammi493\Documents\Arduino\WordclockV3\WordclockV3.ino:37:

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/Rgbw64Color.h: In constructor 'Rgbw64Color::Rgbw64Color(uint16_t)':

C:\Users\kammi493\Documents\Arduino\libraries\WiFiManager/WiFiManager.h:49:28: error: anachronistic old-style base class initializer [-fpermissive]

   49 | #define G(string_literal)  (String(FPSTR(string_literal)).c_str())

      |                            ^

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/Rgbw64Color.h:58:15: note: in expansion of macro 'G'

   58 |         R(0), G(0), B(0), W(brightness)

      |               ^

In file included from C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/NeoPixelBus.h:62,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\ledfunctions.h:29,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\WordclockV3.ino:39:

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/Rgbw64Color.h:58:13: error: unnamed initializer for 'Rgbw64Color', which has no base classes

   58 |         R(0), G(0), B(0), W(brightness)

      |             ^

In file included from C:\Users\kammi493\Documents\Arduino\WordclockV3\WordclockV3.ino:37:

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/Rgbw64Color.h: In constructor 'Rgbw64Color::Rgbw64Color(const Rgb48Color&)':

C:\Users\kammi493\Documents\Arduino\libraries\WiFiManager/WiFiManager.h:49:28: error: anachronistic old-style base class initializer [-fpermissive]

   49 | #define G(string_literal)  (String(FPSTR(string_literal)).c_str())

      |                            ^

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/Rgbw64Color.h:75:9: note: in expansion of macro 'G'

   75 |         G(color.G),

      |         ^

In file included from C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/NeoPixelBus.h:62,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\ledfunctions.h:29,

                 from C:\Users\kammi493\Documents\Arduino\WordclockV3\WordclockV3.ino:39:

C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/Rgbw64Color.h:74:19: error: unnamed initializer for 'Rgbw64Color', which has no base classes

   74 |         R(color.R),

      |                   ^

exit status 1

Fout bij het compileren voor board LOLIN(WEMOS) D1 mini (clone)
` 

### Settings in IDE

Module:  			Wemos D1

Additional libraries: [NeoPixelbus](https://github.com/Makuna/NeoPixelBus)

### Sketch

https://github.com/akamming/WordclockV3

### Debug Messages

N.A.

**Comment by Makuna** [comment]
This is not a NeoPixelBus problem.  These lines in your error output tells you the answer...
```
C:\Users\kammi493\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/Rgbw64Color.h:58:13: error: unnamed initializer for 'Rgbw64Color', which has no base classes

   58 |         R(0), G(0), B(0), W(brightness)

      |    
WiFiManager.h:49:28: error: anachronistic old-style base class initializer [-fpermissive]

   49 | #define G(string_literal)  (String(FPSTR(string_literal)).c_str())
```
Wifimanger is defining a macro that is too simple and easily present in other code.  This is real bad, as macros just replace all code after it (like in NeoPixelBus) with the macro parts.  It should avoid macros and use static inline functions, at the very least expand the name of the macro to something not so commonly used.
