### ISSUE TITLE
Save Wifi Settings from Setup/Loop - Not via Portal

### ISSUE THREAD

**Issue by Michail1** [tzapu/WiFiManager#1418]
Everything works great on ESP8266/ESP32 (M5Stack), but I am unable to directly save SSID/Password other than AutoConfig.

If there a way to read/write SSID/Password directly to the stored area?

When I flash a new mcu, instead of going through the webportal to configure it to save SSID/Password, I would like to be able to directly write a default configuration.  For example, reading a firstboot file from spiffs in order to pre-setup a configuration including Wifi credencials prior to deleting the firstboot file.

There is a way to reset them, but not to write them (other than web portal).

**Comment by tablatronix** [comment]
#1433
