### ISSUE TITLE
Static IP change after first restart to DHCP

### ISSUE THREAD

**Issue by Mehdi-Dehghan** [tzapu/WiFiManager#1423]
WiFimanager Branch/Release:  Master 2.0.11-beta
Esp8266
Hardware:			ESP-12e
### Description
Hi
I used "wifiManager.setShowStaticFields(true);" to show static fields. after first config the module connect with static ip but after first restart, module use DHCP.
could you please help me how can i coupe with this issue.
thanks

### Settings in IDE

Module:  			NodeMcu

**Comment by Mehdi-Dehghan** [comment]
I tried to use setSaveParamsCallback() and also save the data to memory with using littlefs. That has been working true.

**Comment by tablatronix** [comment]
Yeah you will have to save and set it back everytime esp lib does not have a persistent flash for ip afaik
