### ISSUE TITLE
how to use a different port to 80 for the portal 

### ISSUE THREAD

**Issue by mjtrini** [tzapu/WiFiManager#1436]
Hello,

Is there a way to set a different port for the configuration portal? For example if I want to use port 50, how can this be set? In my case the portal address would become 192.168.4.1:50

Regards,
Michael.

**Comment by tablatronix** [comment]
setHttpPort

**Comment by mjtrini** [comment]
Thanks for the reply. Can you give an example sketch on how to use setHttpPort?
