### ISSUE TITLE
RTC memory access after deep sleep

### ISSUE THREAD

**Issue by dinonovak** [tzapu/WiFiManager#144]
HI,

I am trying to save some data to RTC memory so that I can use it after waking from deep sleep.
I tries location 65, 100 & 150, but data is lost every time I wake up from deep sleep

Is RTC memory used by the class or erased ?

eg:
# define RTC_BASE 160;

system_rtc_mem_read(RTC_BASE,buf,2);

Thanx,
DiNo

**Comment by tzapu** [comment]
hi, no, rtc is not touched,
i am using it quite sucessfully here 
https://github.com/tzapu/ESP8266ArducamTimelapse

together with WiFiManager and a lot of other libraries
65 i think worked for me

**Comment by fixduino** [comment]
i wanna setup RTC via wifimanager beside ssid dan password connection,, how to save data to RTC? thanks
