### ISSUE TITLE
Abandon Auto Reconnect

### ISSUE THREAD

**Issue by DrJaymz** [tzapu/WiFiManager#1450]
In my application I want the portal to appear until it times out, if the Wi-Fi credential are saved but its unable to reconnect then I want to continue in an offline mode.

The problem is, I can't seem to see how to stop it trying to reconnect forever.  It used to work fine, but I have opened a 3 year old project and functionality seems to have moved on somewhat - which is great.

I tried disconnect etc.  

Still keep getting

```
no network found, reconnect after 1s
reconnect
scandone
```

which appears to be from the manager.

**Comment by tablatronix** [comment]
well in wm use setConfigPortalTimeout

**Comment by tablatronix** [comment]
That is the esp library, disable esp autoreconnect

**Comment by DrJaymz** [comment]
The timeout is set. It does timeout. And my mainloop begins, but it keeps trying to reconnect continually according to the debug output.

**Comment by DrJaymz** [comment]
> Yeah that an ESP thing, ESP.setAutoReconnect(false) or just setMode(WIFI_OFF)

its an 8266 does have either of those methods, however it does have WiFi.mode(WIFI_OFF);
so trying that.

Thanks for the help, I couldn't see where those messages are coming from, I searched my code and he WIFI manager code but couldn't get it to stop.   The reason it matters is because its a sensor that will normally be on WIFI but if it can't connect then I want the output on serial port - and obviously random messages I don't need!
