### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by kararosev** [tzapu/WiFiManager#146]
We are using an ESP8266 12F on a board we are designing ourself and I was wondering if I had to include anything to ensure that WiFi manager will still work. We have been using an Sparkfun ESP dev thing for testing up until this point.

**Comment by tzapu** [comment]
hi, it should be working fine, it doesn t need anything specific
let me know the outcome, or where i could follow, quite curious :D

**Comment by kararosev** [comment]
thank you ! I will keep you updated for sure! One more question, is there a
way to also assign a username or unique device while using WiFiManager?
