### ISSUE TITLE
The device does not generate the wifi network in Access Point Mode [ESP32]

### ISSUE THREAD

**Issue by MattiaCC93** [tzapu/WiFiManager#1481]
Hi,
I have successfully flashed my ESP32-C3 esp32-c3-devkitc-02, the system boots but the wifi network is not generated. Yet from the IoT device logs, everything seems to work. I cannot see the wifi network neither from my PC nor from my mobile.
I thank you in advance whoever helps me.

This is the code used (the original code):
![image](https://user-images.githubusercontent.com/38031049/186923836-8e2b40ab-10ca-4002-8c05-ee38abf29bf7.png)

These are the  Arduino IDE logs, no warnings:
![image](https://user-images.githubusercontent.com/38031049/186923762-6b74a42f-e850-408f-8ef4-20086a975835.png)

These are the logs of the device:
![image](https://user-images.githubusercontent.com/38031049/186923800-56ae071f-0aa5-463c-a2b9-1b68d17e59b2.png)

Thanks!!

**Comment by tablatronix** [comment]
#1422

**Comment by tablatronix** [comment]
#1479

**Comment by tablatronix** [comment]
#1482

**Comment by bantaj** [comment]
unsubscribe
