### ISSUE TITLE
Question on WiFiManager use

### ISSUE THREAD

**Issue by cniedzi** [tzapu/WiFiManager#1486]
Hi,
I don't know if this is a right place for questions concerning WiFiManager; if not  please advise me where should I go.

I build the ESP32S2-based device that should connect to last connected WiFi after powering on, without passing any credentials or waiting. If there aren't any known WiFis, the program should go further without any WiFi connection. The only way to set WiFI credentials is WiFiManager's wm.startConfigPortal() triggered by pushing a button.
So the code framework will be:

```
void setup() {
	WiFiManager wm;
	WiFi.mode(WIFI_STA);
        WiFi.begin(); //??????????

} 

void loop() {
	if (buttonPushed) {
		wm.startConfigPortal("AP");
	}
}
```

Is this a correct way to try to connect to the last connected WiFi by means of WiFi.begin()?
Where the last known WiFi credentials are stored (in particular these set by WiFIManager), in internal registers of ESP32?

**Comment by tablatronix** [comment]
Yes
