### ISSUE TITLE
ESP32S3 wifi not broadcasting during AP mode

### ISSUE THREAD

**Issue by shashi5841** [tzapu/WiFiManager#1488]
Tested with esp32-s3 with the same issue.
ESP32-S3 with WiFiManager lib.

Can't find SSID AutoConnectAP, when the module is in AP mode.

Terminal output:

SPIFFS mounted
*wm:[1] AutoConnect
*wm:[2] ESP32 event handler enabled
*wm:[2] Connecting as wifi client...
*wm:[2] setSTAConfig static ip not set, skipping
*wm:[1] Connecting to SAVED AP: espressif
*wm:[1] connectTimeout not set, ESP waitForConnectResult...
*wm:[2] [EVENT] WIFI_REASON: 201
*wm:[2] [EVENT] WIFI_REASON: NO_AP_FOUND
*wm:[2] Connection result: WL_NO_SSID_AVAIL
*wm:[1] AutoConnect: FAILED
*wm:[2] Starting Config Portal
*wm:[2] Disabling STA
*wm:[2] Enabling AP
*wm:[1] StartAP with SSID: AutoConnectAP
*wm:[2] AP has anonymous access!
*wm:[1] AP IP address: 192.168.4.1
*wm:[1] Starting Web Portal
*wm:[2] HTTP server started
*wm:[2] Config Portal Running, blocking, waiting for clients...
*wm:[2] NUM CLIENTS: 0
*wm:[2] NUM CLIENTS: 0
*wm:[2] NUM CLIENTS: 0
*wm:[2] NUM CLIENTS: 0

I used 4 different mobile phones and different laptop PC to find esp32s3 in the WiFi list but the module was not broadcasting.

Used the latest library of WiFi manager v2.0.12-beta

Please advise what to do ??

**Comment by tablatronix** [comment]
#1482
