### ISSUE TITLE
Access Point not necessary with previous saved credentials

### ISSUE THREAD

**Issue by piertoni** [tzapu/WiFiManager#149]
Hi,
Imagine a router and ESP power down. The router maybe takes a while to span a wi-fi network.
In the meanwhile ESP boots and can't connect, then goes to AP and doesn't connect anymore to router. This is not what I want for an IoT device.
Is possible to simply let ESP trying to connect to wi-fi without AP mode?

**Comment by tzapu** [comment]
yes, either use `wifiManager.setConfigPortalTimeout(180);` so it stays in portal for said timeout, then make it reboot and retry (this is what i use) or just start config portal manually when you actually need it.

too many problems could arise otherwise

**Comment by kentaylor** [comment]
Do not use the autoconnect functionality. Then it "Is possible to simply let ESP trying to connect to wi-fi without AP mode".

Start configuration mode manually when "you actually need it".
