### ISSUE TITLE
Wait before connecting (because GPRS could be used)

### ISSUE THREAD

**Issue by eried** [tzapu/WiFiManager#1492]
How can I force WifiManager to always show the captive portal in AP mode for X minutes before connecting to the saved credentials?

**Comment by eried** [comment]
I will answer myself 
https://github.com/JAndrassy/SunriseClock/blob/main/SunriseClock/SunriseClock.ino#L323

**Comment by tablatronix** [comment]
setCaptivePortalTimeout

**Comment by eried** [comment]
Yes thanks 😵
