### ISSUE TITLE
Access wi-fi settings from station mode

### ISSUE THREAD

**Issue by piertoni** [tzapu/WiFiManager#150]
Is it possible to access and change settings from station mode?

**Comment by tzapu** [comment]
every time you call WiFi.begin(ssid,pass) it changes those settings

**Comment by piertoni** [comment]
Sorry,
I meant if is it possible to access the settings webpage when the device is connected to router as station mode.

**Comment by tzapu** [comment]
currently no, and there s a bug making it impossible to start it manually

**Comment by kentaylor** [comment]
Using the forked version of this library at https://github.com/kentaylor/WiFiManager/ it is possible to access the settings page when the device is connected to a network via the network to which it is connected.

**Comment by tzapu** [comment]
@piertoni it woulc be wonderful if you could test the fork that @kentaylor was so kind to provide and see if it works better for your needs.

reports are both welcome and needed :D
thanks
