### ISSUE TITLE
QUESTION: How to get post data

### ISSUE THREAD

**Issue by ByronAP** [tzapu/WiFiManager#1506]
#### Hardware
WiFimanager Branch/Release:  Master
Hardware:			ESP32

### Description

Does anyone have an example on how to get post data? 

I use 
`wm.server->on("/saveschedule", HTTP_POST, handleSaveScheduleRoute);`

and

```
void handleSaveScheduleRoute()
    {
#if defined(DEBUG)
        Serial.println("[HTTP] handle save schedule");
#endif
        wm.server->send(200, "text/html", "hello you are at save schedule");
    }
```

which for some reason catches both get and post... but anyway I do not see a way to access the post data, anyone have an example on how to do this?

Thank you :-)

**Comment by ByronAP** [comment]
OK so looking at the code the answer is quite simple since WM is using the default WebServer.h thus checking for a 'plain' argument to see if raw data was sent then getting the contents of the 'plain' arg.

Example handler:
```
void handlePostDataRoute()
    {
        if (wm.server->hasArg("plain") == false)
        {
            // no raw data posted
            wm.server->send(400);
            return;
        }

        // this is the data
        String body = wm.server->arg("plain");

        Serial.println(body);

        // return success
        wm.server->send(204);
    }

```

**Comment by tablatronix** [comment]
This is really an esp webserver question
