### ISSUE TITLE
I always see *WM: Using last saved values, should be faster

### ISSUE THREAD

**Issue by netdudeuk** [tzapu/WiFiManager#1522]
Hardware:			ESP8266 NodeMcu ESP-12E Development Board

Core Version:      	From - PlatformIO tzapu/WiFiManager@^0.16.0

PlatformIO won't let me select any of the much later beta versions.

My device always shows the below serial output and has never let me connect to the AP using my phone.  It always just connects to the WLAN AP that I was previously using before I added in WIFIMANAGER to my existing code.

I would have expected that the resetSetttings() ought have forced the AP pop up every time.

I've never told WIFIMANAGER my SSID and password but I still get a connection.

I've just found that I can use the BASIC sketch in the Arduino IDE and the resetSetttings() command does clear the LAN information.  If I don't enter the WIFI info and download my own project via PLATFORMIO then the settings have indeed been cleared and I get a new AP.  However, the resetSetttings() in my own code still doesn't clear the settings.

Module:  			ESP8266 NodeMcu ESP-12E Development Board

### Sketch

#include <ESP8266WiFi.h>
#include <WiFiManager.h>

void setup()

 WiFiManager wifiManager;
 wifiManager.resetSettings();
 wifiManager.autoConnect("AutoConnectAP", "Nixie");

#END
```

Here's my platformio.ini -

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
upload_port = COM[4]
build_flags = 
	-D_BSD_SOURCE
lib_deps = 
	RTClib
	adafruit/Adafruit BusIO@^1.11.3
	tzapu/WiFiManager@^0.16.0
lib_ignore = TinyWireM

### Debug Messages

*WM: settings invalidated
*WM: THIS MAY CAUSE AP NOT TO START UP PROPERLY. YOU NEED TO COMMENT IT OUT AFTER ERASING THE DATA.
*WM:
*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Status:
*WM: 0      
*WM: Using last saved values, should be faster
*WM: Connection result: 
*WM: 3    
*WM: IP Address:
*WM: 192.168.1.194

WiFi connected
IP address: 192.168.1.194

**Comment by netdudeuk** [comment]
Managed to get it working thanks.

**Comment by tablatronix** [comment]
Yeah you have to add a custom lib dep in pio its annoying

**Comment by netdudeuk** [comment]
> Yeah you have to add a custom lib dep in pio its annoying

I didn't actually do that.  Are you referring the need to add a beta version ?  I've just got 	tzapu/WiFiManager@^0.16.0 listed in mine.  Please do you have a better lib dep entry to replace that one ?  Thanks.

**Comment by tablatronix** [comment]
Yeah github master
