### ISSUE TITLE
Disable "Need Authorization" Message on connect to AP of ESP32

### ISSUE THREAD

**Issue by SuriSureda** [tzapu/WiFiManager#1526]
Hi I am wondering if it could be possible to remove the message "Needs authorization" ("Se requiere autorización") when my phone gets connected to ESP32.
![1 (Personalizado)](https://user-images.githubusercontent.com/61196829/204176549-6d386578-2f65-498b-84c0-ae56d52f7c96.jpg)

It also automatically opens the Portal, I supose this is because of the above.
![2 (Personalizado)](https://user-images.githubusercontent.com/61196829/204176558-4088bcea-6ec0-4dec-8506-86fca16af898.jpg)

I'm developing an Android App which would handle the WiFI config, making API calls instead of using the Wifi Manager portal(which I have already implemented), so it would be great to be able to avoid mobiles to open or show the message of Needs Config or Authorization.

**Comment by tablatronix** [comment]
You can turn off the captiveportal in wm. No idea what the other thing is I assume this means no internet
