### ISSUE TITLE
Connection not possible with a smartphone using the default channel 1 if other WiFi AP is using it

### ISSUE THREAD

**Issue by jjbubka** [tzapu/WiFiManager#153]
First of all, thank you for this **awesome** library.

I want to share with you one problem regardin the connection to the ESP with a smartphone. This is happening because of the collision of the WiFi signal (other APs in channel 1). I have a workaround to first scan the environment and selecting the first free channel (if possible). Of course this algorithm could be improved, but this works very good.

in **WiFiManager::setupConfigPortal()** I have changed:

`WiFi.softAP(_apName.c_str(), _apPassword);`

to this:

`WiFi.softAP(_apName.c_str(), _apPassword, getFirstFreeChannel()); //modified to avoid WiFi collisions`

where the function to select the channel is:

```
uint8_t WiFiManager::getFirstFreeChannel() {

    int n = WiFi.scanNetworks();
    if (n == 0)
        return 1;

    uint8_t channel = 0;
    bool used = true;

    while (used) {
        ++channel;
        used = false;
        for (int i = 0; i < n; i++) {
            if (WiFi.channel(i) == channel) {
                used = true;
                break;
            }
        }

        if (channel >= 11 && used)
            return 1;
    }

    return channel;

}
```

**Comment by tzapu** [comment]
hi, this is very very interesting, might explain why at some rare but random times, i can t manage to connect from some devices.

thanks for letting me know, will see about adding it
