### ISSUE TITLE
info page displays ESP_ARDUINO_VERSION_MAJOR text instead of value

### ISSUE THREAD

**Issue by olonsoft** [tzapu/WiFiManager#1532]
#### Hardware
WiFimanager Branch/Release:  Master

Esp8266
Hardware:			ESP-12e
Core version
3.0.2
Boot version
31

### Description

Problem description

When I click the info page the values of Arduino Versions are not displayed. Look bellow.

### Settings in IDE

Module:  			NodeMcu

## truncated info page:
```
...
WiFiManager
v2.0.15-rc.1
Arduino
ESP_ARDUINO_VERSION_MAJOR.ESP_ARDUINO_VERSION_MINOR.ESP_ARDUINO_VERSION_PATCH
Build date
Dec 14 2022 13:48:21
...
```

**Comment by tablatronix** [comment]
Give that a try
