### ISSUE TITLE
Compile error from version 2.0.12-beta onwards (set_country_code vs set_country)

### ISSUE THREAD

**Issue by alx-1** [tzapu/WiFiManager#1552]
Hello,

From version 2.0.12-beta, there seems to be an error in WifiManager.cpp preventing compilation of the included Basic.ino example.
Line 3523   
err = esp_wifi_set_country_code(_wificountry.c_str(), true);

Version 2.0.11-beta compiles.

Thank you for your work ++

**Comment by tablatronix** [comment]
Use a new ESP version they changed this

**Comment by alx-1** [comment]
Thank you, it works!
