### ISSUE TITLE
How i can do it? 

### ISSUE THREAD

**Issue by snow79** [tzapu/WiFiManager#1554]
Hi guys, i have a question... I'm using an esp32 and i like to make some like this...
when my esp power on every time start in ap mode... where i can set ssid password and other parameter... and after 2 minuts try to connect to wifi with the stored value...
in all case i need to start in ap mode and wait some times client connect how i can do it? some one can help me? because don't exist an example in all the web :D 
Too tnk all the world

**Comment by tablatronix** [comment]
this are examples in the library
