### ISSUE TITLE
[EVENT] WIFI_REASON: 7

### ISSUE THREAD

**Issue by Peterpanik** [tzapu/WiFiManager#1564]
Hi 

I am some times getting this error code when I am trying to connect to wifi: 
[EVENT] WIFI_REASON: 7

Is there a certain reason for this errorcode and is there an overview of all these error codes in wifimanager? 

Thanks in advance

Best regards 
Peter

**Comment by Bighoneypot** [comment]
Hi @Peterpanik ,
this is your error,

WL_STATION_WRONG_PASSWORD

**Comment by tablatronix** [comment]
Try updating esp library there were some auth bugs
