### ISSUE TITLE
Way to disable pages from being served?

### ISSUE THREAD

**Issue by BlaT2512** [tzapu/WiFiManager#1566]
#### Hardware
WiFimanager Branch/Release:  Master

Esp8266/Esp32: ESP8266

Hardware: ESP-12e

Core Version: 2.4.0, staging

### Description

I was wondering if there was a way to actually disable pages on the configuration portal such as the OTA update page `/update`. I know how to disable the update menu item using `setMenu` and to disable it off of the info page with `setInfoShowUpdate` but the page can still be opened by navigating directly to the `/update` page so is there a way to disable pages from being served at all?

### Settings in IDE

Module: Wemos D1 / Bare ESP-12F module

Additional libraries: N/A

### Sketch

N/A

### Debug Messages

N/A

**Comment by tablatronix** [comment]
yeah #982 
For now I think you can override them with an empty callback
