### ISSUE TITLE
Question: Authentication on Portal

### ISSUE THREAD

**Issue by Catta1997** [tzapu/WiFiManager#1576]
Is possible to put an authentication to access to the config portal? I do not want that anyone can configure my ESP but at the same time I want the portal.

Or do not have portal on localIP, I mean:
- ESP create own AP (ESP-WiFi with password) if my esp is connected to my home wifi I can access to portal also on localIP, how can I have portal only if I connect to the AP and not on localIP?

**Comment by Bighoneypot** [comment]
@Catta1997 UP ;-)

**Comment by tablatronix** [comment]
Yeah I left that in to test, I think it does not work with captive portals hence why it is not enabled

**Comment by Bighoneypot** [comment]
> HI
> 
> > Yeah I left that in to test, I think it does not work with captive portals hence why it is not enabled.
> 
> it work form me if I visit `192.168.4.1` or local IP, what you mean with "not work with captive portals"?
> 
> > It might be better to add plain http auth form
> 
> yeah but I do not know html so I do not know how to do a plain http auth .

Can you share picture and comment it? I need to understand

**Comment by tablatronix** [comment]
Captive portal is the sandboxed webpage that automaticallty pops up
