### ISSUE TITLE
wifiManager.setConfigPortalTimeout should only time out if no client connected to AP

### ISSUE THREAD

**Issue by probonopd** [tzapu/WiFiManager#1589]
E.g., when we set a 180 seconds timeout like this: `wifiManager.setConfigPortalTimeout(180);`

The 180 seconds timeout should be t for the user to connect to the access point and open the configuration portal. Once the user has connected to the access point and opened the configuration portal, the user should be able to take as much time as they need to enter the WiFi credentials and save them (not just 180 seconds).

Or is that already the case?

**Comment by tablatronix** [comment]
The timer is reset everytime an http connection is made
