### ISSUE TITLE
eeprom 

### ISSUE THREAD

**Issue by domonetic** [tzapu/WiFiManager#16]
share settings with other data

from that address writes data occupy and how to use EEPROM to store other data?

**Comment by tzapu** [comment]
hi, this was intially included, and there was an eeprom start paramter passed on, but i believe it is no longer functional.
I am planning to drop eeprom requirement completely, hopefully before the end of this week. you would then be able to use eeprom as needed

**Comment by domonetic** [comment]
why not use spiffs to store config file? i think, this is more userful.

any ways is good job and simplifi initial configs

**Comment by tzapu** [comment]
well, i'm trying to simplify it as much as possible, and giving options like these for advanced uses.
it's just a matter of getting the time and learning enough to make it a reality :p

**Comment by domonetic** [comment]
I appreciate your work, and is useful. I would like to work with you.

Aprecio tu trabajo y es de real utilidad. Me gustaria colaborar contigo.

**Comment by tzapu** [comment]
hi, that s nice to hear. please feel free to discuss and/or submit as pull request any improvements you might think fit

**Comment by tzapu** [comment]
i ve just commited a new version that does not need eeprom or wificlient anymore
check it out

**Comment by domonetic** [comment]
Great. Very efficient . Do you use the  section of config of wifi. Thanks.
