### ISSUE TITLE
Is there a way to aviod Overflow and being Stuck in aloop when a new Custom Option is added, 

### ISSUE THREAD

**Issue by ahmetcemturan** [tzapu/WiFiManager#1606]
Is there a way to avoid the need to flash everything before making changes to the amount or attributes of custom-options.
At the moment when I want to add a custom-attribute and just upload it via Visual Code, all goes crazy and I have lost all access to the board.  Then I open Arduino and flash all.  then upload the sketch and re enter the custom-options along with SSID and password.
That is acceptable somehow as long as I have access to the board and can plug it into a computer.
It is not possible to fix it, if it is somewhere else and I have updated the firmware OTA.  

Any ideas?

**Comment by tablatronix** [comment]
Sounds like its just crashing, which is bad code or bad esp version
