### ISSUE TITLE
Root menu always empty

### ISSUE THREAD

**Issue by nonsintetic** [tzapu/WiFiManager#1610]
#### Hardware
WiFimanager Branch/Release:  Master

Esp8266/Esp32: 

Hardware:			ESP32

### Description

In the current Master branch the menu in the root page is always empty. Think I figured out why:

The comparison done in `WiFiManager::setMenu()` (to determine what menus should be displayed) always equals false now. Think this is because it's comparing pointers, memory addresses, instead of contents like before. 

See comment in code below:
```
void WiFiManager::setMenu(const char * menu[], uint8_t size){
  _menuIds.clear();
  for(size_t i = 0; i < size; i++){
    for(size_t j = 0; j < _nummenutokens; j++){
      
    //following line is always false, the menu never gets populated
      if(menu[i] == _menutokens[j]){
        if((String)menu[i] == "param") _paramsInWifi = false; // param auto flag
        _menuIds.push_back(j);
      }

    }
  }
}

```

**Comment by tablatronix** [comment]
Yeah looks like I changed the consts def but not the methods that use it crap

**Comment by tablatronix** [comment]
Also need to check that nummenutokens size is set

**Comment by tablatronix** [comment]
9b8de0d
