### ISSUE TITLE
Feature request: Reset Wifi Settings only before boot

### ISSUE THREAD

**Issue by ahmetcemturan** [tzapu/WiFiManager#1613]
I am trying to be able to access the custom configuration parameters without the need to resetting all data.
I tried several ways but somehow it will not work.  
Easiest way would be to just being able to reset the wifi settings so it cant find a suitable wifi to connect and therefore would fire up the Portal.  
Is there another way?

**Comment by tablatronix** [comment]
yeah use the ondemand examples
