### ISSUE TITLE
HTTP_200 is defined in WiFiManager.h but never used

### ISSUE THREAD

**Issue by ahndee** [tzapu/WiFiManager#164]
[Line 27 in WiFiManager.h](https://github.com/tzapu/WiFiManager/blob/master/WiFiManager.h#L27) is
```
const char HTTP_200[] PROGMEM             = "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n";
```

However, `HTTP_200` is never actually used and as such only fills up memory space unnecessarily.

**Comment by tzapu** [comment]
removed on latest git version, thank you very much for using it and letting me know
