### ISSUE TITLE
How to get notification after entering correct or wrong password and SSID

### ISSUE THREAD

**Issue by Emcukcan** [tzapu/WiFiManager#1656]
I already saw similar request about getting notification during entering wrong password. Additionally I suggest it is better to have notification both while correct and wrong credentials. Is there any function that we can utilize for this purpose?

**Comment by Emcukcan** [comment]
Hi, what is the reason of closing this, is this function already available in the most updated version of library?

**Comment by tablatronix** [comment]
There are so many issues with this same question
