### ISSUE TITLE
Using SSD1306 as userinterface during booting ?

### ISSUE THREAD

**Issue by RudolfLapie** [tzapu/WiFiManager#167]
My ESP8266 uses an OLED via I²C as device to interact with the user. During booting I would like it to give feedback about the progress of WifiManager. Something like 'trying to connect to <SSID>' and when it fails a message saying you need to browse to '192.168.4.1' to configure it. Probably this already exists via the debug printing, but not sure

**Comment by tzapu** [comment]
hi, you can use this as a starting point
https://github.com/tzapu/WiFiManager/blob/master/examples/AutoConnectWithFeedback/AutoConnectWithFeedback.ino

should enable you to print what you need in the callback
cheers
