### ISSUE TITLE
Feature request: Make _preloadwifiscan publicly settable

### ISSUE THREAD

**Issue by realA10001986** [tzapu/WiFiManager#1672]
In my projects, the WiFi scan triggered when starting the CP disturbs required network traffic between devices, especially during boot. Setting _preloadwifiscan to false does avoid this, but I would like avoid my users having to patch the WiFiManager library source code when compiling my projects. 

Adding a simple, public setPreLoadWiFi(bool) would really help.

**Comment by tablatronix** [comment]
Yeah I am about to turn that off by default it was experimental and does make the page come up faster, but can also be problematic when joining or using ondemand and trying to join immediatly.

**Comment by realA10001986** [comment]
OK, plain off is fine, too. Thanks!

**Comment by tablatronix** [comment]
94529cd08b5d956f3ca015bb4b6fd0226ee43143
