### ISSUE TITLE
ESP32 fails to reset correctly after connecting to WIFI Network

### ISSUE THREAD

**Issue by serifpersia** [tzapu/WiFiManager#1689]
### Basic Infos
Latest release of WiFiManager from Arduino Library Manager

#### Hardware

Hardware: ESP32-12K(S2)

Core Version: 2.4.0

### Description
Whenever I connect from captive portal to my local network, the esp32 doesn't reset correctly, and I get issue with not being able to connect to the webserver hosted on the esp32, the browser says device refuses to connect. When I press reset button on ESP32 I can access webserver hosted on esp32 ip or mdns, does this have to do with spiffs I assume.
Another minor thing I don't understand is ESP32 doesn't reset when users type wrong password for their ssid, you manually have to erase wifi config, typing correct password doesn't do anything. If you could clarify how that works. 
Thanks!

### Settings in IDE

Module: NodeMCU

Additional libraries: 
#include <ESPAsyncWebServer.h>
#include <SPIFFS.h>

### Sketch
```
#include <WiFiManager.h>
#include <ESPAsyncWebServer.h>
#include <SPIFFS.h>

AsyncWebServer server(80);

void setup() {
  Serial.begin(115200);

  // Initialize SPIFFS
  if (!SPIFFS.begin(true)) {
    Serial.println("An error occurred while mounting SPIFFS");
    return;
  }

  // WiFiManager
  WiFiManager wifiManager;

  if (!wifiManager.autoConnect("AutoConnectAP")) {
    Serial.println("Failed to connect and hit timeout");
  }

  // Route to serve HTML file
  server.on("/", HTTP_GET, [](AsyncWebServerRequest * request) {
    request->send(SPIFFS, "/index.html", "text/html");
  });

  // Route to serve CSS file
  server.on("/style.css", HTTP_GET, [](AsyncWebServerRequest * request) {
    request->send(SPIFFS, "/style.css", "text/css");
  });

  // Route to serve JavaScript file
  server.on("/script.js", HTTP_GET, [](AsyncWebServerRequest * request) {
    request->send(SPIFFS, "/script.js", "application/javascript");
  });

  // Start server
  server.begin();
}

void loop() {
}
```
Here is an image showing the browser, I checked with non spiffs site webserver and it still the same so its not spiffs. After I press reset button or reconnect power to esp32 only then I can connect to the ip of esp32 and access the page.
![image](https://github.com/tzapu/WiFiManager/assets/62844718/5376ed20-4262-4669-9127-f2e023165f5e)

**Comment by serifpersia** [comment]
I fixed this issue I had. I called the callback function on save config to restart esp32 board. I don't know why it doesn't do it automatically but this is the fix to be able to access the server without pressing reset button or reconnecting power to the board.

![image](https://github.com/tzapu/WiFiManager/assets/62844718/050fa1ac-b311-4c93-b93a-98c901e61ede)

**Comment by tablatronix** [comment]
What does your logs say?
Try increasing the retries for connect, this sounds like an ap issue.

Also there is esp bug that you cannot start a new webserver check your webserver error codes, the port stays in use and cannot be released

**Comment by serifpersia** [comment]
> What does your logs say? Try increasing the retries for connect, this sounds like an ap issue.
> 
> Also there is esp bug that you cannot start a new webserver check your webserver error codes, the port stays in use and cannot be released

I found the fix I'm not going to go in depth on this I just wanted to have my webserver accessible immediately after connecting to local network via wifi manager. The image above does it for me. When a password is typed and save is pressed this runs and it resets the esp32 and it I can go into the ip without issue. Thanks for making this lib its so useful. One thing I hate is not having ability to know esp32's ip after connecting. Improv web serial sdk seems like a good option to setup wifi but for now I like using your wifimanager library for wifi setup.

**Comment by tablatronix** [comment]
Yeah rebooting just frees the port I think, I bet if you use a different port it works, ie 8080

**Comment by serifpersia** [comment]
> Yeah rebooting just frees the port I think, I bet if you use a different port it works, ie 8080

Oh I see, well I will try different port for my webserver and see how it goes, since wifimanager webserver also uses port 80 and this bug is not releasing the port if I understood it correctly.
