### ISSUE TITLE
Enabling EAP

### ISSUE THREAD

**Issue by nivedhanatarajan7** [tzapu/WiFiManager#1697]
#### Hardware
WiFimanager Branch/Release:  Master

Esp8266/Esp32: Esp32

Hardware: ESP32-S3

### Description

I was wondering how to enable EAP configuration using this WiFiManager tool. Is it possible? If so, how can I enable this?

**Comment by tablatronix** [comment]
#1512 
#1668 
#364

**Comment by nivedhanatarajan7** [comment]
I looked through the issues you linked. I was wondering how to incorporate the university network connection code from [#309](https://github.com/tzapu/WiFiManager/issues/309) using WiFi Manager. I am quite new to using WiFi Manager and ESP32, which is why it would be great if you could clarify this further.
