### ISSUE TITLE
Feature configurable? WiFi AP started when local WiFi is down

### ISSUE THREAD

**Issue by sany3001** [tzapu/WiFiManager#1725]
As soon as there are no Discussions enabled on this repo, I need to ask question here:

From project description:
* if this is unsuccessful (or no previous network saved) it moves the ESP into Access Point mode and spins up a DNS and WebServer (default ip 192.168.4.1)

I want to avoid in my project on many of my devices just because my WiFi is down that AP gets activated when there are WiFi credentials stored previously.

Can I achieve that be (re)configuring WiFiManager?

**Comment by tablatronix** [comment]
Yeah I do not have privs to make those changes, no problem.

You can use only ondemand, or a reset mechanism, long press etc.
Add a configportaltimeout
Add a user code check for x many minutes or reboots before starting cp.

**Comment by tablatronix** [comment]
```
    // if true (default) then start the config portal from autoConnect if connection failed
    void          setEnableConfigPortal(boolean enable);
```
