### ISSUE TITLE
Dedicated Parameter Page

### ISSUE THREAD

**Issue by ha11otronix** [tzapu/WiFiManager#1728]
I am using
WiFiManager:- v2.0.17
Hardware :- ESP32

I wanted to show bunch of parameter that are hardcoded into system to a special page.
I see that there is a way to show custom parameter but I see that comes under the wifi page. I do not want to configure wifi or save any new SSID or Password so I do not want to have that page at all.

Is there any way so I can show some custom parameters on dedicated page?

**Comment by tablatronix** [comment]
use setmenu(), or    
 // add params to its own menu page and remove from wifi, NOT TO BE COMBINED WITH setMenu!
    void          setParamsPage(bool enable);
