### ISSUE TITLE
Web server connection refused, after configuration via Wi Fi Manager

### ISSUE THREAD

**Issue by DarkBeardRUS** [tzapu/WiFiManager#174]
Hello,
  Sorry for my bad english.
Maybe then he raised the topic.
But I could not find a solution to the problem.

  **If the device configuration via WiFiManager, then I pick up on port 80 another web server. New web server must rise to the new IP, but also on port 80, I get a connection refused.**

**If you restart the device, the Web server will accept connections. or if I'm going to use a port other than 80, then the same web server will accept connections.**

Where can I see the solution to my problem?

**Comment by tzapu** [comment]
hi

check example AutoConnectWithHTTPServer

cheers
