### ISSUE TITLE
Blue LED

### ISSUE THREAD

**Issue by RaptorSDS** [tzapu/WiFiManager#1747]
### Basic Infos
one sketch activate blue LED ,one didnt activate blue led when wifi connect 

#### Hardware
WiFimanager Branch/Release:  latest arduino libary manager

Esp8266: 

Hardware:			ESP01

Core Version:      	2.2.1 +100

### Description
one sketch activate blue LED ,one didnt activate blue led when wifi connect 
same module , same pc , same IDE ,.....

### Settings in IDE

Module:  			Generic ESp8266 arduino Board manager 3.1.2 
https://arduino.esp8266.com/stable/package_esp8266com_index.json

Additional libraries: 

### Sketch without blue led 
#include <ESP8266WiFi.h>
#include <ESP8266WebServer.h>
#include <WiFiManager.h>
#include <ArduinoJson.h>

// WiFiManager
WiFiManager wifiManager;

// WebServer auf Port 80 initialisieren
ESP8266WebServer server(80);

void setup() {
  // Serielle Schnittstelle starten
  Serial.begin(115200); // RX, TX

  // WiFiManager Konfiguration
  if (!wifiManager.autoConnect("ESP8266-Config")) {
    //Serial.println("failed to connect and hit timeout");
    ESP.restart();
  }

  Serial.println("WiFi connected!");

  // Webserver Endpunkte definieren
  server.on("/", handleRoot);
  server.on("/rawdata", handleRawData);
  server.on("/jsondata", handleJsonData);
  server.on("/trigger", HTTP_GET, handleTriggerMeasurement); // Neuer Endpunkt für manuelle Messung

  server.begin();
 // Serial.println("HTTP server started");
}

void loop() {
  server.handleClient();
  
  // Serielle Daten lesen und verarbeiten
  while (Serial.available() >= 7) {
    uint8_t response[7];
    for (int i = 0; i < 7; i++) {
      response[i] = Serial.read();
    }
    
    // Überprüfen, ob die empfangene Nachricht gültig ist
    if (response[0] == 0x01 && response[1] == 0x03 && response[2] == 0x02) {
      uint16_t distance_mm = (response[4] << 8) | response[3]; // Umwandlung von Hex in mm
      height_mm = SENSOR_HOEHE_MM - distance_mm;

      // Sicherheitsprüfungen
      if (height_mm < 0 || height_mm > SENSOR_HOEHE_MM) {
        //Serial.println("Ungültiger Wert empfangen: " + String(height_mm) + "mm");
        return;
      }

      // Begrenze den Wert auf MAX_FUELLSTAND_MM
      if (height_mm > MAX_FUELLSTAND_MM) {
        height_mm = MAX_FUELLSTAND_MM;
      }

      // Speichere den aktuellen Messwert in der Historie
      heightHistory[historyIndex] = height_mm;
      historyIndex = (historyIndex + 1) % 6;

      // Berechne den gleitenden Mittelwert der letzten 6 Messungen
      int sum = 0;
      for (int i = 0; i < 6; i++) {
        sum += heightHistory[i];
      }
      height_mm = sum / 6;
      
      // Sicherheitsprüfung des gleitenden Mittelwerts
      if (height_mm < 0 || height_mm > SENSOR_HOEHE_MM) {
        //Serial.println("Ungültiger gleitender Mittelwert: " + String(height_mm) + "mm");
        return;
      }

      current_liters = calculateVolume(height_mm);

      // Speichere den gleitenden Mittelwert alle 6 Messungen (entspricht 1 Minute)
      if (historyIndex == 0) {
        minuteHistory[minuteIndex] = height_mm;
        minuteIndex = (minuteIndex + 1) % 5;
      }
    }
  }
.........
}

### Sketch with blue led 
#include <ESP8266WiFi.h>
#include <ESP8266WebServer.h>
#include <WiFiManager.h>  // https://github.com/tzapu/WiFiManager
#include <ArduinoJson.h>  // https://arduinojson.org/v6/doc/installation/

// WiFiManager
WiFiManager wifiManager;

// WebServer auf Port 80 initialisieren
ESP8266WebServer server(80);

// Pin-Definitionen für den Ultraschallsensor
const int TRIGGER_PIN = 1; // TX Pin als Trigger
const int ECHO_PIN = 3;    // RX Pin als Echo

void setup() {
  // Serielle Schnittstelle starten
 // Serial.begin(9600);

  // WiFiManager Konfiguration
  wifiManager.autoConnect("ESP8266-Config"); // AP-Name für Konfigurationsportal

  // Webserver Endpunkte definieren
  server.on("/", handleRoot);
  server.on("/rawdata", handleRawData);
  server.on("/jsondata", handleJsonData);
  server.on("/trigger", HTTP_GET, handleTriggerMeasurement); // Neuer Endpunkt für manuelle Messung

  server.begin();

  //Serial.println("HTTP server started");

  // Initiale Pin-Konfiguration für Ultraschallsensor
  pinMode(TRIGGER_PIN, OUTPUT);
  pinMode(ECHO_PIN, INPUT);
digitalWrite(TRIGGER_PIN, LOW);
  // Initiale Messung durchführen
  performSingleMeasurement();
  current_liters = calculateVolume(height_mm); // Erste Messung speichern
}

void loop() {
  server.handleClient();
  digitalWrite(TRIGGER_PIN, LOW);
  
  static unsigned long lastMeasurement = 0;
  if (millis() - lastMeasurement >= 60000) { // 1 Minute = 60000 ms
    lastMeasurement = millis();
    performMultipleMeasurements();
  }
}

void performSingleMeasurement() {
  // Sende Trigger-Puls
  digitalWrite(TRIGGER_PIN, LOW);
  delayMicroseconds(2);
  digitalWrite(TRIGGER_PIN, HIGH);
  delayMicroseconds(20);
  digitalWrite(TRIGGER_PIN, LOW);

  }

v-..........
}

### Debug Messages

```
messages here
i didnt see any reson why this diffirent behavior only serial pin 1 and 3 are diffirent not 16 or anything with wifi

**Comment by tablatronix** [comment]
This is usually defined in board def by LED_BUILTIN, maybe you have the wrong board selected
