### ISSUE TITLE
unable to set access point name

### ISSUE THREAD

**Issue by romuye123** [tzapu/WiFiManager#186]
Following is my code:

```
 WiFiManager wifiManager;
 wifiManager.resetSettings();
 wifiManager.autoConnect("My Chip name");
```
Even if i set access point name it displays "ESP_xxxxxx" in the wifi list.
What is wrong with this ?

**Comment by romuye123** [comment]
@tzapu : waiting for your response

**Comment by ahmadmn** [comment]
after
WiFiManager wifiManager;
Append this code:
WiFi.hostname("YourName");

**Comment by romuye123** [comment]
@ahmadmn: Thanks for your quickly reply.  Tried appending the code, but it still does not work. 
Here is my updated code:
`WiFiManager wifiManager; 
WiFi.hostname("mychipname"); 
wifiManager.resetSettings(); 
wifiManager.autoConnect("testchipname");` 

Here is debug output: 
`0
chksum 0x0f
csum 0x0f
*WM: settings invalidated
*WM: THIS MAY CAUSE AP NOT TO START UP PROPERLY. YOU NEED TO COMMENT IT OUT AFTER ERASING THE DATA.
*WM: 
*WM: AutoConnect
*WM: Two
*WM: Connecting as wifi client...
*WM: Using last saved values, should be faster
*WM: Connection result: 
*WM: 0
*WM: SET AP STA
*WM: Three
*WM: testchipname
*WM: 
*WM: Configuring access point... 
*WM: testchipname
*WM: AP Name Here
*WM: testchipname
*WM: AP IP address: 
*WM: 192.168.4.1
*WM: HTTP server started`

Following is the screenshot on my phone:

![img_9354](https://cloud.githubusercontent.com/assets/1880131/16337020/e93e6030-3a2f-11e6-87eb-48df8340dcba.PNG)

**Comment by tzapu** [comment]
hi,

that is the default username of the esp chip, somehow it is not getting set by wifimanager at all...

can you updated to the latest everything (esp8266 core, wifimanger) and try again? also make sure you are setting the correct flash size for your esp module

cheers

**Comment by ahmadmn** [comment]
It works for me.
I use Arduino 1.6.9 and following libs:
![image](https://cloud.githubusercontent.com/assets/5241132/16350532/744851ba-3a74-11e6-99e1-97fb78f85d42.png)

**Comment by romuye123** [comment]
Works fine after updating to latest
