### ISSUE TITLE
Using Websockets after Autoconnect

### ISSUE THREAD

**Issue by kommancs96** [tzapu/WiFiManager#187]
Hi !
I recently made a working example where I am able to switch a LED using HTTP protocol.
The problem is that sending http requests, waiting for response, than process the response is too much time. I am curious if I am able to use websockets for communication after successfully connecting to WiFi using WiFiManager?

**Comment by ahmadmn** [comment]
Hi
I need Async compatible WiFiManager too.

**Comment by tzapu** [comment]
hi, i am using websockets and wifimanager in a project here, hope it helps
https://github.com/tzapu/WebSocketSerialMonitor/blob/master/WebSocketSerialMonitor.ino

async webserver i have not used yet, but i guess it needs some intialisation/reset/reintialisation after wifimanger is done

cheers

**Comment by ahmadmn** [comment]
Thanks @tzapu
The example works fine.
But I have a basic question!
I want to write a Delphi application to communicate with ESP8266 (WebSocketSerialMonitor.ino included).
I must write a WebSocket server or client?

**Comment by tzapu** [comment]
in my particular app linked above, the esp8266 is a websockets server.
but you could have it be either server or client depending on what you need it to do, look at the websockets lib docs
cheers

**Comment by kommancs96** [comment]
Thanks, @tzapu , helped a lot. ;)

**Comment by ahmadmn** [comment]
Thanks @tzapu,
Your code works perfect with delphi:

![image](https://cloud.githubusercontent.com/assets/5241132/16362578/ba4cb8fa-3bc7-11e6-9a27-41e983952e65.png)
![image](https://cloud.githubusercontent.com/assets/5241132/16362579/c09d8b08-3bc7-11e6-90c0-3d008f38e2ff.png)

**Comment by rooky06** [comment]
hello **ahmadmn**
I downloaded  IPwors activeX trial but theres only demo for VB and ASP.
Can you share your code to i learn( i m newbie)
thank you

**Comment by ahmadmn** [comment]
Hi rooky06

**Comment by rooky06** [comment]
Hello

Thank you for the link.

I downloaded it .

I go to try to use it like the sample code here 
https://developers.binary.com/demos/

thank you
