### ISSUE TITLE
How to get current local IP address?

### ISSUE THREAD

**Issue by roccomuso** [tzapu/WiFiManager#19]
This is what i tried:

      WiFiManager wifi;
    
      wifi.setTimeout(120); // retry after 2 minutes to connect to a wifi.
    
      if(!wifi.autoConnect(apName)) { // timeut reached
        Serial.println("failed to connect and hit timeout");
        delay(3000);
        //reset and try again
        ESP.reset();
        delay(5000);
      } 
    
      // if you get here you have connected to the WiFi
      Serial.println("connected!");
      currentIp = wifi.localIP();

But I've got the following error:

    'class WiFiManager' has no member named 'localIP'

**Comment by tzapu** [comment]
hi,
just do `WiFi.localIP()` . it's a function of the core WiFI, not my lib.
maybe the examples could do with another naming scheme to make things clearer
cheers
