### ISSUE TITLE
What happen if using Wifi Manager in restaurant?

### ISSUE THREAD

**Issue by vukidrock** [tzapu/WiFiManager#194]
Hi there, I love this lib very much, so I have some question:

- Using Wifi Manager lib in restaurant: I have a wifi system before, I use this lib Arduino with ESP8266 like a captive portal to redirect customers to my restaurant website. It will very nice if Wifi manager save my SSID's wifi restaurant and not show other wifi system. 

More specific, when customers turn on wifi on their device, they connect to my restaurant wifi system, they see a website (or Facebook, Twitter... randomly), wait 5 seconds and a button will show to click, after that, they can use wifi system normally.

Anybody think about it? How can I do?

Thank you.

**Comment by probonopd** [comment]
How did you solve this?

**Comment by tzapu** [comment]
hi, isn t it easier just to use a router that has this ability? seems a bit long winded and outside the scope of wifimanager to do this...

**Comment by tablatronix** [comment]
Yeah i would just use openwrt running on a cheapo wall wart router

**Comment by probonopd** [comment]
After re-reading the original question I agree.
