### ISSUE TITLE
EEPROM Storing for SSID/Pass

### ISSUE THREAD

**Issue by LorelaiNerv** [tzapu/WiFiManager#196]
Hello.
Can you please tell me if there is a special start bit for EEPROM write for the network ssid and pass, or is it 0?
I would like to store some more data in EEPROM and i want to leave that SSID/pass area alone (say.. 50 addresses).
Awsome work with this library! Congrats!

**Comment by tzapu** [comment]
hi,

thanks,

you can safely write to eeprom, it is separate from ssid/pwd store

cheers

**Comment by LorelaiNerv** [comment]
Great!
Thank you very much,
Keep up the good work ;)

**Comment by pieman64** [comment]
@LorelaiNerv https://github.com/esp8266/Arduino/blob/master/doc/filesystem.md shows the memory structure for ESP's and as @tzapu states ssid/pwd are in the WiFi area not the EEPROM area. Do you really want to use EEPROM in the traditional way or would it be better for you to add extra parameters to WiFiManager?

**Comment by tzapu** [comment]
@pieman64 thanks

also, there is the additional option of using wifimanager for the parameters, and having it store all in eeprom.

i ve got a sketch somewhere doing that

cheers

**Comment by LorelaiNerv** [comment]
I want to use it absolutely old fashioned way.. made some successful tests on arduino mega and now i want to implement the solution to ESP. If i am successful i will post it heere.
My stored values are absolutely independent of this library, bbut i would not interfere with it's functionality.
I will keep you posted.
Again, thank you very much!

**Comment by pieman64** [comment]
OK I just worry about some users trashing their devices by posting a bad sketch that exceeds the maximum allowable writes to EEPROM, within a few minutes.

**Comment by LorelaiNerv** [comment]
Of course it is a possibility.. but, i have tested the code for some time now.. and looks ok.
My worry was about the address allocation but i saw that it wasn't the case.
Anyway.. average read/writes to eeprom is around 100k if i remember... should take a while.. except for some loop..

**Comment by LorelaiNerv** [comment]
On a second thought.. can you please post the example code for storing parameters to wifi area? .. could be a valid solution due to the above mentioned life expectancy of eeprom....
I have "work in progress" here, and i would give it a try.. can save some heads ;)
thank you,

**Comment by rafaelmaeuer** [comment]
push! Same for me, please post a working example!
