### ISSUE TITLE
DHCP Reservation

### ISSUE THREAD

**Issue by wfraga18** [tzapu/WiFiManager#199]
Hi Tzapu,

congrats by the lib

I getting problems when i try set a specific IP for my esp8266 !
ex: 
if i set my router to give a 192.168.0.190 to my ESP,  the device hang, i believe stay in loop

have a setting or trick ?
because i don't want to set IP in thing, only in my router

thank you in advance

**Comment by wfraga18** [comment]
nobody tried ??

**Comment by tzapu** [comment]
hi, 
 i have dhcp reservations based on mac address, seems to work fine, module always comes back with same ip

cheers
