### ISSUE TITLE
Two network DHCP

### ISSUE THREAD

**Issue by josep112** [tzapu/WiFiManager#203]
Hello!
I have a network with two dhcp tracks:
192.168.0.0 and 192.168.70.0, as do the mananger to connect by dhcp the 192.168.70.0 network?
thanks

**Comment by kentaylor** [comment]
This question seems erroneous but if you really have two DHCP servers on the one network segment then the ESP8266 device will use whichever DHCP server responds first to it's DHCP request as explained at http://serverfault.com/questions/368512/can-i-have-multiple-dhcp-servers-on-one-network
