### ISSUE TITLE
Captive portal: cannot paste in the fields

### ISSUE THREAD

**Issue by darrepac** [tzapu/WiFiManager#204]
Hi

I will setup the connection from my iPhone. Additionnaly I have to set-up a long parameter in the captive portal.
So I plan to copy this parameter from elsewhere and paste it in the captive portal (could be also used for SSID or password). Yet, I can't paste in any field of the captive portal form. I guess there is a setting in the captive portal html code to avoid that??
Thanks for any hint

**Comment by tzapu** [comment]
Hi,

Not that i am aware. It does happen to me, but i remember it happening on third party access points as well. It  most likely a iOS limitation.

Do let me know if there is anything i could do to circumvent it

Cheers
