### ISSUE TITLE
Web server does not restart in on demand mode

### ISSUE THREAD

**Issue by normads** [tzapu/WiFiManager#205]
After starting and leaving the captive portal once, triggering the captive portal again starts the softAP, but the web server is not started. Only works after a reboot

**Comment by tzapu** [comment]
hi, this is an issue in the esp8266 webserver cleanup somewhere unfortunately together with a bug in wifimanager that doesn t start the portal if it s already connected to the network.

don t have a test bed for this currently, but will have to check it out whenever i get some time to rework the way it does things.

in the mean time, you could jsut force a reset after captive portal ends, if that ok.

**Comment by normads** [comment]
Yup that should be ok for now. Thanks!
