### ISSUE TITLE
Where/how are fields stored?

### ISSUE THREAD

**Issue by Daemach** [tzapu/WiFiManager#213]
Where is the SSID and password stored?  How about custom fields like the blynk token?

**Comment by tzapu** [comment]
hi

ssid and pwd are stored by the expressif sdk in the flash.

the other stuff, that you used a parameter for, you are responsible for saving, so it could be eeprom or fs, depending on how you want to do it

cheers

**Comment by piux** [comment]
@tzapu  how can i change or read this values without being in access point mode?

**Comment by tzapu** [comment]
hi

i believe you are looking for 
WiFi.SSID()
and
WiFi.psk()

Cheers
