### ISSUE TITLE
Custom SSID for Captive Portal in WiFi selection

### ISSUE THREAD

**Issue by kfeger** [tzapu/WiFiManager#217]
Greetings!
First of all: Great, great work!!!!
One question: How can I asign a custom ssid for the captive Portal that's set up when doing an autoconnect as you show it e.g. in AutoconnectWithFeedback.ino (for display reasons I need the callback feature)?
What I try to get is an ssid that is not the default "ESP[chipID]" but rather "MyConfigWiFi" or the like.
Thanks and greetings from Dresden, Germany!
Karl

**Comment by tzapu** [comment]
hi,

just send the SSID as the first parameter to autoConnect

thanks und danke

**Comment by kfeger** [comment]
Thanks!

I misinterpreted the time, the debug output was generated. That was to easy…

Thanks again!!

Karl

 

Von: tzapu [mailto:notifications@github.com] 
Gesendet: Samstag, 20. August 2016 06:54
An: tzapu/WiFiManager
Cc: Karl O. Feger; Author
Betreff: Re: [tzapu/WiFiManager] Custom SSID for Captive Portal in WiFi selection (#217)

 

hi,

just send the SSID as the first parameter to autoConnect

thanks und danke

**Comment by skx** [comment]
@kfeger - Perhaps time to close this issue?

**Comment by kfeger** [comment]
You’re definitly right. I’ll do it right away.

BTW: Works like a charme!!!

Karl

 

Von: Steve Kemp [mailto:notifications@github.com] 
Gesendet: Mittwoch, 1. Februar 2017 21:20
An: tzapu/WiFiManager
Cc: Karl O. Feger; Mention
Betreff: Re: [tzapu/WiFiManager] Custom SSID for Captive Portal in WiFi selection (#217)

 

@kfeger <https://github.com/kfeger>  - Perhaps time to close this issue?
