### ISSUE TITLE
Configuration by app

### ISSUE THREAD

**Issue by lunanigra** [tzapu/WiFiManager#218]
Hello, your WiFiManage is quite cool :-)

But the configuration via Browser is not really comfortable. The user has to know several things (connect to ESP8266, open browser with right URL and so on). Then the ESP8266 is often quite slow...

A colleague has implemented a similar (but slightly different) approach. An Ionic app (can be native as well) connects to the ESP8266 if not already configured. This approach reduces the communication and allows developing a complex (or more comfortable) UI.

Is this something that sounds interesting? If so I can send you a copy of our Ionic app... Then you can check how to merge with your solution.

**Comment by Alkia** [comment]
Looks a great idea.

Kind regards,

**Comment by tzapu** [comment]
HI,

thanks, it is a great idea, unfortunately it can t sort out some of the biggest issues with the whole process. (or at least i don t know how). You would still need to connect to the esp manually. On most devices(or the ones i have tested), after that step, the configuration portal opens automatically, so you shouldn t need to know IPs anymore. DNS redirection should also work to direct any address in your browser to the proper IP.

In my case, i am using an iphone to configure my devices, i connect to the ESP network, captive portal pops up, enter details, save and that s it... and the only annoying step is that i have to connect to the wifi network, but that s unavoidable currently. 

Now, if any of the smart config options or the WPS would be reliable and work, it would be quite a different thing altogether, but, again, in my experience, they are quite hit and miss...

I would love to see the app, maybe there s some scope to link the two together, make WiFiManger also work with an app 

thanks again

**Comment by lunanigra** [comment]
Hi, can you give me an email address? I will send you our sample code.

Beside a faster UI the solution via app will not require manually changing WiFi setting. Similar to Google Cast the app will scan for ESPxxxx networks. If available a setup screen will be provided. Only WiFi settings will be transferred; no HTML or other UI elements. This will speed up configuration and also safe resources on ESP.

Would be great if we can link both approaches together :-)

Thanks, JC

**Comment by tzapu** [comment]
HI,

On iOS at least, you can t send the settings without connecting to the actual wifi. You also can t force a connection and I am not sure even if you can scan for wifi networks, last i checked there were no public apis for the WIFi connection management in iOS.

Google cast employs a number of other technologies that are most likely not available on the ESP, and even those don t work reliably for me at all times. WifiDirect, Multipeer, quite possibly even bluetooth.

You can use: alex@tzapu.com

Cheers
Alex

**Comment by tzapu** [comment]
Forgot, i think chromecast is even putting out or listening for an out of audible range audio signal through the tv and links to the phone through that to send settings, etc.

**Comment by lunanigra** [comment]
hmmm...

<alex@tzapu.com>
    (reason: 552-5.7.0 This message was blocked because its content presents a potential)

**Comment by tzapu** [comment]
seems it doesn t like your attachment ..

**Comment by lunanigra** [comment]
Seems so... But it's just a ZIP ;-)

**Comment by umranium** [comment]
Hi,

We have an Android app already. We're currently testing it and fixing some minor issues. If you'd like to test it out, please take a look: [ESP Connect on Google Play](https://play.google.com/store/apps/details?id=au.com.umranium.espconnect)

**Comment by tzapu** [comment]
oh man, that s so cool.
i would like to make a batter API for this, so anyone can have/build or use an app and also have a showcase/apps section on the main github page.
is there anything in particular you d like supported in the api? Would you be ok on being featured?
i love it when things develop further :)

**Comment by Alkia** [comment]
Looks great,

Looking forward helping for test.

It would be great if the ionic app could natively requests for 2 optional
feilds:
- an email address
- a Pin code

Kind regards,

Maxime

On Aug 29, 2016 1:40 PM, "tzapu" <notifications@github.com> wrote:

oh man, that s so cool.
i would like to make a batter API for this, so anyone can have/build or use
an app and also have a showcase/apps section on the main github page.
is there anything in particular you d like supported in the api? Would you
be ok on being featured?
i love it when things develop further :)

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tzapu/WiFiManager/issues/218#issuecomment-243043747>,
or mute the thread

**Comment by umranium** [comment]
@tzapu We added some APIs and some fixes to the code to get it to work smoothly with apps. For example, supporting a more machine-centric data format (we went with JSON). You can find the additions (and fixes) in this repository: [Ken Taylor's WiFiManager repo](https://github.com/kentaylor/WiFiManager)

**Comment by umranium** [comment]
@tzapu Forgot to answer one of your questions. Yes, we would **love** to be featured! :)

**Comment by lunanigra** [comment]
Sounds cool!! Curious about testing the next release :-)

----- Nachricht beantworten -----
Von: "Umran Abdulla" <notifications@github.com>
An: "tzapu/WiFiManager" <WiFiManager@noreply.github.com>
Cc: "JC" <haddorp@lunanigra.de>, "Author" <author@noreply.github.com>
Betreff: [tzapu/WiFiManager] Configuration by app (#218)
Datum: Mo., Aug. 29, 2016 23:37

@tzapu Forgot to answer one of your questions. Yes, we would love to be featured! :)

&mdash;You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.










{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tzapu/WiFiManager","title":"tzapu/WiFiManager","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tzapu/WiFiManager"}},"updates":{"snippets":[{"icon":"PERSON","message":"@umranium in #218: @tzapu Forgot to answer one of your questions. Yes, we would **love** to be featured! :)"}],"action":{"name":"View Issue","url":"https://github.com/tzapu/WiFiManager/issues/218#issuecomment-243264798"}}}

**Comment by pieman64** [comment]
@umranium can we have a Blynk token field?

**Comment by tzapu** [comment]
i think ideally i would expose some api endpoint, and all apps should fetch all configured fields in the sketch and allow configuration

cheers

**Comment by umranium** [comment]
@pieman64 We might look into that in the future. Currently our scope is limited to getting the user's device connected to the WiFi (and therefore the internet) as painlessly and as effortlessly as possible.

**Comment by umranium** [comment]
@lunanigra I should have an update out by early next week.

**Comment by TechieIndianGuy** [comment]
@umranium Has the update released?

**Comment by umranium** [comment]
@TechieIndianGuy I just updated the alpha testing version. Here's the link to opt into the alpha testing:

[ESP Connect Alpha Testing Opt In Link](https://play.google.com/apps/testing/au.com.umranium.espconnect)

I'm keen to get any feedback.

**Comment by Melcos1970** [comment]
I have made a small change to WiFiManager.cpp and .h to get a mid-term solution to the problem with WPS.
It's not the best way, but now you can use WPS if you are going to ..
I have no idea how to add suggestions to github, but I want to post them here so can add them if you want to use them.
The solution is actually simple .. I just add a button extra that makes a WPS call.

Changed:
Const char HTTP_PORTAL_OPTIONS [] PROGMEM = "<form action = \" / wifi \ "method = \" get \ "> <button> Configure WiFi </ button> </ form> <br/> <form action = \" / 0wifi \ "method = \" get \ "> <button> Configure WiFi (No Scan) </ button> </ form> <br/> <form action = \" / i \ "method = \" get \ "> <Button> Info </ button> </ form> <br/> <form action = \ "/ r \" method = \ "post \"> <button> Reset </ button> </ form> <br/> <Form action = \ "/ w \" method = \ "post \"> <button> WPS Setup </ button> </ form> ";

Inserted: lines +++
    Void handleReset ();
+++ void handleWPS ();
    Void handleNotFound ();

  Server-> on ("/ r", std :: bind (& WiFiManager :: handleReset, this));
+++ server-> on ("/ w", std :: bind (& WiFiManager :: handleWPS, this));
  // server-> on ("/ generate_204", std :: bind (& WiFiManager :: handle204, this)); // Android / Chrome OS captive portal check.
  Server-> on ("/ fwlink", std :: bind (& WiFiManager: handleRoot, this)); // Microsoft captive portal. Maybe not needed. Might be handled by notFound trades.


Inserted section / ++ ++ / after void WiFiManager :: handleReset () section
/ ++
Void WiFiManager :: handleWPS () {
  DEBUG_WM (F ("WPS Start"));

  String page = FPSTR (HTTP_HEAD);
  Page.replace ("{v}", "Info");
  Page + = FPSTR (HTTP_SCRIPT);
  Page + = FPSTR (HTTP_STYLE);
  Page + = _customHeadElement;
  Page + = FPSTR (HTTP_HEAD_END);
  Page + = F ("Module will start WPS in a few seconds.");
  Page + = FPSTR (HTTP_END);
  Server-> send (200, "text / html", page);

  DEBUG_WM (F ("Sent WPS page"));
  // WPS works only in STA (Station mode) only.
  WiFi.mode (WIFI_STA);
  delay (1000);
  startWPS ();

[WiFiManager_WPS_Files.zip](https://github.com/tzapu/WiFiManager/files/983659/WiFiManager_WPS_Files.zip)



  delay (5000);
  ESP.reset ();
  delay (2000);
}
++ /

**Comment by FernandoGarcia** [comment]
Hi!

@umranium why your App doesn't connect to ESP when there a SSID and Password configured here?

`if (!wifiManager.startConfigPortal("ESP8266","password"))`

It's always saying "connecting to ESP....."

But it works in this way:

`if (!wifiManager.startConfigPortal())`

I would like to post this issue to your repo but it's not available.

Best regards.

**Comment by erdemontas** [comment]
I have working device and I'm using wifimanager library properly. I also have an android app, I want to implement"configuration by app" rather than having @umranium 's app. What kind of changes should I do?

**Comment by pieman64** [comment]
@erdemontas you might want to look up **Blynk provisioning** but it's difficult to tell what you want to do from your post.

**Comment by erdemontas** [comment]
@pieman64 let me try to put it this way; what I want to do to connect my esp to internet via my app not using web portal. 
First idea which came to my mind is, to be successful on this task, I have to deliver the credentials to my esp and save them in ESP. I figured out how to save them but where I'm stucked is how should I deliver them from Android app to Esp(I guess it has to be in AP mode)

**Comment by kapiloberoi** [comment]
I have been able to put together an app that autodetects the esp8266 and let you select your wifi network settings to be saved into the esp. The only think now remains is to set a hostname so that ince config is over we can access it by name instead for looking for the ip address.

Used appinventor2 and credit goes to Taifun for excellent wifi extension. "Kapiloberoi@gmail" and ill send the code along with apk. Will also post the code and app here in a day !! Be warned that im a terrible coder:))

Cheers -

**Comment by gopchi** [comment]
Guys, I am not able to get the app to find my ESP... What am I doing wrong? Installed the WiFi Manager library then used the AutoConnect example. The ESP creates an AP but when I scan with the app @umranium provided says Unable to find any ESP8266 nodes. 

@FernandoGarcia  How did you set up your ESP?

Would appreciate some help, because I really want to try and configure my esp's through the mobile app. :)

**Comment by anshulfd** [comment]
@tzapu Are there any plans to add the features from https://github.com/kentaylor/WiFiManager to this repo?

**Comment by tablatronix** [comment]
Features yes, merge no.

**Comment by BuzzHari** [comment]
Is an open source app for configuring esp8266 available yet?

**Comment by DeveloperChand** [comment]
@gopchi 
facing same issue. any solution available

**Comment by laurensV** [comment]
Would also like to know if an open source version of an app is available (auto detect esp etc.)
