### ISSUE TITLE
setAPConfig not existing in the API

### ISSUE THREAD

**Issue by pit001** [tzapu/WiFiManager#225]
HI, the call to setAPConfig in the line
wifiManager.setAPConfig(IPAddress(10,0,1,1), IPAddress(10,0,1,1), IPAddress(255,255,255,0)); in a example sketch is not existing in the API (.h / .c / .ino) nor in the github repo. 

AutoConnect:20: error: 'class WiFiManager' has no member named 'setAPConfig'

```
 wifiManager.setAPConfig(IPAddress(10,0,1,1), IPAddress(10,0,1,1), IPAddress(255,255,255,0));

             ^
```

**Comment by tablatronix** [comment]
which example ?
