### ISSUE TITLE
Improve the UI

### ISSUE THREAD

**Issue by akshitgandhi** [tzapu/WiFiManager#226]
Hey! Nice job with the library. I wanted to add more style elements on the configuration page, but being new to this I cannot figure how to add more css and JavaScript. I wondered if I could use the template in the extras folder and use the snippets into the script. Please tell me how can I add custom css and JavaScript. I refered the documentation but couldnot understand , please help me!

**Comment by tzapu** [comment]
hi,

if you can hold a few more days, i was just working on a nodejs app that exports consts from the the template, so anyone can make it look however they like easier.

just need to make sure it s outputing the proper stuff, then i ll include it

cheers

**Comment by akshitgandhi** [comment]
Thanks!
Approximately how much time will it take? Can you share the developmental version so that even I can help you up in bug fixes?

**Comment by tzapu** [comment]
hi,

just committed it. check the extras folder, you just run it with node parse (need to have nodejs installed of course)

the next step was to check of the exported consts are valid, reintegrate whatever changes have been made to the consts in the library into the template, exporting, seeing if they are equivalent and then finally modifying wifimanger to use them.

cheers

**Comment by akshitgandhi** [comment]
thank you keep up the good work!
