### ISSUE TITLE
Found a workround- so not really an issue- but might be a clue!

### ISSUE THREAD

**Issue by ed-french** [tzapu/WiFiManager#246]
Hi, thanks for the project. It has helped me throw together a useful thing in next to no time.
I was struggling with the ESP8266-12E reconnecting after reset. It remembered the credentials and tried to reconnect OK.
At work, and on my mobile hotspot this always worked OK.
At home, it absolutely never worked. I'd get a status of 4 then it would flip back to being an access point.
I would configure it, and it would be OK. However, next reset it would do the same again.
Browsing through my router settings I saw it had a facility for IPv6 that I'd never adjusted or looked-at.
This had two subsettings- Basic Config- Connection Type- which was disabled.
However, "Enable Router Advertisement" was set to Enabled.
Disabling this fixed the issue for me!

I don't know if that's useful!

Thanks again,

Ed

**Comment by kentaylor** [comment]
Not something I've seen before. 4 corresponds to [WL_CONNECT_FAILED](https://github.com/esp8266/Arduino/blob/4897e0006b5b0123a2fa31f67b14a3fff65ce561/libraries/ESP8266WiFi/src/include/wl_definitions.h#L56). 

My guess it the router provided an IPV6 and IPV4 access point with the same SSID, the ESP was trying to connent to the IPV6 one and failing.
