### ISSUE TITLE
how to disable station mode during normal operation?

### ISSUE THREAD

**Issue by miknuc** [tzapu/WiFiManager#254]
Hi,
after having some reliabilty issues with my wifi network, I learned that per default each of my ESP opens an additional wifi station on the same wifi channel it is connected as a client.
This can be switched off by changing the wifi mode:
 WiFi.mode(WIFI_STA);

I was looking for something similar when using WifiManager, something like 
WifiManager.autoConnect(PortalName, PortalPWD)
but didn't find anything. 

Would setting
 WiFi.mode(WIFI_STA); 
before calling WifiManager.autoConnect() help?

Regards
Michael

**Comment by kentaylor** [comment]
@miknuc, when you say
> Would setting WiFi.mode(WIFI_STA); before calling WifiManager.autoConnect() help?

it doesn't make a lot of sense to me. WIFI_STA means connect to a WiFi network and usually you want WiFiManager to enable you to connect to a WiFi network, rather than after you are connected.
