### ISSUE TITLE
json is parsed perfectly but problem with strcpy

### ISSUE THREAD

**Issue by mushfiq-cse05-buet** [tzapu/WiFiManager#259]
i have stored my custom parameter to cofig.json successfully but whenever i reboot the esp it can successfully parse the json and printing the values of various keys on Serial monitor then after that when esp try to execute strcpy to retrieve the stored value from json to any variable ,my ESP starts malfunctioning 
showing the following things on Serial Monitor
exception (28):
epc1=0x402117b2 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: cont 
sp: 3fff0dc0 end: 3fff10e0 offset: 01a0

>>>stack>>>
3fff0f60:  3fff2b9c 3fff2c38 3ffefff8 402073d9  
3fff0f70:  3ffe99d8 00000000 000003e8 feefeffe  
3fff0f80:  3fff1e64 3fff19ac feefeffe feefeffe  
3fff0f90:  feefeffe feefeffe feefeffe feefeffe  
3
Exception (4):
epc1=0x400005cb epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000  

is there anybody who can help me out regarding the issue

**Comment by eketjall** [comment]
I 've had similar problems with retirering json data.
try something like: 
const char* data  = root["data"];
and then perform the strcpy on the data variable instead of root["data"] directly if you don't already do it.
