### ISSUE TITLE
Duplicate Wifi networks

### ISSUE THREAD

**Issue by lunanigra** [tzapu/WiFiManager#26]
Hello, when scanning in our company all Wifi networks are listed 2-3 times.

I didn't had the chance for further investigation; but I assume following reason... We have several access points providing the same Wifi network. Means we can use network XYZ inside the whole building on all floors. So, assumption is that a Wifi network is getting listed multiple times if multiple access points are in range.

Is there a chance putting all items with the same name together?

Thanks, JC

**Comment by tablatronix** [comment]
:+1: 
I had this on one of my other issues and it was closed, I forgot to pull it out into its own issues.

This becomes a bit more complicated quickly as there could be some secure some open, different signal levels so you gotta max the best one for display, maybe also show the count (n) so you know it is a institutional AP.

**Comment by tzapu** [comment]
it would be easier to do in js... maybe it s worth considering, as then you would only have to pass the array to js, and a progmem string containing the actual js...

what i m mostly worried about is uncontrolable growth and memory usage with this, which is not justified in my mind as you are really only using the lib once in a blue moon to make your life easier, but decreases resources on your ESP at all times...

**Comment by tzapu** [comment]
i am close this, don t think there s a big need for it really
if anyone strongly feels different, reopen for another discussion

**Comment by tablatronix** [comment]
Im gonna pr it regardless

**Comment by tzapu** [comment]
:))
thank you, i ll reopen then

**Comment by tzapu** [comment]
@tablatronix Shawn, i just have a thought. 
If you are considering going down the javascript route for this, which it would be a lot easier, there a new function i added to add custom <head> elements. ( `setCustomHeadElement("<script> function doSomething() {}</script>")
it could be then offered as a custom head/script snippet that anyone can add, and whoever is not interested can choose to skip it.
there could be a whole range of customisations offered like this for maximum flexibility

**Comment by tablatronix** [comment]
I was gonna just do another n2 loop and remove them but only if there are duplicates detected, but I noticed you changed your sort loop to std::sort comparison

Is it any faster ?

I guess a map might work, I barely know C though and had a hard time trying to modify references in a lambda. shrug.

I was also going to use the sort loop to check if there was any dups before bothering another loop. 
Or do them both in one loop, but it wound up being easier to not combine the two in case the sort algorithm needed to change for memory vs speed on different platforms. I imagine n2 loop is pretty fast even at 16mhz...

Ill look at the JS solution again since you added that callout.

**Comment by tzapu** [comment]
welcome to the club, i barely know c as well :)
the std::sort came from a discussion on how to best do it. i doubt very much that at the amount of n s we have, it will make any difference. it was more of a try and see if you can do it kind of thing :d
any way of doing it would probably not have much impact, it might make sense to pull the networks in an array before any looping first, that might make it faster...

js would be interesting, maybe with a count as well, but that would probably waste the most memory as well...

**Comment by tablatronix** [comment]
yeah i looked at a hash table and it was not worth even looking at for memory, the extra microsecond for a n2 loop was better, for eg i have 22 duplicate network at this one location, more elsewhere.

**Comment by tablatronix** [comment]
Well it looks like std::sort uses quicksort and is around 30% faster in my real world test.

**Comment by tablatronix** [comment]
Before
![image](https://cloud.githubusercontent.com/assets/807787/13652583/8f12a010-e612-11e5-8f78-0dd9cd1e1b8c.png)
After
![image](https://cloud.githubusercontent.com/assets/807787/13652591/98a41230-e612-11e5-903e-631f0931c77f.png)

**Comment by tablatronix** [comment]
I added `_removeDupAps` global in case you want to expose it or toggle it.

**Comment by lunanigra** [comment]
Cool :-)

**Comment by tzapu** [comment]
that s perfect, will pull it in a bit later and add the toggle for it

boy you ve got lots of networks :))
