### ISSUE TITLE
what is the Maximum String Length of any custom Parameter 

### ISSUE THREAD

**Issue by mushfiq-cse05-buet** [tzapu/WiFiManager#260]
could anybody tell me what is the maximum String Length of a custom parameter can be coz in my device i have to enter a long URL  which is more than 100 character long

**Comment by cosmocracy** [comment]
From my quick analysis of the code, it looks like parameters can be any arbitrary length.  Most of the constructors for WiFiManagerParameter take a "length" parameter that specifies the maximum.  See [WiFiManager.h](https://github.com/tzapu/WiFiManager/blob/master/WiFiManager.h)
