### ISSUE TITLE
Persosting AutoConnect Configuration

### ISSUE THREAD

**Issue by JohnAntonusMaximus** [tzapu/WiFiManager#261]
Just a quick question as I haven't tried this yet, but if you connect to your WiFi in Access Point mode and then upload a different sketch to the the ESP8266, is the saved WiFi configuration for autoconnect() persisted from memory? Or will it need to be reconfigured in access point mode?

**Comment by tzapu** [comment]
hi,

it should be saved until you issue a WiFi.disconnect() no motter how many sketches you write to it

good luck
