### ISSUE TITLE
Is there an easy way to change wifi channels?

### ISSUE THREAD

**Issue by gregsvo** [tzapu/WiFiManager#264]
I've got a project I'm working on at my office, but there are many, many wireless devices in the building. The problem (to my knowledge) is that **the ESP8266 defaults to channel 1**, which is heavily used in this office- and is causing connectivity issues. **I would like to change the ESP8266's channel to something else.** Is there a way in the configuration in WifiManager to do so?

**Thank you!** I'm very new at Arduino/ESP8266, so I appreciate your patience.

**Comment by mushfiq-cse05-buet** [comment]
u can use the WiFi functions of arduino core see the documentation Thanks

**Comment by gregsvo** [comment]
I was hoping for a more informational answer than that. I've already seen the documentation, but wifi manager didn't seem to be respecting my changes.

**Comment by ggriesse** [comment]
Also looking for a why to change this ..

**Comment by girisan** [comment]
> Also looking for a why to change this ..

I can give a 'why' for an option to specify channel...
In my case, when the device goes into config mode, the SSID is not visible in the scanned list, Resetting the device repeatedly didnt help. The probable cause was, that the channel probably clashed with many other hotspots in the neighborhood. A simple work around is to let the device specify the channel, which it can randomize each time it gets into the config mode.
At present, in such cases, WiFiManager will be entirely ineffective.

**Comment by tablatronix** [comment]
#936
