### ISSUE TITLE
Rename setTimeout(...) to be more clear in intent

### ISSUE THREAD

**Issue by cosmocracy** [tzapu/WiFiManager#270]
The concept of "timeout"--without further context in the name--is vague and confusing to consumers of the WifiManager framework.  (Timeout of the AP? Timeout waiting for autoconnect? etc.)  I suggest you rename this to be clearer and indicate the units of measure.  As it stands--and as I understand it--the current method might better be named ```setConfigPortalTimeoutSec(...)```.  I feel this would alleviate confusion and frustration.

**Comment by tzapu** [comment]
hi, it was renamed long ago, mentioned in the readme. only left the setTimeout function as well to not break older sketches.

https://github.com/tzapu/WiFiManager#configuration-portal-timeout

thanks
