### ISSUE TITLE
Debug Messages using Serial or Arduino Debug?

### ISSUE THREAD

**Issue by tzapu** [tzapu/WiFiManager#273]
What do you guys think?

**Comment by tzapu** [comment]
Leave debug messages as they currently are?

**Comment by tzapu** [comment]
Move debug messages to Arduino IDE debug 
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md#example-for-own-debug-messages

**Comment by tablatronix** [comment]
Link is broken what exactly was the implementation?
