### ISSUE TITLE
WiFiClientSecure with WiFiManager - can it work?

### ISSUE THREAD

**Issue by JonSilver** [tzapu/WiFiManager#288]
I've tried all day with this, but ultimately although WiFiManager is connecting, the WiFiClientSecure client.connected() is showing 0.

Is there a prescribed way of making the two work together? Is this even possible? I need my ESP8266s talking MQTTS (MQTT over TLS). If not, I'll just write my own captive configuration portal.

**Comment by koloboid** [comment]
Try to connect other host with TLS. In my attempts, WiFiClientSecure can not connect *any* TLS service, only few configurations of TLS server will work (api.github.com:443, for example, should connect and handshake well).
