### ISSUE TITLE
How to check if there are saved wifi credentials

### ISSUE THREAD

**Issue by gonsays** [tzapu/WiFiManager#293]
Is there any simple way, on WiFiManager, to check whether there are wifi credentials saved or not?

I have an ESP8266 connected to a button. If I press the button upon esp's startup it will do: wifiManager.resetSettings() and wifiManager.autoConnect("AutoConnectAp").

Besides the button, I would like to have another option: if there are no previously saved settings it would launch the autoConnect function. To do so, I would use an IF LOOP to check that there are no saved settings and launch the WiFiManager AP mode for configuration.

Thank you very much in advance!

**Comment by skx** [comment]
The following will output the saved values, if any:

     Serial.println( WiFi.SSID() );
     Serial.println( WiFi.psk() );

You can test if they are null/empty as you wish :)
