### ISSUE TITLE
Setting DNS server in static ip address mode

### ISSUE THREAD

**Issue by ElApe** [tzapu/WiFiManager#295]
When setting static IP address I cant set the DNS server addresses, they do get set under dhcp.

Could you provide a method such as setDNS to allow this please?

Regards

Nick

**Comment by sktaylortrash** [comment]
Did you ever find a solution to this? I also need to be able to specify a DNS server when using a static IP

**Comment by ElApe** [comment]
Sorry no :/ 
TBH I've all but given up with the library now. Just doesn't seem to work properly anymore and I cant get it running on ESP32 
Regards
