### ISSUE TITLE
Missing id/name

### ISSUE THREAD

**Issue by kolesar007** [tzapu/WiFiManager#301]
I try your Wifi manager and works great. I had just one issue with missing id/name under input fields on configuration page. Altrough I have set it WiFiManagerParameter .

WiFiManagerParameter p_boardName("boardName", "boardName", config.boardName, x);

![wifimanager_issue](https://cloud.githubusercontent.com/assets/17949018/22412161/a95727bc-e6ab-11e6-83d2-c2a7e7dbe398.png)

**Comment by xlinbsd** [comment]
Hello,
Did you add the parameter after your declaration ?
 `wifiManager.addParameter(&p_boardName);`
