### ISSUE TITLE
Is this behavior possible?

### ISSUE THREAD

**Issue by MarcFinns** [tzapu/WiFiManager#306]
Hi, reading the docs I am not sure whether the following behaviour is possible at all. It seems a new use-case unless I misunderstood.
I would like to use this lib in a measurement device that has both an LCD display and MQTT logging capabilities. In the assumption that a valid set of credentials/parameters is already stored, I would like my device to:
1) Try to connect to wifi (without blocking for too long)
2) If wifi is present, cycle normally, updating display AND mqtt
3) If wifi is not available, cycle updating the display but skip mqtt
4) Retry the wifi connection from time to time, possibly at a configurable interval
5) Invoke the configuration portal only programmatically / from touch screen UI
In the examples I see the autoconnect and the programmatic portal but I don't understand if the periodic connect attempt is feasible.
Thanks a lot for your time and apologies should the answer be an obvious one... but it is not to me!

**Comment by tablatronix** [comment]
Someone wrote a non blocking PR, check the pullrequests, instead of entering a blocking portal loop it uses a loop handler.
