### ISSUE TITLE
Current parameters as default?

### ISSUE THREAD

**Issue by MarcFinns** [tzapu/WiFiManager#307]
Hello again,
In my implementation I have a number of custom parameters (e.g. mqtt server etc).
When moving the device to a different network, the config page forces to re-enter all of them and not only the new SSID/password.
Is there a way to prompt the user with the config page with the current parameter set already populated?
thanks!

**Comment by tzapu** [comment]
hi,

using the code in the examples i provided that should not be the case.

i m currently playing with a 9 custom param sketch and the only thing i need to reenter are the ssid and pass.

cheers

**Comment by MarcFinns** [comment]
Do you mean that the HTML page shows the current values as default? Or that if you submit them blank the old ones are retained?
Thanks.

**Comment by tzapu** [comment]
that the exemples are loading the current values as defaults for the web portal, so the webportal should show the current saved values in the interface

**Comment by MarcFinns** [comment]
Ok then, will check again. Thanks!
