### ISSUE TITLE
configPortalTimeout improvements

### ISSUE THREAD

**Issue by tablatronix** [tzapu/WiFiManager#308]
only timeout configportal if ap has no client

**Comment by tablatronix** [comment]
pr 
https://github.com/tzapu/WiFiManager/pull/310

**Comment by tablatronix** [comment]
My fix was simple and to keep configportal open if a client was connected to AP.

This avoids dealing with last request timestamp bumping and all the problems that creates and fails to solve for.

**Comment by tzapu** [comment]
in my mind, the timeout should be paused or reset if there is a client connected to the ap or maybe just increase the timeout interval with 30 seconds (for example) each time the loop happens, it has not timed out yet and there is someone connected... this should give in effect a timeout that will happen 30 seconds + whatever was left of the timeout after the client disconnected...

a bit hacky maybe, but not bloated i think

**Comment by tablatronix** [comment]
So just add a static global timeoutbuffer variable and add it to the timeout calculations ?

**Comment by tablatronix** [comment]
hows this?

```
boolean WiFiManager::configPortalHasTimeout(){
    if(_configPortalTimeout == 0 || wifi_softap_get_station_num() > 0){
      _configPortalStart = millis(); // kludge, bump configportal start time to skew timeouts
      return false;
    }
    return (millis() > _configPortalStart + _configPortalTimeout);
}
```

**Comment by tzapu** [comment]
that looks brilliant to me, thank you very much

**Comment by tablatronix** [comment]
pushed to PR

**Comment by tablatronix** [comment]
In the future maybe implement a keep alive headers or a microajax keepalive

**Comment by tablatronix** [comment]
It looks there might be a problem with this solution.

Depending on how the client disconnects, wifi_softap_get_station_num continues to report client connected.

**Comment by tablatronix** [comment]
This seems to be caused as with a ton of other problems, by bad sta connect while trying to run softap, it seems it causes issues with dhcp as well.

I was able to stabilize this a bit by `WiFi.disconnect(true);` before enabling softap if not connected.
setting `mode(WIFI_AP)` was not enough.

**Comment by FernandoGarcia** [comment]
Hi @tablatronix @tzapu!

After this update the portal never goes to timeout even without any client.

Best regards.

**Comment by FernandoGarcia** [comment]
I'm sorry was my mistake I don't know the reason but I changed the timeout from seconds to milliseconds. :D

**Comment by tablatronix** [comment]
added webclient checking to bump timeouts, good enough until I decide to add js and ajax keepalives.

1c4011bfb4debe15952239fa6861b4e04cebba4f
