### ISSUE TITLE
softap left on

### ISSUE THREAD

**Issue by tablatronix** [tzapu/WiFiManager#312]
#216 
#267 

probably more

When configportal is abandoned, ap mode is left persistent,

**Comment by tzapu** [comment]
for now it's probably worth just going to WIFI_AP and then back to WIFI_STA rather than AP+STA it goes to now.

it was a half assed attempt to do something else i think

**Comment by tablatronix** [comment]
Easiest fix is to make sure to turn off AP when timeout of configportal, or else it gets stuck on every time.
Also worth noting that switching modes alot may cause flash wear.

**Comment by tablatronix** [comment]
man github is being slow today, could not even see or merge updates.

pr on its way

**Comment by tablatronix** [comment]
best solution is to handle this directly via SDK, no flash involved
`wifi_set_opmode_current`
>Set Wi-Fi working mode to Station mode, SoftAP or Station + SoftAP, and do not
update flash.

That or toggle persistent before and after changing modes.

**Comment by tablatronix** [comment]
Testing good so far

```
/**
 * toggle mode, non persistant
 * @param m WiFiMode_t
 */
bool WiFiManager::wifimode(WiFiMode_t m) {
    DEBUG_WM(F("changing wifi mode non persistant"));
    if(wifi_get_opmode() == (uint8) m) {
        return true;
    }

    bool ret = false;

    ETS_UART_INTR_DISABLE();
    ret = wifi_set_opmode_current(m);
    ETS_UART_INTR_ENABLE();

    return ret;
}
```
Ideally we would be able to rework the library to not step on users configs.

do a `wifi_station_get_config` save state locally, switch to lib ap, finish,  restore users ap.
or when in doubt reboot works now since not overwriting flash.

**Comment by tablatronix** [comment]
It is also worth noting that even though opmode wont be saved when you start the softap the conf is always saved.

**Comment by neilyoung** [comment]
How do you  ETS_UART_INTR_ENABLE(); after return?

**Comment by tablatronix** [comment]
huh?
