### ISSUE TITLE
Weird behaviour when adding custom head.

### ISSUE THREAD

**Issue by ArnieX** [tzapu/WiFiManager#316]
Hi @tzapu,

first of all, thanks for great library. I hope you could point me into right direction, I have quite altered your original design using custom head, added image to h1 instead of text. Hide h3, etc.

But this is what happens to me multiple times. Sometimes it works perfectly, other times it do not and I can't see any scheme or how to reproduce this behaviour.

This is how it should look like:
<img width="984" alt="screen shot 2017-02-12 at 19 23 27" src="https://cloud.githubusercontent.com/assets/2325116/22865156/6798142c-f15e-11e6-97fc-0b7f34666e85.png">

This is what happens:
<img width="1012" alt="screen shot 2017-02-12 at 19 21 58" src="https://cloud.githubusercontent.com/assets/2325116/22865166/84f44b3a-f15e-11e6-85df-f45494ce429a.png">
<img width="1012" alt="screen shot 2017-02-12 at 19 15 17" src="https://cloud.githubusercontent.com/assets/2325116/22865164/7e0bc14a-f15e-11e6-9960-8067271165a6.png">
<img width="1012" alt="screen shot 2017-02-12 at 19 15 09" src="https://cloud.githubusercontent.com/assets/2325116/22865161/775227d6-f15e-11e6-899e-130579455f1e.png">

Sometimes the main screen works but when I click any section it opens empty:
<img width="1440" alt="screen shot 2017-02-12 at 18 49 01" src="https://cloud.githubusercontent.com/assets/2325116/22865170/9dbbf776-f15e-11e6-9b67-6e12d92b932c.png">

Any idea? Thanks for help.

BR,

Martin

**Comment by nhaduy99** [comment]
Similar issue, I have tested that, in my case the scanning network function (WiFi.scanNetworks();) case a bit long time and this make the web crash or appears nothing.
Looking for solution.........
Regards

**Comment by ArnieX** [comment]
Thanks, let me know if you find anything.

**Comment by tablatronix** [comment]
#400
