### ISSUE TITLE
Can I have readonly parameter on ConfigPortal?

### ISSUE THREAD

**Issue by angel1st** [tzapu/WiFiManager#320]
Hi there,
In certain cases, ESP device Mac Address is required to be known. One possible reason for it is when the router uses Mac filtering. 
Therefore, I would like to have mac address shown on `ConfigPortal`, when the ESP module is on AP mode.
I suspect I should use `wifiManager.addParameter` to add it as parameter and it is available via `WiFi.macAddress()`, however, I rather have it as **readonly** parameter on the `ConfigPortal`.
How can I do that?

**Comment by tzapu** [comment]
hi

mac address should be listed on the info page i think

cheers

**Comment by angel1st** [comment]
Thanks, @tzapu, makes sense.
Best Regards
