### ISSUE TITLE
Can saved wifi credentials be cleared using the reset button.

### ISSUE THREAD

**Issue by FaizB** [tzapu/WiFiManager#325]
Hi I am new to the ESP8266

I am using the wifiManager to give me an access point to configure my wifi credentials. 
I was wondering without using ( wifiManager.resetSettings(); ) explicitly. So every time I have to input my wifi credentials is there a method where I can use the RESET button on the nodeMCU to initialize (wifiManager.resetSettings();), so I can change wifi credentials whenever I choose or send it into AP mode when the RESET button is pressed.

**Comment by tusharpc** [comment]
look for KEn taylor's fork here for his version of the wifi manager

**Comment by trungkiendt9** [comment]
//Reset mạng wifi đã lưu tên
        int reset_level = analogRead(A0);
        Serial.print("reset_level: ");
        Serial.println(reset_level);

        if (reset_level >500) {
                WiFi.disconnect(true);
                delay(2000);
                ESP.reset();
        }

**Comment by saleemnabaki** [comment]
trungkiendt9  Thank you so much .. Work very well
