### ISSUE TITLE
Q: How to determine if connected  in main loop  ? 

### ISSUE THREAD

**Issue by Gerry33** [tzapu/WiFiManager#327]
I need to query somehow if I'm connected within the main loop. 
I send messages to an MQTT server. If I'm not connected I have to buffer.

Thanks for this library ! 

br
Gerry

**Comment by tzapu** [comment]
hi,

you can just use the normal esp8266 and mqtt lib functions

cheers

**Comment by Gerry33** [comment]
@tzapu 
Thank you very much for the fast response.  Appreciated ! 

I wasn't aware that standard ESP routines are usable .
This did it: 
  ` if (WiFi.status()  == WL_CONNECTED )`

Again, a big thumb up for this lib.
br
Gerry

**Comment by tzapu** [comment]
no probs, glad you like it

cheers
