### ISSUE TITLE
Add singal strength in AP listings

### ISSUE THREAD

**Issue by tablatronix** [tzapu/WiFiManager#33]
- [x] Add quality as a standard range of -50-0dbm.
ideas ?

```
int getRSSIasQuality(int RSSI){
  //  int dBm = WiFi.RSSI();
  int quality = 0;
  
  if(dBm <= -100){
        quality = 0;
  }else if(dBm >= -50){
        quality = 100;
  } else {
        quality = 2 * (dBm + 100); 
  }
  return quality;
}
```

Any easy way to sort this also, client or server ?

**Comment by tablatronix** [comment]
Also show duplicate ap names as one and auto select best ?

**Comment by tzapu** [comment]
nice, will add the rssi indicator/quality
will think of the duplicate rssis, i think i need to get some hardware setup to test this
cheers

**Comment by tablatronix** [comment]
- [ ] add strength filtering optional threshold

**Comment by tablatronix** [comment]
I figure it can act like most computer selectors, not reinventing wheel , we can probably find the specs everyone uses. I know they remove low signals from listings, and they combine duplicate and and auto select somehow. Right now my module shows 3 times as many APs as my other devices do, obviously we dont' need qos for IOT, so this might be a bit different, but might make auto selecting best easier. and simplifying the interface.

**Comment by tzapu** [comment]
maybe a flag to not show all networks with quality 0
no reason why that can t be an arbitrary value though

btw, i am seeing more ap s on the esp modules as well, but, i can also connect from further away from my esps than my phone for instance, they just seem to outperform a lot of other wifi devices

**Comment by tzapu** [comment]
added filter for low quality signal set by using   `wifiManager.setMinimumSignalQuality();`
will need to add documentation soon, it does take a parameter that sets under what percent to ignore networks, defaults to 8%
inspired from http://www.speedguide.net/faq/how-does-rssi-dbm-relate-to-signal-quality-percent-439

**Comment by domonetic** [comment]
Back my holiday documented all.

**Comment by tzapu** [comment]
this is done, documentation will be coming shortly, there is another issue in which we can discuss dropdowns and duplicate networks
cheers
