### ISSUE TITLE
detect router unlink

### ISSUE THREAD

**Issue by plcabgut** [tzapu/WiFiManager#337]
how can i detect if the router is down?

**Comment by Daemach** [comment]
WiFi.status();

iPhone. iTypos. iApologize. 




On Wed, Mar 22, 2017 at 3:46 PM -0700, "plcabgut" <notifications@github.com> wrote:












how can i detect if the router is down?

**Comment by merlokk** [comment]
if (WiFi.status() != WL_CONNECTED) {
    delay(100); // here you can do something
  }
