### ISSUE TITLE
Auto join open APs

### ISSUE THREAD

**Issue by tablatronix** [tzapu/WiFiManager#34]
Can esp8266 lib even detect this ?

Combined with strength logic, this might be neat for a roaming option.
Could also add wildcard ap matching, for example how xfinity and atts free wifi works.

**Comment by tzapu** [comment]
i think you can detext open ip networks, but then it needs logic to retry the connection when you fail, and so on.
i am thinking that might be better off in a separate library just for that, outside the scope of WiFiManager

**Comment by tablatronix** [comment]
Maybe we can just add secure flags to the listings for manual ID.

**Comment by tzapu** [comment]
yup, will add something like that as soon as i get another chunk of time i can allocate to this

**Comment by tablatronix** [comment]
Ill brush up on my C and take a look if i get time.

**Comment by tzapu** [comment]
added a padlock indicator for secured networks
please test
