### ISSUE TITLE
manual reset

### ISSUE THREAD

**Issue by ohgary** [tzapu/WiFiManager#340]
Couldnt find a way to put in code request, so will try here. It would be nice if there was support in the module to check a digital pin and in high to reset the stored data and start up the AP.  A "factory" restart type button.

**Comment by telanoc** [comment]
You can already do that yourself, quite easily.  It's part of the core ESP wifi library.  Just monitor a pin (I do it only at startup) and if it's set to the value you're looking for, call

    WiFi.disconnect(true);

to have the ESP forget its last connected access point.
