### ISSUE TITLE
AutoconnectAP stay active after connection to network!

### ISSUE THREAD

**Issue by pbecchi** [tzapu/WiFiManager#345]
I want to be able to use WIFI station mode. 
But after Autoconnect call the autoconnectAP remain active and the mode is WiFi STa_AP!
I have tried to call WIFI.mode(WIFI_STA) before and after Autoconnect but I don't get any change!

**Comment by andysc** [comment]
There's been some activity in Issue [#296](https://github.com/tzapu/WiFiManager/issues/296) about this recently, and a PR which should address what you're seeing.
