### ISSUE TITLE
AutoConnectAP and on demand portal?

### ISSUE THREAD

**Issue by johnhmacleod** [tzapu/WiFiManager#346]
I would like to normally connect automatically but have the option to press a button to reconfigure it.  If I do that & enter the portal while it is connected, I get a crash. (not surprising since the doco says don't use both!)  Is there a way to do this?

**Comment by andysc** [comment]
Worth having a look at Issue [#296](https://github.com/tzapu/WiFiManager/issues/296) for related discussion
