### ISSUE TITLE
Accespoint Config Mode does not work well

### ISSUE THREAD

**Issue by bobybobybob** [tzapu/WiFiManager#350]
Hello, I have four eps12E. I put these in Accespoint Config mode to display Accespoint.

With two I can connect and adjust everything.
For the other two, a stable connection is not possible. The signal travels in a few seconds so I do not see the config page.

The script code is the same for all four. Also the same firmware. Identical current source.

In serial print, writes on the non workung one something like reset ets Jan 8 2013, rst cause: bootmode:
Wdt reset

Is this a Software Bug oder Hardware problem?

á
mounting FS...
mounted file system
192.168.1.60
Standortname
24
*WM: Adding parameter
*WM: blynk
*WM: Adding parameter
*WM: STUNDEN_H
*WM: 
*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Custom STA IP/GW/Subnet
*WM: 192.168.1.60
*WM: Using last saved values, should be faster
*WM: Connection result: 
*WM: 0
*WM: SET AP STA
*WM: 
*WM: Configuring access point... 
*WM: AutoConnectAP
*WM: AP IP address: 
*WM: 192.168.4.1
*WM: HTTP server started

 ets Jan  8 2013,rst cause:4, boot mode:(3,1)

wdt reset
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v3de0c112
~ld
á
mounting FS...
mounted file system
192.168.1.60
Standortname
24
*WM: Adding parameter
*WM: blynk
*WM: Adding parameter
*WM: STUNDEN_H
*WM: 
*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Custom STA IP/GW/Subnet
*WM: 192.168.1.60
*WM: Using last saved values, should be faster
*WM: Connection result: 
*WM: 0
*WM: SET AP STA
*WM: 
*WM: Configuring access point... 
*WM: AutoConnectAP
*WM: AP IP address: 
*WM: 192.168.4.1
*WM: HTTP server started

**Comment by maxdd** [comment]
Have you checked your hw pins configuration of the second device?

**Comment by javieryanez** [comment]
I have the same problem with a Witty Cloud (ESP-12F)

**Comment by tablatronix** [comment]
Could be power supply could be corrupt memory try esptool erase flash?

**Comment by bobybobybob** [comment]
> Could be power supply could be corrupt memory try esptool erase flash?
No, i have 8 ESP12E and F from diferent sellers. 3 are very stabile and the other are shit. 

Super Power 3.4V 3A, many Capacitators and that Pullup, Pulldown rubish for improve Stability helps not much. 

I found out that the instabile ESP need one connection to WLAN and after upload new script, the problem script work without problems and most stabile. It is maybe a Hardwarebug.

**Comment by tablatronix** [comment]
What sketch sounds like

**Comment by tablatronix** [comment]
what sketch ? Does the sketch cause the reset on purpose, if so it is probably this issue

#425

**Comment by bobybobybob** [comment]
Excample

I buy a new RAW ESP12E or ESP12F. The lite one no wemos. I upload a script likte

in the loop
int blabla = 0
blabla = blabla + 1
serial.print blabla

it will count up maybe up to 2000 then the watchdog Reset come and it start again new

When i upload the same sketch again, it count rising. Maybe in first it count up to 5000, in the second upload it count only to 2000 and after some more most counting end ner 1000.

But if i upload a script that make hardcoded wlan connection and then overwrite it withh the counter script without wlan, it count up to endlees or one some ESP the watchdog again but in very higher numbers where a litte capacitator realy help stability. 

Is that ESP12 one time in his life connected with wlan, it is stability. Stability go away when flash firmware new + erase.

**Comment by bobybobybob** [comment]
do you can read german? if yes i can write Deutsch
