### ISSUE TITLE
Problem with WiFi.scanNetworks();

### ISSUE THREAD

**Issue by nhaduy99** [tzapu/WiFiManager#351]
Hi,
I am using this library but sometimes the config AP portal doesn't show off when scanning the local wifi (page 192.168.4.1/?wifi). I check on the Serial Monitor:
*WM: Scan done
*WM: Yamaha
*WM: -60
*WM: My Dung_plus
*WM: -87
*WM: Sent config page

Sometimes the web appears with missing parts and one weird word of: "CTYPE html>" appeared. I searched that this wear word appears when the web is not fully HTML website. 

How do I fix this?

Best regards,
Seppy

**Comment by svh1985** [comment]
I'm having the same issues; especially when there are a lot of wifi networks around.

**Comment by tablatronix** [comment]
How many aps?
I have 25 and have never encountered this

**Comment by svh1985** [comment]
I can test it when I'm back home, we have 40+ WiFi networks from all the neighbours at home.

**Comment by tablatronix** [comment]
k
interestingly enough I am having a similar symptom unrelated to this issue

**Comment by svh1985** [comment]
I'm guessing that it has something to do with the ESP running out of memory when it has to do all the "find & replace" actions during the HTML output generation.

**Comment by tablatronix** [comment]
Yeah I am going to check the output and see whats mangled, oddly mine only occurs if i am not calling handlewifi fast enough, so there is some asynchronous problems with the server handling.

**Comment by tablatronix** [comment]
_apname is const char and getting lost
refactoring in my dev branch required me to change this anyway for non blocking mode, and inadvertently fixes this bug also. Basically chanve _apname and _appassword to strings, nuch easier to deal with.
