### ISSUE TITLE
Save and customize user parameters in ConfigPortal

### ISSUE THREAD

**Issue by DjSchakal** [tzapu/WiFiManager#354]
Hello,
Great software,

Is there a possibility to adjust and save the parameters station IP, gatteway IP, network mask as well as the choice possibility DHCP or Static IP OnDemand Config Portal?
Furthermore, I would like to pass 3 parameters from the Config Portal into the user program.

Thanks for the support

**Comment by spamloco** [comment]
Try the example [AutoConnectWithFSParameters.ino](https://github.com/tzapu/WiFiManager/blob/master/examples/AutoConnectWithFSParameters/AutoConnectWithFSParameters.ino)
