### ISSUE TITLE
Stucking after credential wifi saved

### ISSUE THREAD

**Issue by nhaduy99** [tzapu/WiFiManager#358]
Hi, I have the problem that after giving the proper SSID and Password, the ESP8266 (WEMOS D1 mini) is stucked at saving the SSID.
*WM: Sent wifi save page
*WM: Connecting to new AP
*WM: Connecting as wifi client...

It stops there forever, then I must hard-reset the ESP, it connects to the wifi with the SSID and password I have given last time.
Anyone has the same trouble and solution?
I use Wifimanager v12.0.0

Thannks

**Comment by pieman64** [comment]
I have noticed the same.
However if you have the timeout set the ESP should eventually reset.
