### ISSUE TITLE
WiFiManager

### ISSUE THREAD

**Issue by MuruganVithul** [tzapu/WiFiManager#359]
Hi tzapu,

I am using arduino 1.6.5 
board manager url: http://arduino.esp8266.com/stable/package_esp8266com_index.json

i am facing below error 

Arduino: 1.6.5 (Windows 7), Board: "Generic ESP8266 Module, Serial, 80 MHz, 40MHz, DIO, 115200, 512K (64K SPIFFS)"

C:\Users\murugan\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp: In member function 'int WiFiManager::connectWifi(String, String)':
C:\Users\murugan\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp:244:18: error: no matching function for call to 'ESP8266WiFiClass::begin()'
       WiFi.begin();
                  ^
C:\Users\murugan\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp:244:18: note: candidates are:
In file included from C:\Users\murugan\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.h:16:0,
                 from C:\Users\murugan\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp:13:
C:\Users\murugan\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\1.6.5-947-g39819f0\libraries\ESP8266WiFi\src/ESP8266WiFi.h:57:9: note: int ESP8266WiFiClass::begin(const char*, const char*, int32_t, uint8_t*)
     int begin(const char* ssid, const char *passphrase = NULL, int32_t channel = 0, uint8_t bssid[6] = NULL);
         ^
C:\Users\murugan\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\1.6.5-947-g39819f0\libraries\ESP8266WiFi\src/ESP8266WiFi.h:57:9: note:   candidate expects 4 arguments, 0 provided
C:\Users\murugan\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\1.6.5-947-g39819f0\libraries\ESP8266WiFi\src/ESP8266WiFi.h:58:9: note: int ESP8266WiFiClass::begin(char*, char*, int32_t, uint8_t*)
     int begin(char* ssid, char *passphrase = NULL, int32_t channel = 0, uint8_t bssid[6] = NULL);
         ^
C:\Users\murugan\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\1.6.5-947-g39819f0\libraries\ESP8266WiFi\src/ESP8266WiFi.h:58:9: note:   candidate expects 4 arguments, 0 provided
C:\Users\murugan\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp: In member function 'void WiFiManager::handleRoot()':
C:\Users\murugan\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp:364:32: error: 'FPSTR' was not declared in this scope
   String page = FPSTR(HTTP_HEAD);
                                ^
C:\Users\murugan\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp: In member function 'void WiFiManager::handleWifi(boolean)':
C:\Users\murugan\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp:384:32: error: 'FPSTR' was not declared in this scope
   String page = FPSTR(HTTP_HEAD);
                                ^
C:\Users\murugan\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp:429:57: error: invalid operands of types 'const char [9]' and 'const char*' to binary 'operator+'
               DEBUG_WM("DUP AP: " + WiFi.SSID(indices[j]));
                                                         ^
C:\Users\murugan\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp:500:40: error: 'class IPAddress' has no member named 'toString'
     item.replace("{v}", _sta_static_ip.toString());
                                        ^
C:\Users\murugan\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp:509:40: error: 'class IPAddress' has no member named 'toString'
     item.replace("{v}", _sta_static_gw.toString());
                                        ^
C:\Users\murugan\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp:518:40: error: 'class IPAddress' has no member named 'toString'
     item.replace("{v}", _sta_static_sn.toString());
                                        ^
C:\Users\murugan\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp: In member function 'void WiFiManager::handleWifiSave()':
C:\Users\murugan\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp:578:32: error: 'FPSTR' was not declared in this scope
   String page = FPSTR(HTTP_HEAD);
                                ^
C:\Users\murugan\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp: In member function 'void WiFiManager::handleInfo()':
C:\Users\murugan\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp:598:32: error: 'FPSTR' was not declared in this scope
   String page = FPSTR(HTTP_HEAD);
                                ^
C:\Users\murugan\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp:618:27: error: 'class IPAddress' has no member named 'toString'
   page += WiFi.softAPIP().toString();
                           ^
C:\Users\murugan\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp: In member function 'void WiFiManager::handleReset()':
C:\Users\murugan\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp:638:32: error: 'FPSTR' was not declared in this scope
   String page = FPSTR(HTTP_HEAD);
                                ^
C:\Users\murugan\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp: In member function 'boolean WiFiManager::captivePortal()':
C:\Users\murugan\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp:690:21: error: 'class ESP8266WebServer' has no member named 'hostHeader'
   if (!isIp(server->hostHeader()) ) {
                     ^
C:\Users\murugan\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp:692:84: error: 'class WiFiClient' has no member named 'localIP'
     server->sendHeader("Location", String("http://") + toStringIp(server->client().localIP()), true);
                                                                                    ^
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by tablatronix** [comment]
Sounds like a dev env problem
