### ISSUE TITLE
Content-length is not set properly

### ISSUE THREAD

**Issue by suculent** [tzapu/WiFiManager#362]
Works on iPhone, but fails on certain Androids accessing the Captive Portal. Solution to fix this was straitforward... adding explicit Content-Length header before all ->send requests.

**Comment by suculent** [comment]
Following solution works for me:

https://github.com/suculent/WiFiManager/commit/ada93b721a235f4bae379e1804c32d962541b992

**Comment by scop** [comment]
I was bitten by this on Android 7.1.2, and the suggested change works for me too, please apply.

**Comment by scop** [comment]
@suculent, could you submit a pull request to get this fix in? Thanks!

**Comment by suculent** [comment]
I've already done this quite a while ago https://github.com/tzapu/WiFiManager/pull/363

**Comment by tzapu** [comment]
thanks guys, merged

**Comment by tablatronix** [comment]
The sdk seems to already send content-length headers, I wonder why android is so picky about the order maybe ?

**Comment by suculent** [comment]
It did not happen only on Android, at least I'm not the Android case, we use iPhones and iPad Pro to test WiFiManager in AP mode. 

I need to find correct test case. After upgrading to latest WiFiManager I need to solve own issues first before going back to AP mode. 

Odesláno z iPhonu

15. 9. 2017 v 18:44, Shawn A <notifications@github.com>:

**Comment by tablatronix** [comment]
Maybe this changed in SDK at some point, shrug
