### ISSUE TITLE
Arduino uno using wifimanager

### ISSUE THREAD

**Issue by gkgk3442** [tzapu/WiFiManager#366]
Arduino uno using wifimanager

Arduino -> esp-12
RX -> TX
TX -> RX
Reset -> Reset
3.3v -> VCC and CH_PD
GND -> GND

Is this the right setting and use?

I would like to know how to use wifimanager in arduino uno.

I am sorry for my poor English.

**Comment by tzapu** [comment]
hi, this is only for esp8266 standalone, sorry
