### ISSUE TITLE
send new ip adress

### ISSUE THREAD

**Issue by sloba1988** [tzapu/WiFiManager#369]
hello, where to put the line of code, that when is successfully connect sending a new ip address instead of
 `handleWifiSave()` - page (I found a way to stop this page)
for example, when esp start, it is on the static address 192.168.4.1 but when it get  `wifisave?s...` , esp connect and go out of the station mode, but where do I put this line of code:
`server->send ( 200, "text/html", WiFi.localIP().toString() ); `
to return the ip address before leaving the station mode. I tried here `int WiFiManager::connectWifi(String ssid, String pass)`  but it is under error. 
 thank you

**Comment by tablatronix** [comment]
You probably figured this out already
