### ISSUE TITLE
Manually manage WiFi connection using WiFiManager

### ISSUE THREAD

**Issue by vks007** [tzapu/WiFiManager#375]
Hi, I am working on a project where having an active WiFi connection is not critical and so my I can live without one for some time and keep retrying at a certain interval. I want to use WiFiManager library for this but I am unable to do so because I want to manage the retry interval as well as when to retry myself. While this library will try to connect to WiFi itself when it gets the credentials. So my specific question is : Can I stop WiFiManager to try connecting to WiFi , rather I will connect to it when I need to. I just need WiFiManager to manage the WiFi credentials for me. Is it possible?

On investigating further I see the following line of code which is used in WiFiManager.cpp to signal a connection attempt to WiFi. Would somebody who knows the code well be able to advise if I just comment out this statement, would I be good to manage the connection to WiFi part manually ?
`  connect = true; //signal ready to connect/reset
`

**Comment by tablatronix** [comment]
See the portalondemand example. Wifimanager already does this
