### ISSUE TITLE
Access point no longer shows

### ISSUE THREAD

**Issue by jimbroze** [tzapu/WiFiManager#380]
Initially, using WifiManager worked straight away on my NodeMCU, presenting an access point that allowed me to connect. After a failed attempt at connecting to my router, it no longer creates an access point despite suggesting that it should; even after flashing the firmware and trying again. Terminal outputs show an IP address followed by "HTTP server started" but no access point exists. Could this suggest that the hardware is broken?

**Comment by tablatronix** [comment]
Most likely a bug #115
