### ISSUE TITLE
How to edit the captive portal page 

### ISSUE THREAD

**Issue by ashtam55** [tzapu/WiFiManager#388]
First of all, I kindly say thank you for your work @tzapu. This library helps a lot and works faster for me, but an issue came up when I am changing the Captive Portal page in template.h . I am not able to add an image to the first page. Can anybody help with this?
Thank you in advance.

**Comment by denisvm** [comment]
You can add images embedding them directly into HTML if they are small enough. Here is some info about it: https://en.wikipedia.org/wiki/Data_URI_scheme
Otherwise you can store the image in SPIFFS and recover it from there if needed.
