### ISSUE TITLE
allow custom parameters to be configured

### ISSUE THREAD

**Issue by tzapu** [tzapu/WiFiManager#4]
so you can use the interface for other things than wifi user and password

**Comment by Sylvania2** [comment]
Would be nice to save BLYNK token this way

**Comment by tzapu** [comment]
or emoncms tokens :)
i am thinking on moving to FS support instead of EEPROM before implementing this.

**Comment by nibelungen** [comment]
+ on that.
Other ideas to save:

pre defined SSIDs and PWs make use of known networks such as hotspots.
Way to implement - retry different/saved credentials before going to AP mode.

Maybe up to 5 pre defined Credentials.

**Comment by AndersV209** [comment]
@tzapu any idea on when you will add FS support ?

**Comment by tzapu** [comment]
@AndersV209 based on the end of discussion here https://github.com/esp8266/Arduino/issues/849#issuecomment-146499499
I am going through with simplifying it first of all so it's easy for people just getting started to use it, in the spirit of Arduino.
I do have some thoughts to still offer advanced support like FS, but I'd like to sort the stuff on igrr's list first of all

**Comment by tablatronix** [comment]
2 simple callouts/filters should suffice for this.

**Comment by Jorgen-VikingGod** [comment]
Currently I add this "feature" as fixed code in my fork
because I need to configure MQTT host,port,user,pass

I try to add this as generic part - but currently no time left for this :/
We will a method to add/handle additional HTML code for the submit form
Or just simple method to add one entry by following parameters:
- name
- default value
- max length
- type

**Comment by tzapu** [comment]
what i m thinking is to give it an array of params you need, and get a callback with them filled in

**Comment by jeremyabel** [comment]
Would also be cool to be able to pass in our own css style string.

**Comment by tzapu** [comment]
@jeremyabel will take it into consideration
thanks

**Comment by rpseng** [comment]
Just sent a pull request #47 with a working version with custom parameters to be configured by the user.

Each parameter has an id, placehoder, default value and maximum length. It worked fine for me, check the example file.

All the best.

**Comment by tzapu** [comment]
hi guys, i have modified a bit the pull request kindly provided by @rpseng  (THANK YOU!!!) so anyone can use their own storage mechanism for those parameters
I have added a FS storage example. Will add an EEPROM example soonish as well.
It is not as pretty as the original version nor as simple, but I really did not want to readd eeprom or FS as a dependency to WiFiManager
If anyone could take a look and let me know if they feel is ok or not, the branch is here
https://github.com/tzapu/WiFiManager/tree/dev

if not, i will merge it in a couple of days

**Comment by rpseng** [comment]
Hi tzapu, I think your dev branch is fine! Now there is room for some cleanup, there are several variables/methods not used anymore.

Regarding the example using EEPROM, I believe it is very welcome. Very simple ESP-01 setups will benefit from it.

**Comment by tzapu** [comment]
thanks @rpseng 
will cleanup, release this one, then use your code to make an eeprom version as well.
Thanks.

**Comment by tzapu** [comment]
added custom parameters to main branch together with FS storage example
now need to fix conflicts with other pull requests :P

**Comment by tzapu** [comment]
this has been added, examples are there, documentation is coming shortly

**Comment by iranweld** [comment]
i want use wifimanger for this file
[link](https://gist.github.com/4refr0nt/829052635894da0f5715)
butt i cannat do it
i want read this parameter by wifimanger.h
String mqttServerName = "m11.cloudmqtt.com";            
int    mqttport = 10927;                               
String mqttuser =  "test";                            
String mqttpass = "test"; 
if possible plz help me
