### ISSUE TITLE
add library.json and others files

### ISSUE THREAD

**Issue by domonetic** [tzapu/WiFiManager#42]
I added the files to standardize the library.
It allows that in a new update, can be made from the Library Manager.

**Comment by tzapu** [comment]
thank you very much,
i ll be back in full working order on the 4th and will go through everything asap

**Comment by tzapu** [comment]
@domonetic merged the library changes
thank you very much

**Comment by domonetic** [comment]
You are welcome. I took the audacity to propose to be included in the Library Manager.
Please go and approves the inclusion

https://github.com/arduino/Arduino/issues/4364#issuecomment-168278446

**Comment by cmaglie** [comment]
@tzapu remember also to move the v1.4 tag!

**Comment by tzapu** [comment]
done, thank you again

**Comment by cmaglie** [comment]
> @tzapu remember also to move the v1.4 tag!

ops, I mean "v0.4", basically the library.properties file must appear here:

https://github.com/tzapu/WiFiManager/tree/v0.4

**Comment by domonetic** [comment]
create a new release.

**Comment by tzapu** [comment]
hi, created a new tag, 0.5 and updated the library.json and library.properties files
is it ok?

**Comment by cmaglie** [comment]
Well not yet :-) it seems that you created the new tag **before** changing library.properties, so the tag 0.5 now points to a library.properties with "version=0.4" written in it.

https://github.com/tzapu/WiFiManager/tree/0.5
https://github.com/tzapu/WiFiManager/blob/0.5/library.properties

to fix this:
- remove the tag 0.5
- remake the tag 0.5 on master branch.

**Comment by domonetic** [comment]
need change version on library.properties, and merge changes in keywords.txt. Please

**Comment by tzapu** [comment]
ok, updated everything inclusing keywords.txt ( @domonetic somehow the pull request was merged but the keywords still cut off, modified it directly)
thanks

**Comment by domonetic** [comment]
thanks

**Comment by domonetic** [comment]
Congratulations, now available in the library manager
https://github.com/arduino/Arduino/issues/4364#issuecomment-168714767

**Comment by tzapu** [comment]
thank you very much Maximiliano , you did a great job of everything
