### ISSUE TITLE
Questions about wifimanager library?

### ISSUE THREAD

**Issue by nickiereturn** [tzapu/WiFiManager#426]
I have question on ESP8266.   After my ESP8266 already connected to WiFi and it works properly OK.   After 1-2 Days, it reset by itself and Turn back into "Accesspoint" .   Waiting for me to re-input the Password of WiFi again.   This situation happen very often, even I make sure 100% that there are NO failure power supply 220V.     Because as I used for 1 week,  I had to re-input the same WiFi Password 3-4 times.  I Know that In the Library,  Once my ESP8266, can NOT find the Wifi,  it will turn itself into accesspoint.    But in real life, even though it found my Wifi, it still turn into accesspoint.

Are there any solution,  that  Once my ESP8266 reset itself and it will NOT turn into Accesspoint anymore,  but keep connecting the current WiFi and password at all time.     And if I really want it to search for new Wifi,  I have to press one button which I can create by myself.

Do you have any Library that can solve this kind of problem. 
or
Can you make Library,  Saying: " Keep Searching until it finds the Current Wifi forever and reconnect the existing Wifi. "

Please help?

**Comment by tablatronix** [comment]
#247
