### ISSUE TITLE
[SOLVED?]: "using" problem with RSSI and SSID

### ISSUE THREAD

**Issue by giovannicandotti** [tzapu/WiFiManager#428]
Hi,
I faced a problem when compiling under Debian with Eclipse.
In header **ESP8266WiFi.h**

class ESP8266WiFiClass : public ESP8266WiFiGenericClass, public ESP8266WiFiSTAClass, public ESP8266WiFiScanClass, public ESP8266WiFiAPClass {
    public:
[...]
        using ESP8266WiFiSTAClass::SSID;
        using ESP8266WiFiSTAClass::RSSI;
[...]
        using ESP8266WiFiScanClass::SSID;
        using ESP8266WiFiScanClass::RSSI;
[...]

causes a compiling error on **ESP8266WiFi.cpp**
/* Wifi config page handler */
void WiFiManager::handleWifi(boolean scan) {
[...]
      // old sort
      for (int i = 0; i < n; i++) {
        for (int j = i + 1; j < n; j++) {
          if (WiFi.RSSI(indices[j]) > WiFi.RSSI(indices[i])) {     **// <-- error here**
            std::swap(indices[i], indices[j]);
          }
        }
      }
[...]

and later on too, involving WiFi.SSID too.
Imo, it seems due to compiler not being able to properly address to ESP8266WiFiScanClass::RSSI.

**Solution:** 
1) in **ESP8266WiFiScan.h** add something like 
        **String mySSID(uint8_t networkItem);
        int32_t myRSSI(uint8_t networkItem);**

2) in **ESP8266WiFiScan.ccp** add something like 
**int32_t ESP8266WiFiScanClass::myRSSI(uint8_t i) {	return RSSI(i);   }**
**String ESP8266WiFiScanClass::mySSID(uint8_t i) {	return SSID(i); }**

3) in **ESP8266WiFi.h** add something like 
        **using ESP8266WiFiScanClass::mySSID;
        using ESP8266WiFiScanClass::myRSSI;**

4) in **ESP8266WiFi.cpp** substitute 
**WiFi.RSSI** with **WiFi.myRSSI**
**WiFi.SSID** with **WiFi.mySSID**

Sorry for poor coding style, quick & dirty solution and maybe violation of naming convention
Just an idea to solve.

**[EDIT]**
By the way, the original code generates compiling errors on Mac+Eclipse, while linking is able to complete, producing a working executable

**Comment by tablatronix** [comment]
do you have exact errors ?

**Comment by giovannicandotti** [comment]
attached the screenshot

**Comment by tablatronix** [comment]
I see no screenshot

**Comment by giovannicandotti** [comment]
attached to this email

**Comment by tablatronix** [comment]
You have to goto github to post images
