### ISSUE TITLE
ubidots wifimanager

### ISSUE THREAD

**Issue by alejotenis** [tzapu/WiFiManager#432]
Hi tzapu.
I am doing a project, and I need ubidots to connect through wifimanager, ubidots connects with ssid and pass when it is fixed but when I try to connect with wifimanager, it can not connect. You can help.

**Comment by rizqiv2** [comment]
yea maybe my issue almost the same with you 👍

**Comment by tablatronix** [comment]
Is this like blynk where the library wrongly handles the wifi connect internally?

**Comment by alejotenis** [comment]
i could solve de problem thank you sorry for my english
