### ISSUE TITLE
it does not work

### ISSUE THREAD

**Issue by shahinesi** [tzapu/WiFiManager#437]
![image](https://user-images.githubusercontent.com/16535600/31439657-ce840940-ae99-11e7-8101-745c77c30ed6.png)

**Comment by tablatronix** [comment]
Why not post your code or say which examples you tried

**Comment by shahinesi** [comment]
@tablatronix How to do send ??

**Comment by shahinesi** [comment]
![image](https://user-images.githubusercontent.com/16535600/31478277-2bfb0cea-af1c-11e7-8d29-d865c6ee19d6.png)

**Comment by shahinesi** [comment]
![image](https://user-images.githubusercontent.com/16535600/31478598-560f38b0-af1e-11e7-8868-f43a8d572749.png)

**Comment by tablatronix** [comment]
Test using one of the simple examples, or post actual code.

**Comment by shahinesi** [comment]
@tablatronix i used 
https://github.com/tzapu/WiFiManager/tree/master/examples/AutoConnect
but dose not workd!

![image](https://user-images.githubusercontent.com/16535600/31553460-6b2e277c-b047-11e7-95e5-77ea9cd1d312.png)
plz help me

**Comment by tablatronix** [comment]
Ststus 3 means connected, your module is connecting already.

Try erasing settings or using the ondemand example

**Comment by shahinesi** [comment]
how do erasing settings??
