### ISSUE TITLE
Not working on NodeMCU

### ISSUE THREAD

**Issue by MrTheBarbarian** [tzapu/WiFiManager#438]
Hello!
I have problem with this library.
It's a very strange. Compiling and uploading look good. 
`Archiving built core (caching) in: C:\Users\Miroslav\AppData\Local\Temp\arduino_cache_478203\core\core_esp8266_esp8266_nodemcu_CpuFrequency_80,UploadSpeed_115200,FlashSize_4M3M_8ec7b3688a145e67bf67f6032e7ee804.a
Sketch uses 309262 bytes (29%) of program storage space. Maximum is 1044464 bytes.
Global variables use 35504 bytes (43%) of dynamic memory, leaving 46416 bytes for local variables. Maximum is 81920 bytes.
Uploading 313408 bytes from C:\Users\Miroslav\AppData\Local\Temp\arduino_build_64852/AutoConnectWithFeedback.ino.bin to flash at 0x00000000
................................................................................ [ 26% ]
................................................................................ [ 52% ]
................................................................................ [ 78% ]
...................................................................              [ 100% ]`
But after uploading, no hotspot and serial communication. Complete silence. 
The board is work properly with other sketches. But no one of the examples didn't work. How to find where is the problem?
Thanks in advance!

**Comment by magnetron** [comment]
Have you resolved this? If not, maybe post a few more details on your set-up... what hardware & software models/versions are you using?
