### ISSUE TITLE
Power Off

### ISSUE THREAD

**Issue by shahinesi** [tzapu/WiFiManager#440]
I'm turning off when I turn off the module, it's no longer a problem in the WiFi list
`#include <ESP8266WiFi.h>          //https://github.com/esp8266/Arduino

//needed for library
#include <DNSServer.h>
#include <ESP8266WebServer.h>
#include <WiFiManager.h>         //https://github.com/tzapu/WiFiManager

void setup() {
    // put your setup code here, to run once:
    Serial.begin(115200);

    //WiFiManager
    //Local intialization. Once its business is done, there is no need to keep it around
    WiFiManager wifiManager;
    //reset saved settings
   // wifiManager.resetSettings();
    
    //set custom ip for portal
    //wifiManager.setAPStaticIPConfig(IPAddress(10,0,1,1), IPAddress(10,0,1,1), IPAddress(255,255,255,0));

    //fetches ssid and pass from eeprom and tries to connect
    //if it does not connect it starts an access point with the specified name
    //here  "AutoConnectAP"
    //and goes into a blocking loop awaiting configuration
    wifiManager.autoConnect("Shahin Repiter ESP", "shahin123456789");
    //or use this for auto generated name ESP + ChipID
    //wifiManager.autoConnect();

    
    //if you get here you have connected to the WiFi
    Serial.println("connected...yeey :)");
}

void loop() {
    // put your main code here, to run repeatedly:
    
}`

Also, the name konfig will come out of the wifi list

**Comment by shahinesi** [comment]
help Me

**Comment by tablatronix** [comment]
Not really sure what you are trying to explain or do

**Comment by shahinesi** [comment]
@tablatronix I run this code, but I do not answer and I'm having trouble
