### ISSUE TITLE
Can I open AP and WebServer on a same time?

### ISSUE THREAD

**Issue by ducthinhdeveloper** [tzapu/WiFiManager#442]
For example, I use WifiManager for config ESP8266 but still need a WebServer to control Relay by HTTP. Can I do that?

**Comment by r-downing** [comment]
I'm working on a version which allows the wifi to be configured at any time, and allows the device to act as a webserver in both AP and STA mode
https://r-downing.github.io/PersWiFiManager/

**Comment by tablatronix** [comment]
This is already done in my dev pr. But advanced features like adding hooks routes is not implemented for general web serving.

**Comment by ageurtse** [comment]
how can i visit the wifimanager when serving my own webserver ?
i'm running dev  but can't manage to enter the config page

**Comment by tablatronix** [comment]
you cant run 2 webservers
