### ISSUE TITLE
Pull request with backward compatibility breaking changes

### ISSUE THREAD

**Issue by herostrat** [tzapu/WiFiManager#443]
Hey,

I am using the WiFiManager for setting up esps with e.g. mqtt connections.

During development I wanted to change the default value for the params in the webform.
This was not possible with the current code.

I changed the WiFiManagerParamter to use `String` instead. This enabled me to be more dynamic with the parameters and change them during runtime.

This has the additional value of a more save size allocation without overflows and such without thinking hard and long about array sizes during initialisation of the parameter.

If I missed your reasons for picking `const char*` instead of `String` please let me know.

Now my questions:
1. Are backward compatibility breacking changes a nogo for pull requests?

2. Are those features a good addition according to your vision of WiFiManager?

I don't want to waste your and my time modifying e.g. examples for a pullrequest if it is not in line with the main development.

**Comment by tablatronix** [comment]
What problem were you having exactly that needed to be solved.
Breaking change is not great.
