### ISSUE TITLE
WifiManager not working with ESP32

### ISSUE THREAD

**Issue by James-sjec** [tzapu/WiFiManager#444]
E:\Arduino\projects\libraries\WiFiManager-esp32\WiFiManager.cpp:746:84: error: 'class WiFiClient' has no member named 'localIP'

     server->sendHeader("Location", String("http://") + toStringIp(server->client().localIP()), true);

**Comment by Jorgen-VikingGod** [comment]
I do not dig into a port of this repo. But I did a port of the async version of WiFiManager to ESP32: https://github.com/Jorgen-VikingGod/ESPAsyncWiFiManager

**Comment by tablatronix** [comment]
wifimanager-esp32 is not a fork , closing
