### ISSUE TITLE
AP Wont Shut Down

### ISSUE THREAD

**Issue by Lethegrin** [tzapu/WiFiManager#457]
Hi there,

After using the portal to connect the device to a home wifi, the AP refuses to shut off and continues broadcasting. What code should be present to make sure it's not broadcasting after either being manually shut off or connecting as a client to another device?

**Comment by Lethegrin** [comment]
Thank you.

**Comment by tablatronix** [comment]
I have been working on some stability and bugs here
https://github.com/tzapu/WiFiManager/pull/313
If you want to take a look

Although some bugs are in core, some are fixed in 2.4.0 but some are still present with no workarounds yet. For example softapdisconnect fails always.
