### ISSUE TITLE
How to combine AutoConnectWithFSParametersAndCustomIP & OnDemandConfigPortal?

### ISSUE THREAD

**Issue by FarmerKJS** [tzapu/WiFiManager#458]
Is there any way to do this? I tried setting it up like it shows in the example but I get an error.

**Comment by tablatronix** [comment]
Whats the error?

**Comment by tablatronix** [comment]
Whats the code

**Comment by FarmerKJS** [comment]
https://pastebin.com/pUJXNTWh

It will show the portal if I connect the pin. If the pin is not connected it does this:
mounted file system
reading config file
opened config file
{"data_server":"api.thingspeak.com","update_interval":"30","api_key":"DBBRTU1YO98KYKBP","ip":"192.168.0.9","gateway":"192.168.0.1","subnet":"255.255.255.0"}
parsed json
setting custom ip from config
192.168.0.9
192.168.0.9
DBBRTU1YO98KYKBP
api.thingspeak.com
connected...yeey :)
local ip
0.0.0.0
0.0.0.0
0.0.0.0
Temperature: -196.60
connecting to api.thingspeak.com
connection failed

**Comment by tablatronix** [comment]
unrelated, but this has no argument!
setMinimumSignalQuality()

**Comment by tablatronix** [comment]
Works for me, whats wrong looks like its working fine.

**Comment by tablatronix** [comment]
There is no autoconnect in your sketch
