### ISSUE TITLE
Auto-launching web page

### ISSUE THREAD

**Issue by bill-orange** [tzapu/WiFiManager#472]
First off, thank you for the useful code.  I am trying to make my efforts accessible to non-hobbyists and this helps.  I do have a couple of questions.  

1. How the heck did you get the set-up page to launch automatically upon selection of the AP?  Can you direct me to the segment of you code that accomplishes the feat?  I would like to fork FSBrowser to do the same.

2. Does any portion of your code continue to run in loop() in the most basic example?  I have had an odd result with my iPhone using my existing code with your library.  Once my code is up and running all is well connecting from a WIN10 machine.  However, after a few minutes attempts to connect  to the iPhone are unresponsive.  Unless I made a subtle screw-up (likely) , there were no code changes except for removing smartconfig and substituting in your library, applies in the most basic way.

There are lots of issues by many people with ESP8266 web server and especially the Async server becoming unresponsive but this is especially weird.  

IDE: Arduino IDE last non-beta release
Board: NODEMCU 9.0 @160 Mhz (with battery for stability)
Code; Its big, so here's a link   https://1drv.ms/f/s!AmXKqAwyCrbxh90Ne_yQ-f9rJaa0Tw 
What it should look like: http://orangecaweather.duckdns.org:8021

Thoughts?

**Comment by tablatronix** [comment]
Captiveportal() function

**Comment by jee1mr** [comment]
@bill-orange  The trick is, to redirect all DNS requests to your own IP and if the request came for another domain then rewrite the URL to your IP. This way the device understands that there's a captive portal running and the OS pops it up natively.

**Comment by alexiszecharies** [comment]
how can i make it not pop up?

**Comment by tablatronix** [comment]
In my dev branch
setCaptivePortalEnable

I hope to merge this fork soon

**Comment by alexiszecharies** [comment]
I tried with your code and as you said it. Nevertheless, when i put the IP 192.168.4.1 in the browser it does not find a webpage. How am i supposed to send the data?

**Comment by tablatronix** [comment]
Hmm, let me test

**Comment by tablatronix** [comment]
I just committed a fix for that, thanks, sorry about that.

**Comment by alexiszecharies** [comment]
Great, it worked. Thanks. There is a weird looking kind of button called No AP set. Should that be the behaviour?

**Comment by tablatronix** [comment]
Screenshot? Dev is not well tested

**Comment by tablatronix** [comment]
Do you mean the well status?

**Comment by alexiszecharies** [comment]
![screenshot from 2018-01-12 11 38 02](https://user-images.githubusercontent.com/10675229/34899021-13c7a46a-f7d5-11e7-8de9-57cfa78fe566.png)

**Comment by alexiszecharies** [comment]
I meant the no AP set box

**Comment by alexiszecharies** [comment]
Also, I am trying to run an ajax call from a webpage (not from this portal) like this:

$.ajax({
                method: 'POST',
                url: 'http://192.168.4.1/wifisave',
                data: { 
                    's': 'PFCdud3', 
                    'p': '' 
                },
                success: function(){
                    alert('wow');
                }
            });

This works in the ESP, it connects. But it returns: Failed to load http://192.168.4.1/wifisave: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access. Do you know how I can fix this?

**Comment by tablatronix** [comment]
Yeah thats the status its called a well

**Comment by tablatronix** [comment]
You are running this from another page? This is illegal cross domain access, there are ways around it google cors

**Comment by alexiszecharies** [comment]
Yes, but I need to change code from the side of de ESP , right?

**Comment by tablatronix** [comment]
Yeah not sure how you are gonna send that header without editing library, there are no callbacks available really.

**Comment by tablatronix** [comment]
We could implement jsonp perhaps

**Comment by alexiszecharies** [comment]
That is a really good idea

**Comment by alexiszecharies** [comment]
Fixed it by adding

  server->sendHeader("Access-Control-Allow-Origin","*");
  server->sendHeader("dataType","jsonp");

in  WiFiManager::handleWifiSave.

**Comment by alexiszecharies** [comment]
Do you know if it is not recommendable to use the function wifiManager.resetSettings() ?
