### ISSUE TITLE
How to change the configured SSID and password

### ISSUE THREAD

**Issue by labajo** [tzapu/WiFiManager#480]
Hi, thanks for your library.

I tried it and I configured a Wifi network properly, but I cannot change it to another one or remove or reset the SSID saved in the devices.

How can I remove that data in order to to left de device clean?

Thank you

**Comment by labajo** [comment]
Sorry, I didn't see ```wifiManager.resetSettings();``` . Using this I managed to clean the Wifi credentials. The problem is that I cannot overwrite other Wifi credentials when I save them in the ConfigPortal.

**Comment by tablatronix** [comment]
There is a bug that causes the new ap connection to bail if already connected, perhaps this is what you mean ?

**Comment by labajo** [comment]
Yes, I think so. I saw the connection when I put the debug information visible. Thank you very much.
