### ISSUE TITLE
How to get latest updates?

### ISSUE THREAD

**Issue by TinajaLabs** [tzapu/WiFiManager#484]
I see references to code updates and I see 35 pull requests but the code looks static since August of last year.  I'm not complaining, just trying to understand if I'm missing any new features or fixes.

Is another option that I should fork this and then run pull requests on that code?

Thanks for any tips,
Chris.

**Comment by tablatronix** [comment]
I have been trying to apply changes andd updates to my fork dev branch there is a pr also. I have not merged this into origin yet however i hope to though

**Comment by tablatronix** [comment]
Merged
