### ISSUE TITLE
mDNS not supported in AP mode

### ISSUE THREAD

**Issue by bkrajendra** [tzapu/WiFiManager#5]
Hi nice idea.
Ive already implemented similar method in my project but with simple functions.
Fortunately ive found your library which has many functions similar as mine.

By the way, why are you using mDNS, as per the esp8266 arduino page this not supported in
AP mode?

**Comment by tzapu** [comment]
it was just a leftover from the intial example code intially, but in sdk 1.3.0 it seems they made mdns work in AP mode as well. it won t be long before it trickles down to the arduino ide build.

i am however pondering dropping mdns and just going with a capture portal

**Comment by tzapu** [comment]
removed mDNS reliance

**Comment by bkrajendra** [comment]
Thanks for update.
