### ISSUE TITLE
the-real-orca AutoCOnnectMultipleNetworksWithFS

### ISSUE THREAD

**Issue by mrlightsman** [tzapu/WiFiManager#506]
I have been trying to install the real-orca AutoCOnnectMultipleNetworksWithFS example.  I keep getting the error:

Arduino: 1.8.5 (Windows Store 1.8.10.0) (Windows 10), Board: "Generic ESP8266 Module, 80 MHz, ck, 26 MHz, 40MHz, DIO, 1M (512K SPIFFS), v2 Prebuilt (MSS=536), Disabled, None, 115200"
C:\mylocation\WiFiManager-master\WiFiManager-master\examples\AutoConnectMultipleNetworksWithFS\AutoConnectMultipleNetworksWithFS.ino: In function 'void load(WiFiManager&)':
AutoConnectMultipleNetworksWithFS:40: error: 'class WiFiManager' has no member named 'addAP'
               wifiManager.addAP(obj["SSID"], obj["Password"]);
                           ^
C:\mylocation\WiFiManager-master\WiFiManager-master\examples\AutoConnectMultipleNetworksWithFS\AutoConnectMultipleNetworksWithFS.ino: In function 'void save(WiFiManager&)':
AutoConnectMultipleNetworksWithFS:65: error: 'class WiFiManager' has no member named 'getAP'
     for (int i = 0; auto ap = wifiManager.getAP(i); i++ ) {
                                           ^
exit status 1
'class WiFiManager' has no member named 'addAP'

I believe I have all of the latest version of the libraries and that they are all installed correctly.  What am I missing?  Thanks.

**Comment by tablatronix** [comment]
addap is from a PR, not part of wifimanager, its someones fork
