### ISSUE TITLE
ESP8266WebServer not closing after the connection to a new AP

### ISSUE THREAD

**Issue by fabiuz7** [tzapu/WiFiManager#509]
Probably you already knowabout it, but then the WifiManager change to AP --> STA it doens't close the ESP8266WebServer, so my WebServer (in the main loop) can't restart properly. 

Are you going to fix it?

**Comment by tablatronix** [comment]
What does "change from ap --> sta" mean?

**Comment by fabiuz7** [comment]
I mean the mode of the WiFi: from Access Point mode to Station mode

**Comment by tablatronix** [comment]
But when and where?

**Comment by tablatronix** [comment]
Do you have example, are you testing on development branch ?

**Comment by fabiuz7** [comment]
No, I'm not testing the dev branch, just the official Arduino version.

Assuming that the first connection to WiFi has already taken place,  I have my own Webserver the runs in the main loop. If the network disappear, yuor library is called again to switch in Access Point mode and get the new credentials. The user will put the new credentials. After this, the control flow go back to my main program ( the usual loop), but my WebServer is not going to restart. 

I checked your code and noticed that you never call server->close();  

(Sorry for poor English)

**Comment by tablatronix** [comment]
ok I will look at maybe a hotfix, but there is pretty much NO development or maintenance being done on that version.

**Comment by fabiuz7** [comment]
Ok, I will try the dev version, thanks again!
