### ISSUE TITLE
fix CI travis , add esp32

### ISSUE THREAD

**Issue by tablatronix** [tzapu/WiFiManager#521]
Can someone fix travis in developement branch ?

**Comment by tzapu** [comment]
what's the minimum arduino ide and esp8266 sdk this compiles for now?

cheers

**Comment by tablatronix** [comment]
I have no idea
I would say when they added C++11

**Comment by tzapu** [comment]
just tried with latest stable and arduino 1.8.5 but it fails miserably with this error
```

<command-line>:0:7: error: token "{" is not valid in preprocessor expressions
/home/travis/.arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/core_esp8266_si2c.c:40:5: note: in expansion of macro 'F_CPU'
 #if F_CPU == FCPU80
     ^
/home/travis/.arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/core_esp8266_si2c.c: In function 'twi_setClock':
<command-line>:0:7: error: token "{" is not valid in preprocessor expressions
/home/travis/.arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/core_esp8266_si2c.c:47:5: note: in expansion of macro 'F_CPU'
 #if F_CPU == FCPU80
     ^
exit status 1
```

which i have no idea how to fix

**Comment by tablatronix** [comment]
yeah that makes no sense, ill pole around

**Comment by tablatronix** [comment]
It looks like the compile string is maybe not replacing vars properly

-DF_CPU={build.f_cpu} <-- is it literally defining F_CPU as `{build.f_cpu}` ?

**Comment by tablatronix** [comment]
Can you debug the entire command, see if all boards.txt build.conf are missing ?

**Comment by tzapu** [comment]
something wrong with travis now, won t give out any logs :))

**Comment by tablatronix** [comment]
whats the status on this ?
Did esp32 ever get added also?

**Comment by tablatronix** [comment]
fixed spiffs esp32 examples
7279333a179f13e62b6592701ea36a3d87bee79d

**Comment by tablatronix** [comment]
why the f** is travis failing, what does it mean
this makes no sense, it complains about cpu freq memory, debug level, wtf

```
Error: FlashSize: Invalid option for board "generic"
The command "arduino --board esp8266:esp8266:generic:CrystalFreq=26,FlashFreq=40,FlashMode=qio,FlashSize=4M1M,led=2,LwIPVariant=v2mss536,Debug=Serial,DebugLevel=CORE --save-prefs" exited with 3.
```

**Comment by liebman** [comment]
Looks like that was renamed to 'eesz' in boards.txt in current git version

**Comment by tablatronix** [comment]
```
Error: 40: Invalid option for "eesz" option for board "generic"
The command "arduino --board esp8266:esp8266:generic:xtal=80,CrystalFreq=26,eesz=40,FlashMode=qio,FlashSize=4M1M,led=2,LwIPVariant=v2mss536,Debug=Serial,DebugLevel=CORE --save-prefs" exited with 3.
```

**Comment by tablatronix** [comment]
shrug no idea what the deal is

**Comment by tablatronix** [comment]
https://github.com/esp8266/Arduino/issues/5572

**Comment by tablatronix** [comment]
travis is deprecated
