### ISSUE TITLE
List all stored SSIDs/passwords

### ISSUE THREAD

**Issue by salym8** [tzapu/WiFiManager#552]
Love this library! A great feature is that it can remember multiple SSID and password combos, which has come in handy for me moving between networks. I'd really like to be able to print a list of ALL stored SSIDs and passwords.

I know I can use `WiFi.SSID()` to show the currently connected SSID, but is there some way of accessing all the stored details so I can print to serial, etc? I can't see it in the documentation.

**Comment by tablatronix** [comment]
Wifimanager does not stop multple aps...
