### ISSUE TITLE
Some ideas from another project

### ISSUE THREAD

**Issue by MrBill1234** [tzapu/WiFiManager#57]
Not sure if this uses any of your code (not open source) but it is an interesting project which fits in with tzapu's other temperature logger too.  I like the idea where you long-press a button to go into config mode.

http://www.ebay.co.uk/itm/WiFi-Temperature-and-Humidity-Sensor-module-powered-from-USB-/281902803096?

**Comment by tzapu** [comment]
hi, 
this can be achieved now with the latest changes, there s even an example (with just press, not long press)

just need to write the documentation on it as well :)
cheers

**Comment by tzapu** [comment]
see new readme and examples for button on demand config
