### ISSUE TITLE
option not to start portal on failed autoconnect

### ISSUE THREAD

**Issue by liebman** [tzapu/WiFiManager#574]
Enhancement request.

It would be nice to be able to only start the portal on demand but still use the auto connect logic.  My use case is a battery powered clock and I want to avoid having the portal pop up if no one is around to configure it.  So if auto connect fails I'll just go back to sleep.  If a button is held during reset then I'll open the portal.  Thoughts?

I may throw out a pull request...

**Comment by tablatronix** [comment]
I was about to add this to development
