### ISSUE TITLE
Compile error with core lib 2.3.0

### ISSUE THREAD

**Issue by sidey79** [tzapu/WiFiManager#576]
## Basic Infos

- [x] I have tested that the issue is present in current development branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [ ] I have filled out all fields below.

#### Platform

- Hardware:				[ESP-12]
- Core Version:			[2.3.0]
- Development Env:		[|other Visual Studio 2017 with Visual Micro]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Generic ESP8266 Module]
- Flash Mode:			[dio]
- Flash Size: 		[1MB]
- lwip Variant:             [unknown]
- Reset Method:		[nodemcu]
- Flash Frequency:	       [40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200]

### Problem Description

Detailed problem description goes here.

The server->on function in core release 2.3.0 is declared with variables from type char* and not with variables from type string as they are used by this lib.

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

example sketches are affected

### Debug Messages

```
WiFiManager.cpp: In member function void WiFiManager::setupConfigPortal()
 
WiFiManager.cpp: 388:78: error: no matching function for call to 'ESP8266WebServer::on(String, std::_Bind_helper<false, void (WiFiManager::*)(), WiFiManager* const>::type)
   bind(&WiFiManager::handleRoot, this))
WiFiManager.cpp:388: note  candidates are
 
WiFiManager.h:31: In file included from
WiFiManager.cpp:13: from
ESP8266WebServer.h:79: note  void ESP8266WebServer  on(const char*, ESP8266WebServer  THandlerFunction)
   void on(const char* uri, THandlerFunction handler)
ESP8266WebServer.h:79: note    no known conversion for argument 1 from String to const char*
ESP8266WebServer.h:80: note  void ESP8266WebServer  on(const char*, HTTPMethod, ESP8266WebServer  THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn)
ESP8266WebServer.h:80: note    candidate expects 3 arguments, 2 provided
ESP8266WebServer.h:81: note  void ESP8266WebServer  on(const char*, HTTPMethod, ESP8266WebServer  THandlerFunction, ESP8266WebServer  THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn, THandlerFunction ufn)
ESP8266WebServer.h:81: note    candidate expects 4 arguments, 2 provided```

**Comment by tablatronix** [comment]
Thanks looks like this was changed in 2.4.0
https://github.com/esp8266/Arduino/commit/4dc4e75216dfe21ca1bc0ba4eebc2ec94d7b6be5

**Comment by tablatronix** [comment]
how in the hell does one install 2.3.0 on platformio.hmm

**Comment by sidey79** [comment]
Sorry, no idea.

It's boring, that the upstream lib is changed that way.

**Comment by tablatronix** [comment]
I will see about making this backward compatible, not sure how I can use strings and char* and use flash strings

**Comment by sidey79** [comment]
The only think i see is, that it is possible to detect the lib version via #ifdef ....

Something like this:
`#ifndef ARDUINO_ESP8266_RELEASE_2_3_0`

And depending on the version use seperate code.

Not very well but then it is backward compatible

**Comment by abhitheawesomecoder** [comment]
`Arduino: 1.8.5 (Linux), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 115200, 4M (3M SPIFFS)"

Build options changed, rebuilding all
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp: In member function 'void WiFiManager::setupConfigPortal()':
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:440:78: error: no matching function for call to 'ESP8266WebServer::on(String, std::_Bind_helper<false, void (WiFiManager::*)(), WiFiManager* const>::type)'
   server->on((String)FPSTR(R_root), std::bind(&WiFiManager::handleRoot, this));
                                                                              ^
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:440:78: note: candidates are:
In file included from /home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.h:36:0,
                 from /home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:13:
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note: void ESP8266WebServer::on(const char*, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, THandlerFunction handler);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note:   no known conversion for argument 1 from 'String' to 'const char*'
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note:   candidate expects 3 arguments, 2 provided
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn, THandlerFunction ufn);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note:   candidate expects 4 arguments, 2 provided
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:441:84: error: no matching function for call to 'ESP8266WebServer::on(String, std::_Bind_helper<false, void (WiFiManager::*)(unsigned char), WiFiManager* const, bool>::type)'
   server->on((String)FPSTR(R_wifi), std::bind(&WiFiManager::handleWifi, this, true));
                                                                                    ^
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:441:84: note: candidates are:
In file included from /home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.h:36:0,
                 from /home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:13:
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note: void ESP8266WebServer::on(const char*, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, THandlerFunction handler);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note:   no known conversion for argument 1 from 'String' to 'const char*'
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note:   candidate expects 3 arguments, 2 provided
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn, THandlerFunction ufn);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note:   candidate expects 4 arguments, 2 provided
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:442:91: error: no matching function for call to 'ESP8266WebServer::on(String, std::_Bind_helper<false, void (WiFiManager::*)(unsigned char), WiFiManager* const, bool>::type)'
   server->on((String)FPSTR(R_wifinoscan), std::bind(&WiFiManager::handleWifi, this, false));
                                                                                           ^
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:442:91: note: candidates are:
In file included from /home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.h:36:0,
                 from /home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:13:
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note: void ESP8266WebServer::on(const char*, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, THandlerFunction handler);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note:   no known conversion for argument 1 from 'String' to 'const char*'
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note:   candidate expects 3 arguments, 2 provided
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn, THandlerFunction ufn);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note:   candidate expects 4 arguments, 2 provided
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:443:86: error: no matching function for call to 'ESP8266WebServer::on(String, std::_Bind_helper<false, void (WiFiManager::*)(), WiFiManager* const>::type)'
   server->on((String)FPSTR(R_wifisave), std::bind(&WiFiManager::handleWifiSave, this));
                                                                                      ^
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:443:86: note: candidates are:
In file included from /home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.h:36:0,
                 from /home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:13:
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note: void ESP8266WebServer::on(const char*, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, THandlerFunction handler);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note:   no known conversion for argument 1 from 'String' to 'const char*'
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note:   candidate expects 3 arguments, 2 provided
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn, THandlerFunction ufn);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note:   candidate expects 4 arguments, 2 provided
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:444:78: error: no matching function for call to 'ESP8266WebServer::on(String, std::_Bind_helper<false, void (WiFiManager::*)(), WiFiManager* const>::type)'
   server->on((String)FPSTR(R_info), std::bind(&WiFiManager::handleInfo, this));
                                                                              ^
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:444:78: note: candidates are:
In file included from /home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.h:36:0,
                 from /home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:13:
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note: void ESP8266WebServer::on(const char*, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, THandlerFunction handler);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note:   no known conversion for argument 1 from 'String' to 'const char*'
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note:   candidate expects 3 arguments, 2 provided
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn, THandlerFunction ufn);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note:   candidate expects 4 arguments, 2 provided
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:445:80: error: no matching function for call to 'ESP8266WebServer::on(String, std::_Bind_helper<false, void (WiFiManager::*)(), WiFiManager* const>::type)'
   server->on((String)FPSTR(R_param), std::bind(&WiFiManager::handleParam, this));
                                                                                ^
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:445:80: note: candidates are:
In file included from /home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.h:36:0,
                 from /home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:13:
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note: void ESP8266WebServer::on(const char*, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, THandlerFunction handler);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note:   no known conversion for argument 1 from 'String' to 'const char*'
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note:   candidate expects 3 arguments, 2 provided
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn, THandlerFunction ufn);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note:   candidate expects 4 arguments, 2 provided
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:446:88: error: no matching function for call to 'ESP8266WebServer::on(String, std::_Bind_helper<false, void (WiFiManager::*)(), WiFiManager* const>::type)'
   server->on((String)FPSTR(R_paramsave), std::bind(&WiFiManager::handleParamSave, this));
                                                                                        ^
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:446:88: note: candidates are:
In file included from /home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.h:36:0,
                 from /home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:13:
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note: void ESP8266WebServer::on(const char*, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, THandlerFunction handler);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note:   no known conversion for argument 1 from 'String' to 'const char*'
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note:   candidate expects 3 arguments, 2 provided
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn, THandlerFunction ufn);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note:   candidate expects 4 arguments, 2 provided
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:447:82: error: no matching function for call to 'ESP8266WebServer::on(String, std::_Bind_helper<false, void (WiFiManager::*)(), WiFiManager* const>::type)'
   server->on((String)FPSTR(R_restart), std::bind(&WiFiManager::handleReset, this));
                                                                                  ^
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:447:82: note: candidates are:
In file included from /home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.h:36:0,
                 from /home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:13:
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note: void ESP8266WebServer::on(const char*, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, THandlerFunction handler);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note:   no known conversion for argument 1 from 'String' to 'const char*'
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note:   candidate expects 3 arguments, 2 provided
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn, THandlerFunction ufn);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note:   candidate expects 4 arguments, 2 provided
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:448:78: error: no matching function for call to 'ESP8266WebServer::on(String, std::_Bind_helper<false, void (WiFiManager::*)(), WiFiManager* const>::type)'
   server->on((String)FPSTR(R_exit), std::bind(&WiFiManager::handleExit, this));
                                                                              ^
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:448:78: note: candidates are:
In file included from /home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.h:36:0,
                 from /home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:13:
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note: void ESP8266WebServer::on(const char*, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, THandlerFunction handler);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note:   no known conversion for argument 1 from 'String' to 'const char*'
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note:   candidate expects 3 arguments, 2 provided
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn, THandlerFunction ufn);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note:   candidate expects 4 arguments, 2 provided
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:449:80: error: no matching function for call to 'ESP8266WebServer::on(String, std::_Bind_helper<false, void (WiFiManager::*)(), WiFiManager* const>::type)'
   server->on((String)FPSTR(R_close), std::bind(&WiFiManager::handleClose, this));
                                                                                ^
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:449:80: note: candidates are:
In file included from /home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.h:36:0,
                 from /home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:13:
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note: void ESP8266WebServer::on(const char*, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, THandlerFunction handler);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note:   no known conversion for argument 1 from 'String' to 'const char*'
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note:   candidate expects 3 arguments, 2 provided
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn, THandlerFunction ufn);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note:   candidate expects 4 arguments, 2 provided
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:450:87: error: no matching function for call to 'ESP8266WebServer::on(String, std::_Bind_helper<false, void (WiFiManager::*)(unsigned char), WiFiManager* const, bool>::type)'
   server->on((String)FPSTR(R_erase), std::bind(&WiFiManager::handleErase, this, false));
                                                                                       ^
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:450:87: note: candidates are:
In file included from /home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.h:36:0,
                 from /home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:13:
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note: void ESP8266WebServer::on(const char*, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, THandlerFunction handler);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note:   no known conversion for argument 1 from 'String' to 'const char*'
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note:   candidate expects 3 arguments, 2 provided
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn, THandlerFunction ufn);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note:   candidate expects 4 arguments, 2 provided
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:451:86: error: no matching function for call to 'ESP8266WebServer::on(String, std::_Bind_helper<false, void (WiFiManager::*)(), WiFiManager* const>::type)'
   server->on((String)FPSTR(R_status), std::bind(&WiFiManager::handleWiFiStatus, this));
                                                                                      ^
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:451:86: note: candidates are:
In file included from /home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.h:36:0,
                 from /home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:13:
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note: void ESP8266WebServer::on(const char*, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, THandlerFunction handler);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:79:8: note:   no known conversion for argument 1 from 'String' to 'const char*'
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:80:8: note:   candidate expects 3 arguments, 2 provided
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note: void ESP8266WebServer::on(const char*, HTTPMethod, ESP8266WebServer::THandlerFunction, ESP8266WebServer::THandlerFunction)
   void on(const char* uri, HTTPMethod method, THandlerFunction fn, THandlerFunction ufn);
        ^
/home/abhishek/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:81:8: note:   candidate expects 4 arguments, 2 provided
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp: In member function 'bool WiFiManager::WiFi_scanNetworks(bool, bool)':
/home/abhishek/Arduino/libraries/WiFiManager/WiFiManager.cpp:1001:14: error: 'class ESP8266WiFiClass' has no member named 'scanNetworksAsync'
         WiFi.scanNetworksAsync(std::bind(&WiFiManager::WiFi_scanComplete,this,_1));
              ^
exit status 1
Error compiling for board Generic ESP8266 Module.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

**Comment by tablatronix** [comment]
Yeah the event func was changed in 2.4 and not backward compatible.

**Comment by tablatronix** [comment]
using `server->on(String(FPSTR(R_root)).c_str(),   ` for both compatability

**Comment by bayazidsustami** [comment]
it's not work on my pc

**Comment by tablatronix** [comment]
These changes are only in the development branch at the moment.

**Comment by MEHUL95** [comment]
> using `server->on(String(FPSTR(R_root)).c_str(), ` for both compatability

May I know where to add this line in WifiManager.cpp?

**Comment by tomgillespy** [comment]
@MEHUL95 if you still need this you see where you need to change it by clicking on the commit hash on the left next to the commit that made the change above. I've just amended the file and it works fine now.
