### ISSUE TITLE
SPIFFSReadServer support for page template.

### ISSUE THREAD

**Issue by MiggyMan** [tzapu/WiFiManager#597]
It would be nice to have support for the SPIFFSReadServer library (or similar functionality)  to store the html for the wifi manager in spiffs to make it a little easier to work with!

**Comment by tablatronix** [comment]
But wm doesnt serve static files, I mean css maybe but whats the point of bloating your lib for that

**Comment by MiggyMan** [comment]
Customisation, and the point of using spiffs is to avoid bloat and give more scope for customisation, whacking html in variables is not optimal, or in anyway fun to work on, loading a file from a local filesystem makes it far easier to adapt the page to fit your project as well removing the overhead to have the html stored in program space.

**Comment by tablatronix** [comment]
I still dont get it, its still gonna be html fragments and still going to need a parser and a templating mechanism

**Comment by MiggyMan** [comment]
I'll look into using PersWiFiManager, I much prefer this but hey-ho.

**Comment by tablatronix** [comment]
If you have a more concise proposal about how exactly this is supposed to work, then provide it. Have you checked the development branch?
