### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by lovelesh** [tzapu/WiFiManager#60]
Hi @tzapu,
I am facing some compile errors while testing the code. The error is somewhat like this
error: 'class ESP8266WiFiClass' has no member named 'psk'

I have checked the ESP8266WiFiClass and it doesnot contain and psk member function.
I am on 1.6.5-947-g39819f0 version of esp8266-arduino.

I am working on similar thing and I have used the apboot code as reference. I am adding extra functionality like GPIO toggling for my RGB bulb.

This is my repo
https://github.com/automote/thingSocket/tree/v0.6

**Comment by tzapu** [comment]
hi, as you must have realised because you closed this, you need to be on 2.0.0 or newer for the more recent versions of WiFiManager
cheers

**Comment by lovelesh** [comment]
Sorry for not reading the README. I am waiting for you next release as I
want some other data to be saved in PROGMEM. Can you provide any time
frame. I am currently using EEPROM and I find it unreliable. I am looking
for better approach as I am developing a product that should work for
atleast a year.

Looking forward for your suggestions.

On Fri, Jan 15, 2016 at 2:22 PM tzapu <notifications@github.com> wrote:

> hi, as you must have realised because you closed this, you need to be on
> 2.0.0 or newer for the more recent versions of WiFiManager
> cheers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tzapu/WiFiManager/issues/60#issuecomment-171904569>.
>
-- 
With Regards,
Lovelesh
Indian Institute of Science
Bangalore
+91 8123121274

**Comment by tzapu** [comment]
hi,

you have an example in the current version that saves to file system, in json. seems quite reliable

give it a shot

**Comment by lovelesh** [comment]
Thanks tzapu,

I think this code will perfectly suit my requirements. Is there a way I can
send the config.json file directly in SPIFFS without interfering with the
code. I was thinking of providing 2 files 1) default and 2) regular. Can I
push those into the file system before uploading the code?

On Fri, Jan 15, 2016 at 8:17 PM tzapu <notifications@github.com> wrote:

> hi,
>
> you have an example in the current version that saves to file system, in
> json. seems quite reliable
>
> give it a shot
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tzapu/WiFiManager/issues/60#issuecomment-171979388>.
>
-- 
With Regards,
Lovelesh
Indian Institute of Science
Bangalore
+91 8123121274

**Comment by tzapu** [comment]
i think you can upload files to the esp beforehand, although i never did it
look in the esp8266 for arduino documentation

p.s. the example takes defaults, so it automatically creates a file for you with the defaults after the first use. you don t necessarily need the file beforehand, just set the appropiate defaults

**Comment by lovelesh** [comment]
If I am not able to send the file then I'll settle for automatic file
creation from the code. Right now I'm doing similar thing using global
variables.

On Fri, Jan 15, 2016 at 9:42 PM tzapu <notifications@github.com> wrote:

> i think you can upload files to the esp beforehand, although i never did it
> look in the esp8266 for arduino documentation
>
> p.s. the example takes defaults, so it automatically creates a file for
> you with the defaults after the first use. you don t necessarily need the
> file beforehand, just set the appropiate defaults
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tzapu/WiFiManager/issues/60#issuecomment-172003239>.
>
-- 
With Regards,
Lovelesh
Indian Institute of Science
Bangalore
+91 8123121274

**Comment by tzapu** [comment]
hi,

see here, uploading files

https://github.com/esp8266/Arduino/blob/master/doc/filesystem.md#uploading-files-to-file-system
