### ISSUE TITLE
Unable to start webserver after "Exit". - softAPdisconnect FAILED

### ISSUE THREAD

**Issue by MichMich** [tzapu/WiFiManager#604]
#### Hardware
WiFimanager Branch/Release:  Development

Esp8266/Esp32: ESP32 Wemos Lolin32 OLED

Hardware:			ESP32 Wemos Lolin32 OLED

Core Version:      	Latest.

### Description

Id like to start a webserver after the "Exit" button in the config screen is pressed. In this case I want to run, or keep running the ESP32 in AP mode, and use the softAP mode to allow the user to continue with a direct connection to the ESP.

After I press the Exit button, I can connect to the ESP, but the webserver (WebServer_tng) is unable to start on port 80. When I use port 8080 it works without any issues.

When I check the serial log of WiFi manager, the following is interesting:

```
*WM: <- HTTP Exit
*WM: disconnect configportal
*WM: [ERROR] disconnect configportal - softAPdisconnect FAILED
*WM: config portal exiting
```

As you can see, it gives an error.

### Settings in IDE

Module:  			lolin32

**Comment by tablatronix** [comment]
#545

**Comment by tablatronix** [comment]
can you reproduce with this gist?

**Comment by tablatronix** [comment]
`*WM: [ERROR] disconnect configportal - softAPdisconnect FAILED` 
was fixed in the esp32 lib, you must not be running the latest core

**Comment by MichMich** [comment]
Ah, I'll update to the latest core, and check again. Thanks!
