### ISSUE TITLE
WiFiManger for Linux

### ISSUE THREAD

**Issue by AvishekHardin** [tzapu/WiFiManager#606]
Hello Team,

Good day,

thanks for the marvelous work, you rock!!.. 
I have a question rather than issue. can you please advise if we have a wifi manager for linux?. I'ved search but found nothing. can you please help.

Best Regards,

**Comment by wvdv2002** [comment]
Hi Avishek,
This might be of interest to you:
https://hackaday.com/2018/06/04/deploying-a-turnkey-raspberry-pi-system/

**Comment by AvishekHardin** [comment]
Hello,

Seems the one am looking for actually, really appreciate your help.

Best Regards,
