### ISSUE TITLE
Keep ESP in WIFI_STA mode

### ISSUE THREAD

**Issue by ThePaceMaker** [tzapu/WiFiManager#612]
**Disclaimer: This is more of a question to the forum rather than a issue, so I have a feeling I'm doing this in the wrong place. I do apologise ahead of time. Not sure where else to post it.**

If the wifiManager disconnects from the WiFi due to WiFi failure, it will try to reconnect within the allocated timeout period :

`wifiManager.setTimeout(seconds);`

From what I understand, when it goes into this phase, the ESP is set to WIFI_AP_STA mode. 

https://github.com/tzapu/WiFiManager/blob/b516085a3d0a7c6eb3e720cd423b7999a1e8f85d/WiFiManager.cpp#L201

Is there a way to keep it in WIFI_STA mode and only when the timeout has elapsed, does it move it over to WIFI_AP_STA? 

I have wired code up to a reset button that clears the config and sets it back into config portal mode, should I wish to get to the config portal sooner.

**Comment by DeltaVetal26** [comment]
Hi, maybe this will help you: https://github.com/tzapu/WiFiManager/tree/development#on-demand-configuration-portal Have you looked?

**Comment by ThePaceMaker** [comment]
The problem was in my sketch.  

To verify, the timeout functionality only works with autoConnect during "setup". Once it it has connected and you power cycle the router, the ESP will sit for n amount of time, waiting to reconnect to the last know SSID. Once the router is back up it reconnects (as it should). If you power cycle, the router and the ESP, the timeout trigger then gets hit and sends the ESP to the config portal mode.

But, long story short. I believe the problem was my side.

P.S. I would be nice to have a autoconnect timeout as well.  So after x hours, if it doesn't find the router it sends it to config portal mode.

**Comment by tablatronix** [comment]
Wifimanager does not reconnect the esp does that itself.
