### ISSUE TITLE
esp32 code

### ISSUE THREAD

**Issue by snahmad** [tzapu/WiFiManager#613]
Do we have simple example working on esp32 board. on start up. it shows web page to config wifi access point, host name and restart button after that run different entry point code to run main application written using C/C++

**Comment by tablatronix** [comment]
In development branch
It should work exactly the same , the examples support esp32

**Comment by snahmad** [comment]
Is this all C/C++ code base?

I guess it works on top of ESP32 IDF.

**Comment by tablatronix** [comment]
Its arduino....
