### ISSUE TITLE
Always show SSID & psk on the web page

### ISSUE THREAD

**Issue by dontsovcmc** [tzapu/WiFiManager#617]
### Basic Infos
I don't see SSID and password when I go to configure device second time. 

Its needed when you have additional parameters and want to change them. 

Now you should reinput ssid and password
#### Hardware
WiFimanager Branch/Release:  
master 

Hardware:		NodeMCU 2 ESP-1E

Core Version:      	2.4.0

ide:                          Platformio

### Settings in IDE

Module:  			NodeMcu v2

**Comment by tablatronix** [comment]
They are not overwritten when empty so whats the problem

**Comment by dontsovcmc** [comment]
I need to enter ssid & psk second time.

**Comment by tablatronix** [comment]
What do you mean you need to enter second time ?

**Comment by dontsovcmc** [comment]
When I turn on AP and open 192.168.4.1 second time I see custom parameter values. The SSID and passwork EditBoxes are empty.

**Comment by tablatronix** [comment]
Yeah they are supposed to be. Still do not see the problem here. They are still set just are not shown

**Comment by dontsovcmc** [comment]
"They are still set just are not shown". Oh, I don't know this fact. It's good.
Maybe it's better to show them?

**Comment by tablatronix** [comment]
Maybe try the development version. Password is hidden on purpose still however due to lack of ssl

**Comment by dontsovcmc** [comment]
There is no in release 0.12. Waiting 0.13...

**Comment by tablatronix** [comment]
Why wait, use development branch
