### ISSUE TITLE
Memory leak when reset()-ing DNS server

### ISSUE THREAD

**Issue by brianrho** [tzapu/WiFiManager#619]
In `startConfigPortal()`, after the settings have been saved:

```
server.reset();
dnsServer.reset();
```
I assume the call to `reset()` relies on the existence of a destructor for the DNS server instance but there's none in the [DNSServer](https://github.com/esp8266/Arduino/blob/master/libraries/DNSServer/src/DNSServer.cpp) class. The class makes use of the heap while processing requests and only frees all that memory when `stop()` is called, but that never happens in `WiFiManager` unless I've missed something.

**Comment by tablatronix** [comment]
Hmm i made a note of this in dev branch because I suspected as much as these are smart pointers.

Would this be a bug in dnsserver? I mean it should clean itself up
