### ISSUE TITLE
Static IP when in Station Mode

### ISSUE THREAD

**Issue by jonathanendersby** [tzapu/WiFiManager#62]
Is there any way to specify a static IP when in station mode?

**Comment by tzapu** [comment]
not currently,
on the road map to sort

**Comment by tzapu** [comment]
thanks for the pull request
now added, together with suggested modifications to variables
please test and reopen if problematic

**Comment by josep112** [comment]
Hello after update wifimanager to use wifiManager.setSTAStaticIP Config now appears this error:

/Users/joseantoniosanchez/Documents/Arduino/libraries/WiFiManager-master/WiFiManager.cpp: In member function 'void WiFiManager::handleWifiSave()':
/Users/joseantoniosanchez/Documents/Arduino/libraries/WiFiManager-master/WiFiManager.cpp:462:20: error: 'class IPAddress' has no member named 'fromString'
     _sta_static_ip.fromString(server->arg("ip"));
                    ^
/Users/joseantoniosanchez/Documents/Arduino/libraries/WiFiManager-master/WiFiManager.cpp:467:20: error: 'class IPAddress' has no member named 'fromString'
     _sta_static_gw.fromString(server->arg("gw"));
                    ^
/Users/joseantoniosanchez/Documents/Arduino/libraries/WiFiManager-master/WiFiManager.cpp:472:20: error: 'class IPAddress' has no member named 'fromString'
     _sta_static_sn.fromString(server->arg("sn"));
                    ^
exit status 1
Erro compilando.


Pleas help me

Thanks

**Comment by tzapu** [comment]
hi, you need to run the latest github version of the esp8266 core for arduino ide, until they release a new staging at least
