### ISSUE TITLE
HELP! SET AP Password wrong both in autoConnect() and startConfigPortal()

### ISSUE THREAD

**Issue by ideaChenGo** [tzapu/WiFiManager#624]
SET AP Password wrong both in autoConnect() and startConfigPortal()
char ESPAP_PASSWORD[10] = "pass";  
wifiManager.autoConnect("AutoConnectAP",ESPAP_PASSWORD);

Serial output
*WM: AutoConnect 
*WM: Connecting as wifi client... 
*WM: No saved credentials, skipping wifi 
*WM: Connection result: WL_NO_SSID_AVAIL
*WM: AutoConnect: FAILED 
*WM: AccessPoint set password is INVALID 
#130 has some question

**Comment by tablatronix** [comment]
password must be 8 chars long

**Comment by tablatronix** [comment]
cba606b84697615629040ddeb3c1260e600dfd65
