### ISSUE TITLE
sketch_jun18a:11: error: 'wifiManager' does not name a type

### ISSUE THREAD

**Issue by nufuk** [tzapu/WiFiManager#626]
While trying the example code I get the following error when verifing:

`sketch_jun18a:11: error: 'wifiManager' does not name a type`

But I just literally copy & pasted the example from the README.md

**Comment by tablatronix** [comment]
do you have WiFiManager wifiManager in head?

**Comment by tablatronix** [comment]
Why? Just use the examples included in the library. The readme is probably wrong

**Comment by tablatronix** [comment]
Not sure whats wrong with it, looks fine to me

**Comment by wdmtech** [comment]
It's because you need the other dependencies that aren't listed - not that easy to figure it out as a beginner (unless you go straight to running the examples). 

I'd PR but this project is new to me since this evening so I wouldn't want to touch anything yet!
