### ISSUE TITLE
Variable configuration from Wifi Manager (SSID, Password, IP, GW, Subnet, dns, etc)

### ISSUE THREAD

**Issue by adamrabbani** [tzapu/WiFiManager#634]
Hello @tablatronix 

i want know what variable i will use..
if ESP disconnected from wifi, i want call Wifi.begin with SSID and Password in the **"loop()"**  from
**Variable Configuration in WifiManager.**. and other variable like (IP, GW, Subnet, dns, etc)

Thanks

**Comment by tablatronix** [comment]
You just call begin this is esp8266 related not wifimanager

**Comment by adamrabbani** [comment]
@tablatronix 
just call WiFi.begin()? without variable? 
because if ESP accidentally disconnect from WiFi, i want using setting configuration from wifimanager.. 
i dont want reset the ESP and configuration again... 
Thanks

**Comment by tablatronix** [comment]
They are one in the same

**Comment by tablatronix** [comment]
Esp automatically reconnects to wifi on its own

**Comment by adamrabbani** [comment]
@tablatronix 
Thank you for clarifying that.
