### ISSUE TITLE
connected to esp8266 network but could not open config portal??

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [tzapu/WiFiManager#641]
I am using Nodemcu.

Autoconnect("appp").

It  creates a network.  But when I connect to it sometimes I am not able to open config portal. Then I need to restart Nodemcu.

I am using the latest version of WifiManager.

**Comment by a-c-sreedhar-reddy** [comment]
I commented captive portal stuff in the library and I feel it is working fine then.

**Comment by tablatronix** [comment]
captive portal was breaking your connection?

**Comment by a-c-sreedhar-reddy** [comment]
Even after disabling captive portal I could not open 192.168.4.1 
Then I need to restart my board ( NODEMCU , esp01)

**Comment by a-c-sreedhar-reddy** [comment]
[ SOLVED ]
In the  startConfigPortal function I changed the Wifi mode from AP_STA to AP.  
It worked..
:-)

**Comment by tablatronix** [comment]
Yeah this is fixed in hotfixes branch
