### ISSUE TITLE
Using POST instead of GET

### ISSUE THREAD

**Issue by smixd** [tzapu/WiFiManager#66]
First of all: Nice Project! Everyone who starts a Project with the ESP8266 needs this lib! :)

Just a small change:
If you use a Password-Field in the HTML to hide the Password chars,
it also makes sense to use POST in the Form-Method?!
At the Moment the "p" Argument is shown in plaintext in the url, wenn you click save...

**Comment by tzapu** [comment]
it would make sense, will see about it

cheers

**Comment by yomasa** [comment]
please don't do this. I like seeing the password.

**Comment by tzapu** [comment]
i guess it could be a flag to switch between get and post...
it just seems too much hassle currently, so will leave this for later

**Comment by javl** [comment]
@yomasa Do you mean you don't want to hide the password in the input field, or don't want to use POST? See discussion in #129

**Comment by dontsovcmc** [comment]
@tablatronix  close, it solved
