### ISSUE TITLE
error: 'WM_COUNTRY_US was not declared in this scope

### ISSUE THREAD

**Issue by d2f** [tzapu/WiFiManager#673]
####Hardware:
WiFimanager Branch/Release:  Development
Esp8266/Esp32: 
Hardware:		heltec_wifi_lora_32
Core Version:      	2.4.0, staging
####Description:
.piolibdeps/WifiManager/WiFiManager.cpp:2343:61: error: 'WM_COUNTRY_US' was not declared in this scope

```
Fixed by:
strings_en.h:322
#ifdef ESP32
...
...
#endif
```

**Comment by tablatronix** [comment]
Oops I had it lowercase
