### ISSUE TITLE
custom html parameters

### ISSUE THREAD

**Issue by Laserlicht** [tzapu/WiFiManager#678]
#### Hardware
WiFimanager Branch/Release:  Development

Esp8266/Esp32: 

Hardware:			ESP32

Core Version:      	staging

### Description

Bug in develop branch: custom html parameters aren't possible.
They aren't visible on page.

For example:
```
WiFiManagerParameter custom_text("<p>This is just a text paragraph</p>");
wifiManager.addParameter(&custom_text);
```

### Sketch
I have to comment out the following lines to solve the problem (WiFiManager.cpp).
Custom-HTML-Parameter don't have an ID.

```
  /*if(p->getID()){
    for (size_t i = 0; i < strlen(p->getID()); i++){
       if(!(isAlphaNumeric(p->getID()[i])) && !(p->getID()[i]=='_')){
        DEBUG_WM(DEBUG_ERROR,"[ERROR] parameter IDs can only contain alpha numeric chars");
        return false;
       }
    }
  }*/
```

```
      /*if (_params[i] == NULL || _params[i]->_length == 0) {
        DEBUG_WM(DEBUG_ERROR,"[ERROR] WiFiManagerParameter is out of scope");
        break;
      }*/
```

**Comment by tablatronix** [comment]
I didnt even realize you could do this, I thought that was a constructor doh
