### ISSUE TITLE
Two small problems

### ISSUE THREAD

**Issue by Mohammed-Kher-Ali** [tzapu/WiFiManager#684]
![screenshot_20180803-151035](https://user-images.githubusercontent.com/35557583/43643933-8d1552d6-9735-11e8-90a8-da3d4400998e.jpg)

1-The top line disappears in the text input box. How can I format this better
2-After a power outage the router needs the Internet about 30 seconds to a minute until the Internet starts broadcasting
While ESP8266 works directly and starts searching for the previous network if it does not exist, it does a reset
Can you delay this by searching for a network for a minute if it does not do a reset? No problem

**Comment by tablatronix** [comment]
setconnecttimeout

**Comment by Mohammed-Kher-Ali** [comment]
i have fixed .issue 1
Keep adding "setconnecttimeout

" to my code

```

#define BLYNK_PRINT Serial

#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>
#include <DNSServer.h>
#include <ESP8266WebServer.h>
#include <WiFiManager.h>          //https://github.com/tzapu/WiFiManager
#include <EEPROM.h>
#include <WidgetRTC.h>

WidgetRTC rtc;
BlynkTimer Time;









    WiFiManager wifiManager;
    WiFiClient wifiClient;


#define EEPROM_SALT 12664
typedef struct
  {
  int   salt = EEPROM_SALT;
  char Blynk_Token[33]  = "";
  char Device_Name[20]  = "Smart Mini Relay";
  char Widgets_Color[8]  = "#23C48E";
  char Pass_Setting[9]  = "12345";
  }

WMSettings;
WMSettings blynk;
WMSettings device;
WMSettings color;
WMSettings pass;

void eeprom_read()
  {
  EEPROM.begin(512);
  EEPROM.get(0, blynk);
  EEPROM.get(100, device);
  EEPROM.get(200, color);
  EEPROM.get(300, pass);
  EEPROM.end();
  }


void eeprom_saveconfig()
  {
  EEPROM.begin(512);
  EEPROM.put(0, blynk);
  EEPROM.put(100, device);
  EEPROM.put(200, color);
  EEPROM.put(300, pass);
  EEPROM.commit();
  EEPROM.end();
  }


/*********************************************************************************/

void configModeCallback (WiFiManager *myWiFiManager)
  {
  String ssid =  device.Device_Name;
  }




void setup()
  {
  Serial.begin(115200);
  pinMode(Relay, OUTPUT);

 


  eeprom_read();

  if (blynk.salt != EEPROM_SALT)
    {
    Serial.println("Invalid settings in EEPROM, trying with defaults");
    WMSettings defaults;
    blynk = defaults;
    device = defaults;
    color = defaults;
    pass = defaults;
    }


  String ssid =  device.Device_Name;
  WiFi.hostname(ssid);

  
  WiFiManagerParameter custom_blynk_text("Device ID");
  wifiManager.addParameter(&custom_blynk_text);


  WiFiManagerParameter custom_blynk_token("blynk-token", "Blynk Token", blynk.Blynk_Token, 33);
  wifiManager.addParameter(&custom_blynk_token);

  WiFiManagerParameter custom_text("<p>This is just a text paragraph</p>");
wifiManager.addParameter(&custom_text);

  WiFiManagerParameter custom_device_text("Device Name");
  wifiManager.addParameter(&custom_device_text);

  WiFiManagerParameter custom_device_token("device-token", "Device Name",  device.Device_Name, 20);
  wifiManager.addParameter(&custom_device_token);


  WiFiManagerParameter custom_color_text("Widget Color");
  wifiManager.addParameter(&custom_color_text);

  WiFiManagerParameter custom_color_token("color-token", "Hex Color eg.#FF0000 = Red color", color.Widgets_Color, 8);
  wifiManager.addParameter(&custom_color_token);



  WiFiManagerParameter custom_pass_text("Lock settings");
  wifiManager.addParameter(&custom_pass_text);

  WiFiManagerParameter custom_pass_token("pass-token", "eg.123Abc", pass.Pass_Setting, 9);
  wifiManager.addParameter(&custom_pass_token);

  if (!wifiManager.autoConnect(ssid.c_str(), NULL)) 
    {
    Serial.println("failed to connect, we should reset and see if it connects");
    delay(6000);
    WiFi.disconnect();
    wifiManager.resetSettings();
    ESP.reset();   
    }

  strcpy(blynk.Blynk_Token, custom_blynk_token.getValue());
  strcpy(device.Device_Name, custom_device_token.getValue());
  strcpy(color.Widgets_Color, custom_color_token.getValue());
  strcpy(pass.Pass_Setting, custom_pass_token.getValue());
 
  eeprom_saveconfig();
  
  
  Blynk.config(blynk.Blynk_Token);
  bool result = Blynk.connect();
  delay(1000);

  if (result != true)
    {
    Blynk.config(blynk.Blynk_Token);
    Serial.println("BLYNK Connection Fail");
    delay(1000);
    wifiManager.resetSettings();
    ESP.reset();
    }
  else
    {
    Serial.println("BLYNK Connected");

    }

  }




void loop()
  {
  Blynk.run();
  Time.run();
  }

```

**Comment by rodri16** [comment]
How did you solve problem 1?

**Comment by Mohammed-Kher-Ali** [comment]
![screenshot_20180808-194517](https://user-images.githubusercontent.com/35557583/43851611-d106b05e-9b43-11e8-8c64-c8d2a3a81c60.jpg)
![screenshot_20180808-194451](https://user-images.githubusercontent.com/35557583/43851612-d12b923e-9b43-11e8-9e05-6cbbe8b341d9.png)


I'll post the edit when you're finished

**Comment by rodri16** [comment]
Did you change only strings_en.h or something else?

**Comment by Mohammed-Kher-Ali** [comment]
It is not connected to the Internet in this case so I think it is difficult to add a picture

**Comment by mikekgr** [comment]
Dear @Mohammed-Kher-Ali 
do you have the above code but full, somewhere published ? GitHub perhaps?
If yes, can you share the URL?
Thanks

**Comment by Mohammed-Kher-Ali** [comment]
Icon I modified it
Editing not yet finished
Modified for style only
I'll post it when you're finished

**Comment by tablatronix** [comment]
you can customize the menu but not add stuff, unless you edit the strings file manually,

You can add whatever you want, mohammed seems to be still using the master branch.


The development branch even support invert dark theme

**Comment by Mohammed-Kher-Ali** [comment]
#https://github.com/Mohammed-Kher-Ali/WiFi-Manager

![1](https://user-images.githubusercontent.com/35557583/44086861-a92a1684-9fc6-11e8-8c27-c814662ace90.jpg)
![2](https://user-images.githubusercontent.com/35557583/44086869-b0820c52-9fc6-11e8-9531-354c3d3b7171.jpg)
![3](https://user-images.githubusercontent.com/35557583/44086883-b97e4b90-9fc6-11e8-9fe9-d7f31e3a41b0.jpg)
![4](https://user-images.githubusercontent.com/35557583/44086891-bfdf3238-9fc6-11e8-8ffb-4326010360f2.jpg)
![5](https://user-images.githubusercontent.com/35557583/44086898-c280b354-9fc6-11e8-9aa9-3a66b6cddd25.jpg)
![6](https://user-images.githubusercontent.com/35557583/44086905-c6422270-9fc6-11e8-8cc2-ba1d455ed272.jpg)
![7](https://user-images.githubusercontent.com/35557583/44086912-c8a396e8-9fc6-11e8-9c75-d17110cdefa7.jpg)

**Comment by tzapu** [comment]
that looks cool :D
