### ISSUE TITLE
How to block the Automatic Pop-up for "Sign-in to WiFi"

### ISSUE THREAD

**Issue by abhaysbharadwaj** [tzapu/WiFiManager#694]
Hello,
I know this is a strange question, but I want to know how to disable the "Sign in to WiFi" pop-up when I use this library.

I am creating an App (Android and iPhone) in which I wish to do the configurations. Most of the things are working as all I need to do is pass the SSID and Passwords appended to the URL. It's working fine.

The main issue is that I want to disable the pop-up and captive portal and use the app to do the configurations. Can anyone help me out? Thanks and regards.

**Comment by tablatronix** [comment]
```cpp
    //if false, disable captive portal redirection
    void          setCaptivePortalEnable(boolean enabled);
```
development branch
