### ISSUE TITLE
Adding extra parameters is not wotking in the WiFiManager-development part

### ISSUE THREAD

**Issue by pvdw0310** [tzapu/WiFiManager#699]
Hi, 
I'm new to the WiFiManager project and I was testing it for a while, now I like to use the examples of the WiFiManager-development lib. But adding some extra parameters is not working? At least I don't find them on the config site at 192.168.4.1 . Using a esp8266f and arduino ide 1.8.5
Thanks

**Comment by liebman** [comment]
Its probably this https://github.com/tzapu/WiFiManager/pull/681

**Comment by tablatronix** [comment]
Which example, they are a bit of a mess right now. The fsparameters ones should work though

**Comment by pvdw0310** [comment]
I'm using the example advanced.ino that comes with the lib.

**Comment by tablatronix** [comment]
That is probably broken

**Comment by pvdw0310** [comment]
is there a way to fix it ?

**Comment by tablatronix** [comment]
dont use that example until I test it maybe

**Comment by tablatronix** [comment]
oh that example actually save anything it just implements custom params, you have to handle the saving, the autoconnectwithfsparameters examples should work and actually save to spiffs

**Comment by pvdw0310** [comment]
Thanks for the reaction, but I understand that I have to handle the saving to spiffs. But,  before that I need a way to enter the params. And that's the problem. I can't enter the params.  If you declare the params in the program they don't show up on the website during the setup.

**Comment by tablatronix** [comment]
Works for me

AutoConnectWithFSParameters

![screen shot 2018-08-18 at 4 51 05 pm](https://user-images.githubusercontent.com/807787/44303451-faf08c80-a306-11e8-9994-867e2ae861b5.png)

**Comment by pvdw0310** [comment]
oeps, strange. I have a look to that program. I only use the advance.ino

**Comment by tablatronix** [comment]
works fine, params under setup

![screen shot 2018-08-19 at 8 42 22 am](https://user-images.githubusercontent.com/807787/44309415-d38fd300-a38b-11e8-98e3-8701ecdd31cf.png)

**Comment by tablatronix** [comment]
works for me
![screen shot 2018-08-23 at 9 59 28 am 2](https://user-images.githubusercontent.com/807787/44533510-4adea300-a6bb-11e8-8117-1a715c9bb8a6.png)

**Comment by diegoalbaga** [comment]
now im having this same problem, when i use the master branch the parameters declared in the code show but when i use the development branch they dont, i think the onl way to use them is is editing in the strings file in the param form but i dont know if they will actually save in fs using the code functions

**Comment by martinberlin** [comment]
Works for me too in development branch.
What does not work is the setSaveConfigCallback() for me so I didn't find a way to store this extra parameters in the EEPROM. There was an issue but is closed: https://github.com/tzapu/WiFiManager/issues/714

Can you please indicate me how to do it ? ( I tried all examples I found, but I never get the Serial comment that is on the Callback function after pressing SAVE )

**Comment by martinberlin** [comment]
Maybe it's my fault ?  I've tested yesterday making a git pull from your development branch.
Just as a reference this is my sketch: https://github.com/martinberlin/esp/blob/master/FasarekCam-WiFi-Settings/FasarekCam-WiFi-Settings.ino 
I'm just doing:
  wm.setAPCallback(configModeCallback);  -> This is called perfectly
  wm.setSaveConfigCallback(saveConfigCallback);  --> this one is not

All the rest works perfectly I'm very happy with WifiManager, seriously I'm putting it in everything I make!

**Comment by tablatronix** [comment]
Did you get the callback working?

**Comment by martinberlin** [comment]
No. I checked and made a git pull on the development branch. But I couldn't get it to work.

Happy that for Diego works the other stuff. I'm growing white hair ;)

**Comment by tablatronix** [comment]
gonna test now, gimme a few

**Comment by tablatronix** [comment]
ok yeah it looks like if you are not submitting an ssid and setBreakAfterConfig is false then it does not get called.

if you setBreakAfterConfig(true) is should work, I will see how this should properly work.

I think I have to just go ahead and add a paramsave callback, its on the list

**Comment by tablatronix** [comment]
yeah i also added a `setSaveParamsCallback`

**Comment by Behzad-6-1** [comment]
Hi I am new on this and tried to use wifiManager.addParameter
it seems if I add the 4th parameter it breaks the code and it goes in to endless loop and print table of hex code

**Comment by Behzad-6-1** [comment]
can the limit be set in .h file
`
#ifndef WIFI_MANAGER_MAX_PARAMS
    #define WIFI_MANAGER_MAX_PARAMS 6 // params will autoincrement and realloc by this amount when max is reached
#endif`

**Comment by tablatronix** [comment]
@Behzad-6-1  create a new issue , do not post on old ones

**Comment by Behzad-6-1** [comment]
this was open so I thought I it is ok sorry
I have now created new one wifiManager.addParameter not working or 6 parameter

would you be able to have a look at it please
