### ISSUE TITLE
wm default ap name does not match esp default ap

### ISSUE THREAD

**Issue by tablatronix** [tzapu/WiFiManager#707]
I was testing the other day and I noticed that the default ap did not match the generated wm one from chip id. It was a bit odd.

try to reproduce , I have a screenshot somewhere

**Comment by Kadah** [comment]
Do you mean this?
https://i.imgur.com/T7yBhBA.png

Testing using OnDemandConfigPortal.ino. Screenshot was of an ESP8266 (ESP-12F) after rebooting, but I got the same but different SSID on an ESP32 Thing.

**Comment by tablatronix** [comment]
Yeah the one the chip generates it different that the one wm generates when no ssid is provided

**Comment by tablatronix** [comment]
Will have to test esp32 and see if this fix covers that as well

**Comment by tablatronix** [comment]
esp32

```
  // AP esp_267751
  // ESP32 Chip ID = 507726A4AE30
```

**Comment by tablatronix** [comment]
- [ ] fix esp chipid
