### ISSUE TITLE
blank wifi credentials aren't handled correctly in connectWifi

### ISSUE THREAD

**Issue by andysc** [tzapu/WiFiManager#708]
If you erase the wifi credentials and start WiFiManager, it says
```
Using last saved values, should be faster
```
whereas it should say
```
No saved credentials
```
and go straight into config portal mode.

It looks like 
```    if (WiFi.SSID()) {```
isn't correctly evaluating an empty SSID.

**Comment by tablatronix** [comment]
You didnt fill out any information

**Comment by andysc** [comment]
sorry... WM 0.14.0
ESP core 2.4.2
running on a  Wemos ESP8266

line 294 of WiFiManager.cpp
erase wifi credentials using the option in Arduino IDE (Erase sketch and WiFi settings)

(I found it while we were playing with #702, but I thought I'd raise it separately :))

**Comment by tablatronix** [comment]
master branch ?

**Comment by andysc** [comment]
yes
