### ISSUE TITLE
Security help wanted

### ISSUE THREAD

**Issue by dmalham** [tzapu/WiFiManager#713]
This is a nice bit of code but one thing I don’t like is that after you have saved the WiFi credentials from the AP web page. the browser address of the new page includes both the SSID and the password in plain. This, I think, is a security hole as it stays in the browser history of the device you use to connect to the AP unless, of course, you clear the history or use the private browsing option. Not very idiot proof! Can anyone reassure me or come up with a fix I can use?

   Dave

**Comment by tablatronix** [comment]
change GET to POST in the form see development branch

**Comment by dmalham** [comment]
Thanks! That does the trick

    Dave
