### ISSUE TITLE
Feature proposal: being able to iterate on WifiManagerParameters

### ISSUE THREAD

**Issue by fllaca** [tzapu/WiFiManager#717]
I think iterating on WifiManagerParameters could be interesting, in order to make easier the creation of reusable configuration forms, so you could do something like:

```C++
JsonObject& json = ...
....
for (int i=0; i<wifimanager.getParametersCount(); i++){
    WiFiManagerParameter parameter = wifimanager.getParameters()[i];
    json[parameter.getId()] = parameter.getValue();
}

// then save the jsonfile into a file
persistJsontoFS(json);
```

WDYT?

**Comment by tablatronix** [comment]
Hmm makes sense

**Comment by JeremyProffitt** [comment]
I worry about json parsing and device memory, was looking at one file per perameter model myself.  Name the file o/<paramname>
