### ISSUE TITLE
IMPROVEMENT: Allow callback or some other method when entering auto connect

### ISSUE THREAD

**Issue by Foozinator** [tzapu/WiFiManager#752]
I'm working with an ESP8266 that has a small built-in OLED display.  I'd like to show the SSID and IP of the unit when it enters the AP-mode for connection input.  That way, I could just provide power to a "new" unit and not have to get a serial monitor to see what SSID + IP was used.

It looks like that might be simple enough to do if a callback was available for "about to enter AP-mode".

**Comment by tablatronix** [comment]
#452

**Comment by tablatronix** [comment]
```
    //called when AP mode and config portal is started
    void          setAPCallback( std::function<void(WiFiManager*)> func );
```

**Comment by tablatronix** [comment]
It looks like that gets fired BEFORE starting the ap..

hmm

**Comment by tablatronix** [comment]
I moved it after softap() in development branch

Should not break anything and allow what you want.

**Comment by tablatronix** [comment]
1d0970a882b84d8840eb597785aae52e5c688605

**Comment by tablatronix** [comment]
👊  Possible Breaking Change!

**Comment by tablatronix** [comment]
Noone has complained... closing
