### ISSUE TITLE
Not compatible with esp32?

### ISSUE THREAD

**Issue by moijerem59** [tzapu/WiFiManager#754]
Arduino : 1.9.0-beta (Windows 10), Carte : "ESP32 Dev Module, Disabled, Minimal SPIFFS (Large APPS with OTA), QIO, 80MHz, 4MB (32Mb), 921600, None"

ATTENTION : la bibliothèque ESP32WebServer-master prétend être exécutable sur la (ou les) architecture(s) (ESP32) et peut être incompatible avec votre carte actuelle qui s'exécute sur (esp32).
In file included from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master/WiFiManager.h:21:0,

                 from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master\examples\AutoConnect\AutoConnect.ino:14:

C:\Users\Lenovo\Documents\Arduino\libraries\ESP32WebServer-master\src/ESP32WebServer.h:30:6: error: using typedef-name 'HTTPMethod' after 'enum'

 enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };

      ^

In file included from C:\Users\Lenovo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\WebServer\src/WebServer.h:30:0,

                 from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master\examples\AutoConnect\AutoConnect.ino:12:

C:\Users\Lenovo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\WebServer\src/HTTP_Method.h:13:3: note: 'HTTPMethod' has a previous declaration here

 } HTTPMethod;

   ^

In file included from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master/WiFiManager.h:21:0,

                 from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master\examples\AutoConnect\AutoConnect.ino:14:

C:\Users\Lenovo\Documents\Arduino\libraries\ESP32WebServer-master\src/ESP32WebServer.h:30:19: error: redeclaration of 'HTTP_ANY'

 enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };

                   ^

In file included from C:\Users\Lenovo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\WebServer\src/WebServer.h:30:0,

                 from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master\examples\AutoConnect\AutoConnect.ino:12:

C:\Users\Lenovo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\WebServer\src/HTTP_Method.h:12:3: note: previous declaration 'HTTPMethod HTTP_ANY'

   HTTP_ANY     = 0b01111111,

   ^

In file included from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master/WiFiManager.h:21:0,

                 from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master\examples\AutoConnect\AutoConnect.ino:14:

C:\Users\Lenovo\Documents\Arduino\libraries\ESP32WebServer-master\src/ESP32WebServer.h:30:29: error: redeclaration of 'HTTP_GET'

 enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };

                             ^

In file included from C:\Users\Lenovo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\WebServer\src/WebServer.h:30:0,

                 from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master\examples\AutoConnect\AutoConnect.ino:12:

C:\Users\Lenovo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\WebServer\src/HTTP_Method.h:5:3: note: previous declaration 'HTTPMethod HTTP_GET'

   HTTP_GET     = 0b00000001,

   ^

In file included from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master/WiFiManager.h:21:0,

                 from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master\examples\AutoConnect\AutoConnect.ino:14:

C:\Users\Lenovo\Documents\Arduino\libraries\ESP32WebServer-master\src/ESP32WebServer.h:30:39: error: redeclaration of 'HTTP_POST'

 enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };

                                       ^

In file included from C:\Users\Lenovo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\WebServer\src/WebServer.h:30:0,

                 from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master\examples\AutoConnect\AutoConnect.ino:12:

C:\Users\Lenovo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\WebServer\src/HTTP_Method.h:6:3: note: previous declaration 'HTTPMethod HTTP_POST'

   HTTP_POST    = 0b00000010,

   ^

In file included from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master/WiFiManager.h:21:0,

                 from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master\examples\AutoConnect\AutoConnect.ino:14:

C:\Users\Lenovo\Documents\Arduino\libraries\ESP32WebServer-master\src/ESP32WebServer.h:30:50: error: redeclaration of 'HTTP_PUT'

 enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };

                                                  ^

In file included from C:\Users\Lenovo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\WebServer\src/WebServer.h:30:0,

                 from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master\examples\AutoConnect\AutoConnect.ino:12:

C:\Users\Lenovo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\WebServer\src/HTTP_Method.h:8:3: note: previous declaration 'HTTPMethod HTTP_PUT'

   HTTP_PUT     = 0b00001000,

   ^

In file included from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master/WiFiManager.h:21:0,

                 from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master\examples\AutoConnect\AutoConnect.ino:14:

C:\Users\Lenovo\Documents\Arduino\libraries\ESP32WebServer-master\src/ESP32WebServer.h:30:60: error: redeclaration of 'HTTP_PATCH'

 enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };

                                                            ^

In file included from C:\Users\Lenovo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\WebServer\src/WebServer.h:30:0,

                 from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master\examples\AutoConnect\AutoConnect.ino:12:

C:\Users\Lenovo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\WebServer\src/HTTP_Method.h:9:3: note: previous declaration 'HTTPMethod HTTP_PATCH'

   HTTP_PATCH   = 0b00010000,

   ^

In file included from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master/WiFiManager.h:21:0,

                 from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master\examples\AutoConnect\AutoConnect.ino:14:

C:\Users\Lenovo\Documents\Arduino\libraries\ESP32WebServer-master\src/ESP32WebServer.h:30:72: error: redeclaration of 'HTTP_DELETE'

 enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };

                                                                        ^

In file included from C:\Users\Lenovo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\WebServer\src/WebServer.h:30:0,

                 from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master\examples\AutoConnect\AutoConnect.ino:12:

C:\Users\Lenovo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\WebServer\src/HTTP_Method.h:7:3: note: previous declaration 'HTTPMethod HTTP_DELETE'

   HTTP_DELETE  = 0b00000100,

   ^

In file included from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master/WiFiManager.h:21:0,

                 from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master\examples\AutoConnect\AutoConnect.ino:14:

C:\Users\Lenovo\Documents\Arduino\libraries\ESP32WebServer-master\src/ESP32WebServer.h:30:85: error: redeclaration of 'HTTP_OPTIONS'

 enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };

                                                                                     ^

In file included from C:\Users\Lenovo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\WebServer\src/WebServer.h:30:0,

                 from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master\examples\AutoConnect\AutoConnect.ino:12:

C:\Users\Lenovo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\WebServer\src/HTTP_Method.h:11:3: note: previous declaration 'HTTPMethod HTTP_OPTIONS'

   HTTP_OPTIONS = 0b01000000,

   ^

In file included from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master/WiFiManager.h:21:0,

                 from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master\examples\AutoConnect\AutoConnect.ino:14:

C:\Users\Lenovo\Documents\Arduino\libraries\ESP32WebServer-master\src/ESP32WebServer.h:31:6: error: multiple definition of 'enum HTTPUploadStatus'

 enum HTTPUploadStatus { UPLOAD_FILE_START, UPLOAD_FILE_WRITE, UPLOAD_FILE_END,

      ^

In file included from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master\examples\AutoConnect\AutoConnect.ino:12:0:

C:\Users\Lenovo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\WebServer\src/WebServer.h:32:6: note: previous definition here

 enum HTTPUploadStatus { UPLOAD_FILE_START, UPLOAD_FILE_WRITE, UPLOAD_FILE_END,

      ^

In file included from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master/WiFiManager.h:21:0,

                 from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master\examples\AutoConnect\AutoConnect.ino:14:

C:\Users\Lenovo\Documents\Arduino\libraries\ESP32WebServer-master\src/ESP32WebServer.h:33:6: error: multiple definition of 'enum HTTPClientStatus'

 enum HTTPClientStatus { HC_NONE, HC_WAIT_READ, HC_WAIT_CLOSE };

      ^

In file included from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master\examples\AutoConnect\AutoConnect.ino:12:0:

C:\Users\Lenovo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\WebServer\src/WebServer.h:34:6: note: previous definition here

 enum HTTPClientStatus { HC_NONE, HC_WAIT_READ, HC_WAIT_CLOSE };

      ^

In file included from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master/WiFiManager.h:21:0,

                 from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master\examples\AutoConnect\AutoConnect.ino:14:

C:\Users\Lenovo\Documents\Arduino\libraries\ESP32WebServer-master\src/ESP32WebServer.h:55:3: error: conflicting declaration 'typedef struct HTTPUpload HTTPUpload'

 } HTTPUpload;

   ^

In file included from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master\examples\AutoConnect\AutoConnect.ino:12:0:

C:\Users\Lenovo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\WebServer\src/WebServer.h:61:3: note: previous declaration as 'typedef struct HTTPUpload HTTPUpload'

 } HTTPUpload;

   ^

In file included from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master\examples\AutoConnect\AutoConnect.ino:14:0:

C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master/WiFiManager.h:36:22: error: 'const char HTTP_HEAD []' redeclared as different kind of symbol

 const char HTTP_HEAD[] PROGMEM            = "<!DOCTYPE html><html lang=\"en\"><head><meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\"/><title>{v}</title>";

                      ^

In file included from C:\Users\Lenovo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\WebServer\src/WebServer.h:30:0,

                 from C:\Users\Lenovo\Documents\Arduino\libraries\WIFIMANAGER-ESP32-master\examples\AutoConnect\AutoConnect.ino:12:

C:\Users\Lenovo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\WebServer\src/HTTP_Method.h:10:3: note: previous declaration 'HTTPMethod HTTP_HEAD'

   HTTP_HEAD    = 0b00100000,

   ^

exit status 1
Erreur de compilation pour la carte ESP32 Dev Module

Ce rapport pourrait être plus détaillé avec
l'option "Afficher les résultats détaillés de la compilation"
activée dans Fichier -> Préférences.

link webserver 
https://github.com/Pedroalbuquerque/ESP32WebServer

**Comment by tablatronix** [comment]
You didnt fill out any information...

**Comment by martinberlin** [comment]
I can confirm that development branch works perfectly on ESP-32 (Using now Heltec model Makerfocus 32)
