### ISSUE TITLE
Testing ota branch 

### ISSUE THREAD

**Issue by martinberlin** [tzapu/WiFiManager#767]
So far is a bit confusing. 

Scenario
Updated Wifi Manager to ota branch
/Arduino/libraries/WiFiManager$ git status
On branch ota
Your branch is up to date with 'origin/ota'

In my sketch : Added the "update" option to menu vector.

**What is expected to happen**
That update option appears when WiFi manager captive portal starts

**What is happening**
![options](https://user-images.githubusercontent.com/2692928/48657565-fdac6c00-ea32-11e8-9646-09f5b3e5f5a4.png)
A new Erase option appears (But I didn't add erase to the menu array) 
Note: My comment on the image is wrong, Erase option appears automatically, has nothing to do with adding the additional "update" option to the menu

No update option appears. If I go to info, I see there is a /u Route, clicking on it I get:
File Not Found

URI: /u
Method: GET
Arguments: 0

Can you please explain in a short note how to test this ?
Thanks in advance

UPDATE: Now I see this https://github.com/tzapu/WiFiManager/commit/0ec7a58b7b0888a1ef261b38694f7a9e5633773e
I will try again later and update this. But still don't get fully how it should work.
Maybe you can provide a working demo in your /examples Folder ?

**Comment by tablatronix** [comment]
what is your menu code?

**Comment by martinberlin** [comment]
Is the same as you can see in the develop branch of the FS2 project. I copied it from your example if I remember well.

**Comment by tablatronix** [comment]
I dont see any menu code in develop, did you push it?

**Comment by martinberlin** [comment]
Good morning Shawn, 
Just added a feature/ota branch and added "update" in the menu:

https://github.com/martinberlin/FS2/commit/a8bf7ec6d7a8993c588d38e57efe0b51116fe514

**Comment by tablatronix** [comment]
Fixed thanks!

**Comment by martinberlin** [comment]
Works fantastic, thanks!!!

**Comment by rodri16** [comment]
Hi, I am also testing OTA branch and when trying to upload a code I get an error, it says
```
*WM: [3] -> 192.168.4.1 
Update: Blink.ino
sleep disable
*WM: [3] -> 192.168.4.1 
.*WM: [3] -> 192.168.4.1 
ERROR[10]: Magic byte is wrong, not 0xE9
*WM: [2] <- Handle update don
```

**Comment by tablatronix** [comment]
Ill take a look and merge in updates

**Comment by tablatronix** [comment]
Did you check esp lib for this error?

**Comment by rodri16** [comment]
I made it work sorry, it was a wrong file!!! I was trying tih .ino file and I have to use .bin
```
 *WM: [3] -> 192.168.4.1 
Update: Blink.ino.d1_mini.bin
sleep disable
*WM: [3] -> 192.168.4.1 
.*WM: [3] -> 192.168.4.1 
Updated: 261824 bytes
Rebooting...
*WM: [2] <- Handle update done 
*WM: [3] -> 192.168.4.1 
*WM: [1] [OTA] update ok 
del if0
station: 9e:f2:09:a1:3b:5a leave, AID = 1
rm 1
bcn 0
del if1
usl
```

Is OTA branch updated with last DEV changes?
Thanks @tablatronix

**Comment by rodri16** [comment]
Hi @tablatronix 
I moved to dev branch but left "update" on the menu. Adding 

``` 
#define USEOTA
// enable OTA
#ifdef USEOTA
#include <WiFiUdp.h>
#include <ArduinoOTA.h>
#endif
```

But update button doesn't apper in WM menu

**Comment by tablatronix** [comment]
I gotta update that branch

**Comment by tablatronix** [comment]
merged , let me test it real quick

**Comment by tablatronix** [comment]
OTA is in the OTA branch, not dev

**Comment by tablatronix** [comment]
#981 
realized there was no issue for this
