### ISSUE TITLE
LED still on when router is down

### ISSUE THREAD

**Issue by zzxjl1** [tzapu/WiFiManager#770]
Turn off the router after a sussessful connection, the Led is still on and the program seems unable to detect the current wifi status

**Comment by tablatronix** [comment]
huh?

**Comment by zzxjl1** [comment]
And it stucks in setup() when the router is off , how can i force it into loop() if i want to achieve some functions without the need of wifi？

**Comment by zzxjl1** [comment]
I tried the timeout function , but it only reboots.

**Comment by bigdolphin** [comment]
I think it is same with my issue and you should have to comment the line 2666 in the WiFiManager.cpp
https://github.com/tzapu/WiFiManager/issues/771

**Comment by zzxjl1** [comment]
noop, i mean without any available ssid to connect it nerver tries to enter the loop()

**Comment by tablatronix** [comment]
yeah that is how it is supposed to work if you call autoconnect(), it starts a configportal to configure using a blocking loop. development branch adds non blocking capability

**Comment by zzxjl1** [comment]
Is there any ways to make it enter the loop while broadcasting the configportal

**Comment by tablatronix** [comment]
See non blocking examples in development branch
