### ISSUE TITLE
LED Indcator Debug

### ISSUE THREAD

**Issue by mocheffendi** [tzapu/WiFiManager#79]
Dear Tzapu,

add feature LED indicator debug please
1. On AP mode        : Blink LED 5 times on a sec
2. On Station Mode  : Blink LED with dimmer 2 times on a sec

Thanks
Best Regards

MEf

**Comment by tzapu** [comment]
hi, i thought about this, and i think i can sort it in an example, with what we have currently, no modifications to WiFiManager. Would that be ok for you?

**Comment by mocheffendi** [comment]
yes, 
Thank you

**Comment by domonetic** [comment]
Use the callback function for this. No need modifications.

**Comment by tzapu** [comment]
as @domonetic said, you can use the call back for start config portal

added example here https://github.com/tzapu/WiFiManager/tree/master/examples/AutoConnectWithFeedbackLED

**Comment by mocheffendi** [comment]
@Tzapu 
confirm work 
thank you very much

**Comment by tzapu** [comment]
cool
have fun
