### ISSUE TITLE
accessing loop on auto connect...

### ISSUE THREAD

**Issue by kotran88** [tzapu/WiFiManager#820]
I'm using node mcu. 

and I wonder How can I disconnect? 
by checking WiFiManager.h file, I can't find disconnect function...only I can find sth similar is resetSetting() but it's reset, not disconnect. 

I want completely disconnect. 
how can I attain it? 

Thank you.

**Comment by tablatronix** [comment]
development branch

**Comment by tablatronix** [comment]
configportaltimeout, or stopconfigportal, or non blocking, see examples
