### ISSUE TITLE
ESP32 and GoPro Hero 6 CONNECTION LOST

### ISSUE THREAD

**Issue by alinscodes** [tzapu/WiFiManager#829]
Hi. 

I have established a connection where the ESP32 connects to the wifi hotstop of the GoPro but it loses connection after exactly 10 minutes and I don't know how to stop that.
The ESP32 connects to the hotspot created by the GoPro. I use http commands to control the GoPro.
I sent http command to record and after 10 minutes the connection fails and I can't stop the gopro from recording with another http command.

Why is this happening and how can I stop the connection from getting cut.

The connection is lost exactly after 10 minutes, is the GoPro the problem where it goes into some kind of sleep mode or turns off wifi and turns on bluetooth?

Thanks

**Comment by tablatronix** [comment]
You are connecting to what to what exactly?

**Comment by alinscodes** [comment]
your label is incorrect @tablatronix , I have clearly said that the connection is between ESP32 wifi controller and GoPro.

**Comment by mindforger** [comment]
this may need more Details

who is the AP in this Scenario, how are you sending the requests?

There is a lot room for assumptions to make here :)

**Comment by tablatronix** [comment]
Heh “between” means nothing here.

**Comment by alinscodes** [comment]
> 
> 
> this may need more Details
> 
> who is the AP in this Scenario, how are you sending the requests?
> 
> There is a lot room for assumptions to make here :)
> 
> edited: the template when opening an issues is there for a reason

first time using this sorry, I added more detail

**Comment by alinscodes** [comment]
> 
> 
> Heh “between” means nothing here.

is that better?

**Comment by mindforger** [comment]
From the gopro forum

>You should also remember that the GoPro has battery conservation feature that turns off the WiFi signal after about 10 min. There is no way to disable this so what I do is touch the LCD screen every few minutes to let the camera know I'm still using it even if its not recording

Out of luck i guess, some people claim the 7 behaves better

**Comment by alinscodes** [comment]
@mindforger it happens even when it is recording, to fix the problem it is wasn t recording I would wake it up and put it to sleep every 5 minutes, because it turns of wifi when it is sleeping too, but after 10 minutes exactly after recording starts it loses connection

**Comment by mindforger** [comment]
@alinscodes this is a known issue and even happens when directly connected via the phone

but that issue with the 6 aside, is it a capacitive touch? can one stimulate the touch with pure electronics and without moving parts?! would be a funny idea to put a virtual finger on the display and fake a touch every 5 minutes or so XD

**Comment by alinscodes** [comment]
@mindforger the GoPro will be put on commercial UAV, so that idea sounds funny but stupid for this application haha, so the HERO 6 doesn't have this problem ? 

I also fixed this using a stupid idea, saving the video after 9 minutes and starting it again after 1 second to keep the wifi connection alive

**Comment by KonradIT** [comment]
Are you sending a Keep Alive packet every 3 seconds? This keeps the GoPro on and the WiFi active. Alternatively try connecting to the GoPro via BLE.

**Comment by mindforger** [comment]
>so the HERO 7 doesn't have this problem ?

i have read people writing this but please don't go out and buy one on my comment here, check the gopro forums first for more insight, I just did a quick search for your issue there to get hints

**Comment by KonradIT** [comment]
Literally all GoPros have this problem. It's probably that @alinscodes is not sending the keep alive message periodically.

**Comment by tablatronix** [comment]
Do gopros have a io port that you could make a device that keeps it awake by sending harmless commands? Like fake button presses, shrug

**Comment by alinscodes** [comment]
@KonradIT I leave it to sleep and then I send WoL packet when I wake it up in order to save battery power. But if I wait more than 10 minutes it loses connection so I try wake it up and put it to sleep every 5 minutes but the problem is when I record for more than 10 minutes it loses connection too, therefore every 9 minutes during recording I have to send command to stop recording and start again,

**Comment by alinscodes** [comment]
@mindforger that was the information I needed, now I have to work around that gopro issue to make it do whatever I need. I think this issue is solved tbh

**Comment by alinscodes** [comment]
@tablatronix you can t really send WoL packet when it is recording can you?

**Comment by mindforger** [comment]
did you try to use a HTTP keepalive?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive

this would include to not drop the TCP from the request and requires to set a keep-alive flag in the request header as far as i remember (had this stuff in college last time, so can not give insight, but maybe that helps?)

**Comment by tablatronix** [comment]
Sounds like this is a hardware level sleep, keep alive is probably not going to help

**Comment by alinscodes** [comment]
yeah, not going to help, I fixed it by waking it and putting it back to sleep every 5 minutes, and then when it is recording for long duration I stop recording and start again every 9 minutes to keep wifi connection alive.

thanks guys for your replies. I appreciate it.

**Comment by KonradIT** [comment]
Just in case someone stumbles across this issue and wants to solve this problem:

I'm the maintainer of multiple [GoPro API related repositories](http://github.com/konradit) so I've had this issue before and I know how to solve it. GoPro cameras, when the WiFi is turned on, can either be turned on or off. When the camera is turned off, the WiFi turns off after 10 minutes (in the case of HERO6 and onward, older cameras keep the WiFi on indefinitely). Bluetooth is kept on for roughly an hour in case you need to wake it up (via BT commands of course).

When the camera is turned on with wifi on, the client needs to send [a keep-alive message every 2.5 seconds](https://github.com/KonradIT/gopro-py-api/blob/master/goprocam/GoProCamera.py#L70) to avoid the camera from killing the wifi uplink after 10 minutes of inactivity. If that message is not sent the camera will turn off after a few minutes and then the wifi will be deactivated after 10 minutes. This is a measure to save power.

**Comment by tablatronix** [comment]
Sounds easy enough, sending a keepalive using esp8266 is outside the scope of this library, BUT if anyone wants to follow up and post keep alive solutions here feel free for posterity.

**Comment by mindforger** [comment]
Should be easy to combine, thank you @KonradIT

**Comment by alinscodes** [comment]
@KonradIT is the keep alive message something different from sending WaL packet?
and where would I put this command and how would I send it to GoPro if I am using http commands to communicate with it ? I am a bigginer so I out appreciate your help.

**Comment by KonradIT** [comment]
Yes it's different. This weekend I plan to add some more code to GoProControl and fnally get to work on gopro32 (a BLE client for ESP32 to control multiple gopro cameras).

**Comment by alinscodes** [comment]
@KonradIT could you direct me to an example of sending this keep alive message from esp32 to gopro please

**Comment by KonradIT** [comment]
```
void loop()
{
    WiFiClient client;
    if (!client.connect('10.5.5.9', 8554)) {
        Serial.println("Connection to host failed");
        delay(1000);
        return;
    }
    client.print("_GPHD_:0:0:2:0.000000" );
    client.stop()
}
```

**Comment by alinscodes** [comment]
It doesn't look like you are using a keep alive message , I don t understand

**Comment by KonradIT** [comment]
That is the keep alive message. Please continue this issue [on my ESP8266 library fork](https://github.com/konradit/GoProControl) or [my ESP32 BT library project](https://github.com/konradit/gopro32)

**Comment by alinscodes** [comment]
what is the 8554? 
I am getting CONNECTION TO HOST FAILED

**Comment by KonradIT** [comment]
8554 is the port where we send the keep alive messages and we receive the UDP live stream.
