### ISSUE TITLE
Suggestion:  List networks in strength priority

### ISSUE THREAD

**Issue by MrBill1234** [tzapu/WiFiManager#83]
When selecting 'configure wifi' I think it may be good to list the SSID's in a more organised fashion.

List % signal strength first, then Locked or unlocked, then the SSID name.  Then order by Signal strength.  Reasoning being that the strongest one is probably close to you and one of yours.    It would also neaten up the screen a bit :)  Not sure if an HTML table is needed - shouldn't be.

Just my 2p.

**Comment by tzapu** [comment]
hi, long on the table to do this, but most stuff that s easily done just increases the file size and memory usage of the library... not ideal in an embedded system

**Comment by tzapu** [comment]
there s part of it (the aspect part) modified in the last commit

**Comment by tzapu** [comment]
sorted networks as well in 0.10
enjoy and test :D

**Comment by MrBill1234** [comment]
Looks good - one thing I found, if one of the SSID's is too long, and you're on a small screen (iPhone 5c),  it seems to break the table a bit for subsequent SSID's listed.  Might be good to only display first 25 to 27 characters of the SSID to make it look neater.  In particular some of the HP wifi enabled printers seem to have some pretty long SSID's.

**Comment by tzapu** [comment]
hi, got any screenshots of this?
thought it should wrap nicely, but apparently not..

**Comment by MrBill1234** [comment]
![fullsizerender](https://cloud.githubusercontent.com/assets/16673089/13176477/81e4df96-d70a-11e5-8c2c-a88e8c14ac57.jpg)

**Comment by tzapu** [comment]
cheers, i see what you mean
