### ISSUE TITLE
parameter update

### ISSUE THREAD

**Issue by yomasa** [tzapu/WiFiManager#84]
How do I update/save a parameter after login? Where in the code is the /config.json being saved?

**Comment by tzapu** [comment]
hi, which sketch are you using? just ssid and pass or other stuff as well?

**Comment by yomasa** [comment]
ssid and pass only, also I am still get this; just installed on my laptop new everything, can you tell me or point me on what it is I need to update. I using 2.0 ver of esp ide or is there something else?

Arduino: 1.6.7 (Mac OS X), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Serial, 115200, 4M (3M SPIFFS)"

/Users/jorge/Documents/Arduino/libraries/WiFiManager-master/WiFiManager.cpp: In member function 'void WiFiManager::handleWifiSave()':
/Users/jorge/Documents/Arduino/libraries/WiFiManager-master/WiFiManager.cpp:472:20: error: 'class IPAddress' has no member named 'fromString'
     _sta_static_ip.fromString(server->arg("ip"));
                    ^
/Users/jorge/Documents/Arduino/libraries/WiFiManager-master/WiFiManager.cpp:477:20: error: 'class IPAddress' has no member named 'fromString'
     _sta_static_gw.fromString(server->arg("gw"));
                    ^
/Users/jorge/Documents/Arduino/libraries/WiFiManager-master/WiFiManager.cpp:482:20: error: 'class IPAddress' has no member named 'fromString'
     _sta_static_sn.fromString(server->arg("sn"));
                    ^
exit status 1
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by tzapu** [comment]
with version 2.0.0 of esp8266 core use version 0.6 of wifimanager from board manager

cheers

**Comment by tzapu** [comment]
i ve updated WiFiManger to 0.8. might sort some of your issues, try it if you can

**Comment by tzapu** [comment]
if you use just ssid and pass, there is no config.json. they are saved internally by the sdk

**Comment by scropion86** [comment]
is that means the other parameters like MQTT or Blynk Token will be lost if ESP restarted?

**Comment by tzapu** [comment]
if they are saved to fs like in example, no
