### ISSUE TITLE
On Dev branch AP still running after successfully connecting to WiFi

### ISSUE THREAD

**Issue by amm009uk** [tzapu/WiFiManager#865]
On Dev branch AP still running after successfully connecting to WiFi

#### Hardware
**WiFimanager Branch/Release:**
- [ ] Master
- [X] Development

**Esp8266/Esp32:**
- [X] ESP8266
- [ ] ESP32

**Hardware:			ESP-12e, esp01, esp25**
- [X] ESP01
- [ ] ESP12 E/F/S (nodemcu, wemos, feather)
- [ ] Other

**ESP Core Version:	2.4.0, staging**
- [ ] 2.3.0
- [ ] 2.4.0
- [ ] staging (master/dev)

### Description
After connecting to WiFiManager's AP and configuring WiFi, device reboots as expected. After bootup, the ESP_XXXXXX AP continues to run. This does not occur on on the master branch. 

### Settings in IDE
sonoff Basic R1 or R2 same behaviour.

Additional libraries: 
ArduinoJson@~5.13, PubSubClient

### Sketch
Nothing clever but here is a snippet:

#include <Arduino.h>
#include <FS.h>                                                      
#include <ArduinoJson.h>                                             
#include <ESP8266WiFi.h>                                             
#include <ESP8266WebServer.h>                                        
#include <PubSubClient.h>                                            
#include <DNSServer.h>                                               
#include <ESP8266mDNS.h>                                             
#include <WiFiManager.h>                                             

void setup() {
.
.
	wifiManager.setConfigPortalBlocking(false);                        
  if(!wifiManager.autoConnect(deviceID, WWW_PASSWD)) {               
  }
.
.
}

void loop() {
.
.
	wifiManager.process();
.
.
}
```

### Debug Messages

**Comment by tablatronix** [comment]
this is the esp running it not wm, it is saved, set the mode in your code to fix it
