### ISSUE TITLE
Ability to add default SSID and Password using code.

### ISSUE THREAD

**Issue by AboveTheHeavens** [tzapu/WiFiManager#876]
So here is what I want to do:

I have a raspberry pi which I am using as server to control multiple nodemcus all of which are using WiFi manager.

I want to be able to "add" or "set" the ssid and password for connection using raspberry pi. In other words, instead of _just_ having the option of setting wifi credentials using AP mode and changing the values for all nodes one by one, I want the pi to do it automatically.

Any idea how I can do this?

**Comment by tablatronix** [comment]
you can if they are already on the network, otherwise you have to use ap mode, not sure how else you would do it, except have your code join the network and grab creds from the server but that has nothing to do with Wm
