### ISSUE TITLE
Start WebServer after config

### ISSUE THREAD

**Issue by k7vlad** [tzapu/WiFiManager#88]
As far as I can see, you can't start a new WebServer immediately after the configuration is done (ESP connects to the desired network). Is there any other good way to do that, without using ESP.reset(), as it works after a reboot?

**Comment by tzapu** [comment]
i ve had one other report of this, i will look into is as soon as i get some time
are you using autoConnect or startConfigPortal ?

**Comment by k7vlad** [comment]
I use autoconnect. Would it be possible to use the same "server" which is declared in your library by making the pointer public? I haven't tried it yet

**Comment by tzapu** [comment]
hi, no, the library deallocates that at the end to save memory

cheers

**Comment by tzapu** [comment]
hi , give this a try
https://gist.github.com/tzapu/ecc0759829d30d5a6152

**Comment by k7vlad** [comment]
Brilliant. Thanks (buna treaba!)

**Comment by tzapu** [comment]
mersi :)
