### ISSUE TITLE
Dev branch - iphone takes 30 seconds to hit captive portal

### ISSUE THREAD

**Issue by Daemach** [tzapu/WiFiManager#885]
It takes a very long time for the captive portal to pop on this iphone (running iOS 12.2).  In the serial monitor, the initial call to /hotspot-detect.html happens immediately and the debug info indicates that it was redirected to the captive portal but nothing happens.  Then a flurry of requests happen 30 seconds later and the last one, to /library/test/success.html, seems to finally trigger the portal which pops immediately.  It's as if the first redirect didn't deliver what the iphone expected from a captive portal and decided to test again.

Can't get the portal to pop from a windows laptop either.

What's the best way to use wireshark to capture this exchange to see what is happening?

**Comment by tablatronix** [comment]
#868
