### ISSUE TITLE
portal suddenly no longer works (failing port 80 sessions)

### ISSUE THREAD

**Issue by flok99** [tzapu/WiFiManager#90]
- I configured an esp to a certain ssid via your excellent wifi manager
- i then moved to a different physical location with different access points with other ssids
- there I connected to the esp over wifi. on serial I see that it connects succesfully. also my laptop says it has an ip address 192.168.4.2
- when i connect using either chrome or firefox (or even telnet to port 80!) on  192.168.4.1, it connects and then immediately disconnects without sending anything. not even an http header.
- in the serial connection I see:
nit ESP8266NeoPixel
Init NeoPixels
Init WiFi
*WM: settings invalidated
*WM: THIS MAY CAUSE AP NOT TO STRT UP PROPERLY. YOU NEED TO COMMENT IT OUT AFTER ERASING THE DATA.
*WM: Adding parameter
*WM: Aoife_server
Entered config mode
192.168.4.1
ESP8266NeoPixel
*WM: 
*WM: Configuring access point... 
*WM: ESP8266NeoPixel
add 1
aid 1
station: 0c:d2:92:3d:80:0b join, AID = 1
*WM: AP IP address: 
*WM: 192.168.4.1
*WM: HTTP server started
- as you see I added an explicit "reset settings" as earlier attempts also failed
- sometimes it logs an "handle root" message, but still a disconnect after a second or so wihout any data
- I tried this with 2 different esp8266 modules. same problem for both. both were configured initially at the other location

**Comment by tzapu** [comment]
hi, what esp8266 core are you on?
what version of the library are you using?

most likely this is a bug that got that got fixed in both esp core and wifimanager latest versions ( staging and 0.7)

**Comment by flok99** [comment]
Hi,

One like these:
http://nl.aliexpress.com/item/1pcs-ESP8266-remote-serial-Port-WIFI-wireless-module-through-walls-best/32280714838.html?isOrig=true#extend
ESP-01 I think it is.

I've upgraded the esp8266 plugin in arduino somewhere last week.
I also upgraded wifimanager 0.7 last night just before I send that bug
report.

On Mon, Feb 1, 2016 at 6:30 AM, tzapu <notifications@github.com> wrote:

> hi, what esp8266 core are you on?
> what version of the library are you using?
>
> most likely this is a bug that got that got fixed in both esp core and
> wifimanager latest versions ( staging and 0.7)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tzapu/WiFiManager/issues/90#issuecomment-177774559>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by tzapu** [comment]
hi, you might need to update again the esp8266 core to the latest github version or to staging rc2

see instructions on their github

cheers

**Comment by tzapu** [comment]
i ve updated WiFiManger to 0.8. might sort some of your issues, try it if you can

**Comment by flok99** [comment]
Hi,

The arduino library manager only shows version 0.7.
And for the esp I've got 2.1.0-rc2 installed.

On Mon, Feb 1, 2016 at 10:35 AM, tzapu <notifications@github.com> wrote:

> i ve updated WiFiManger to 0.8. might sort some of your issues, try it if
> you can
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tzapu/WiFiManager/issues/90#issuecomment-177902986>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by flok99** [comment]
Ok I checked again and now 0.8 is available.
MUCH better! thanks a lot!
Only scanning for accesspoints takes minutes.
But apart from that; configuration well now works.

On Mon, Feb 1, 2016 at 5:26 PM, Folkert van Heusden <mail@vanheusden.com>
wrote:

> Hi,
>
> The arduino library manager only shows version 0.7.
> And for the esp I've got 2.1.0-rc2 installed.
>
> On Mon, Feb 1, 2016 at 10:35 AM, tzapu <notifications@github.com> wrote:
>
>> i ve updated WiFiManger to 0.8. might sort some of your issues, try it if
>> you can
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/tzapu/WiFiManager/issues/90#issuecomment-177902986>.
>>
>
>
>
> --
> www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by flok99** [comment]
Hi,

I was too quick: I'm now at an other location and got the same problem
again.

Init NeoPixels
Init WiFi
*WM: Adding parameter
*WM: Aoife_server
*WM:
*WM: AutoConnect
bcn 0
del if1
usl
mode : sta(18:fe:34:d5:9e:57)
add if0
*WM: Connecting as wifi client...
*WM: Using last saved values, should be faster
f r0, scandone
no VANHEUSDENDOTCOM2 found, reconnect after 1s                         <---
correct, it's not here
reconnect
f 0, scandone
no VANHEUSDENDOTCOM2 found, reconnect after 1s
reconnect
f -180, scandone
no VANHEUSDENDOTCOM2 found, reconnect after 1s
*WM: Connection result:
*WM: 1
del if0
usl
mode : softAP(1a:fe:34:d5:9e:57)
add if1
dhcp server start:(ip:192.168.4.1,mask:255.255.255.0,gw:192.168.4.1)
bcn 100
Entered config mode
192.168.4.1
ESP8266NeoPixel
*WM:
*WM: Configuring access point...
*WM: ESP8266NeoPixel
*WM: AP IP address:
*WM: 192.168.4.1
*WM: HTTP server started
chg_A1:-140
add 1
aid 1
station: 0c:d2:92:3d:80:0b join, AID = 1
*WM: Handle root
*WM: Request redirected to captive portal
*WM: Handle root
chg_A1:-100
LmacRxBlk:1
LmacRxBlk:1
LmacRxBlk:1
chg_A1:-60
*WM: WiFi save
*WM: Parameter
*WM: Aoife_server
*WM: 192.168.64.1
*WM: Sent wifi save page
*WM: Connecting to new AP
*WM: Connecting as wifi client...
*WM: Using last saved values, should be faster                         <-----
I've set a new ap but as you see below it will try to connect to the old
ssid ("vanheusdendotcom2")
mode : sta(18:fe:34:d5:9e:57) + softAP(1a:fe:34:d5:9e:57)
add if0
f r-60, LmacRxBlk:1
LmacRxBlk:1
scandone
no VANHEUSDENDOTCOM2 found, reconnect after 1s
reconnect
f 0, LmacRxBlk:1
LmacRxBlk:1
scandone
no VANHEUSDENDOTCOM2 found, reconnect after 1s
reconnect
f -180, LmacRxBlk:1
LmacRxBlk:1
scandone
no VANHEUSDENDOTCOM2 found, reconnect after 1s
*WM: Connection result:
*WM: 1
*WM: Failed to connect.
reconnect
f r-60, scandone
no VANHEUSDENDOTCOM2 found, reconnect after 1s
reconnect
f 0, scandone
no VANHEUSDENDOTCOM2 found, reconnect after 1s
reconnect


On Mon, Feb 1, 2016 at 10:51 PM, Folkert van Heusden <mail@vanheusden.com>
wrote:

> Ok I checked again and now 0.8 is available.
> MUCH better! thanks a lot!
> Only scanning for accesspoints takes minutes.
> But apart from that; configuration well now works.
>
> On Mon, Feb 1, 2016 at 5:26 PM, Folkert van Heusden <mail@vanheusden.com>
> wrote:
>
>> Hi,
>>
>> The arduino library manager only shows version 0.7.
>> And for the esp I've got 2.1.0-rc2 installed.
>>
>> On Mon, Feb 1, 2016 at 10:35 AM, tzapu <notifications@github.com> wrote:
>>
>>> i ve updated WiFiManger to 0.8. might sort some of your issues, try it
>>> if you can
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/tzapu/WiFiManager/issues/90#issuecomment-177902986>.
>>>
>>
>>
>>
>> --
>> www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info
>>
>
>
>
> --
> www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by flok99** [comment]
Oh and the arduino ide does not speak about 0.9, only 0.8.

On Sat, Feb 6, 2016 at 7:16 PM, Folkert van Heusden <mail@vanheusden.com>
wrote:

> Hi,
>
> I was too quick: I'm now at an other location and got the same problem
> again.
>
> Init NeoPixels
> Init WiFi
> *WM: Adding parameter
> *WM: Aoife_server
> *WM:
> *WM: AutoConnect
> bcn 0
> del if1
> usl
> mode : sta(18:fe:34:d5:9e:57)
> add if0
> *WM: Connecting as wifi client...
> *WM: Using last saved values, should be faster
> f r0, scandone
> no VANHEUSDENDOTCOM2 found, reconnect after 1s
> <--- correct, it's not here
> reconnect
> f 0, scandone
> no VANHEUSDENDOTCOM2 found, reconnect after 1s
> reconnect
> f -180, scandone
> no VANHEUSDENDOTCOM2 found, reconnect after 1s
> *WM: Connection result:
> *WM: 1
> del if0
> usl
> mode : softAP(1a:fe:34:d5:9e:57)
> add if1
> dhcp server start:(ip:192.168.4.1,mask:255.255.255.0,gw:192.168.4.1)
> bcn 100
> Entered config mode
> 192.168.4.1
> ESP8266NeoPixel
> *WM:
> *WM: Configuring access point...
> *WM: ESP8266NeoPixel
> *WM: AP IP address:
> *WM: 192.168.4.1
> *WM: HTTP server started
> chg_A1:-140
> add 1
> aid 1
> station: 0c:d2:92:3d:80:0b join, AID = 1
> *WM: Handle root
> *WM: Request redirected to captive portal
> *WM: Handle root
> chg_A1:-100
> LmacRxBlk:1
> LmacRxBlk:1
> LmacRxBlk:1
> chg_A1:-60
> *WM: WiFi save
> *WM: Parameter
> *WM: Aoife_server
> *WM: 192.168.64.1
> *WM: Sent wifi save page
> *WM: Connecting to new AP
> *WM: Connecting as wifi client...
> *WM: Using last saved values, should be faster                         <-----
> I've set a new ap but as you see below it will try to connect to the old
> ssid ("vanheusdendotcom2")
> mode : sta(18:fe:34:d5:9e:57) + softAP(1a:fe:34:d5:9e:57)
> add if0
> f r-60, LmacRxBlk:1
> LmacRxBlk:1
> scandone
> no VANHEUSDENDOTCOM2 found, reconnect after 1s
> reconnect
> f 0, LmacRxBlk:1
> LmacRxBlk:1
> scandone
> no VANHEUSDENDOTCOM2 found, reconnect after 1s
> reconnect
> f -180, LmacRxBlk:1
> LmacRxBlk:1
> scandone
> no VANHEUSDENDOTCOM2 found, reconnect after 1s
> *WM: Connection result:
> *WM: 1
> *WM: Failed to connect.
> reconnect
> f r-60, scandone
> no VANHEUSDENDOTCOM2 found, reconnect after 1s
> reconnect
> f 0, scandone
> no VANHEUSDENDOTCOM2 found, reconnect after 1s
> reconnect
>
>
> On Mon, Feb 1, 2016 at 10:51 PM, Folkert van Heusden <mail@vanheusden.com>
> wrote:
>
>> Ok I checked again and now 0.8 is available.
>> MUCH better! thanks a lot!
>> Only scanning for accesspoints takes minutes.
>> But apart from that; configuration well now works.
>>
>> On Mon, Feb 1, 2016 at 5:26 PM, Folkert van Heusden <mail@vanheusden.com>
>> wrote:
>>
>>> Hi,
>>>
>>> The arduino library manager only shows version 0.7.
>>> And for the esp I've got 2.1.0-rc2 installed.
>>>
>>> On Mon, Feb 1, 2016 at 10:35 AM, tzapu <notifications@github.com> wrote:
>>>
>>>> i ve updated WiFiManger to 0.8. might sort some of your issues, try it
>>>> if you can
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/tzapu/WiFiManager/issues/90#issuecomment-177902986>
>>>> .
>>>>
>>>
>>>
>>>
>>> --
>>> www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info
>>>
>>
>>
>>
>> --
>> www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info
>>
>
>
>
> --
> www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by tzapu** [comment]
weird, maybe they did not update their db yet? a bit opaque on how you can see what they have received or not...

anyway, that seems ike the esp doesn t connect, wifimanager seems to be sending the info on properly...

**Comment by tzapu** [comment]
is it a no password AP?

**Comment by flok99** [comment]
That's correct.

On Sun, Feb 7, 2016 at 10:55 AM, tzapu <notifications@github.com> wrote:

> is it a no password AP?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tzapu/WiFiManager/issues/90#issuecomment-180995052>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by tzapu** [comment]
i added a fix for that in the latest 0.9 i think, update WiFiManager and see if it still does it

**Comment by fat-tire** [comment]
FWIW I'm seeing the same:


*WM: Configuring access point...
*WM: ESP123456  //changedthis
*WM: AP IP address:
*WM: 192.168.4.1
*WM: HTTP server started

Then blinking led.  Guess I can try tracking it down but wanted to post  jic anyone else seeing it.
