### ISSUE TITLE
ESP does not re-connect to the wifi network with the stored parameters

### ISSUE THREAD

**Issue by Portia-Lin** [tzapu/WiFiManager#914]
Hello!

I have a problem with automatic connection to the wifi network after ESP8266 restart.
I can`t solve this problem. 

I'm using a standard sketch "AutoConnectWithReset".
https://github.com/tzapu/WiFiManager/tree/master/examples/AutoConnectWithReset

After pressing the reset button, ESP8266 does not connect into a choosen network. It was start with the AP mode.
And when I connect to an access point again there writes this:

![this:](http://i.piccy.info/i9/b219fc1ff6f57d8a687f3915cf03246f/1563118106/76805/1327794/photo_2019_07_14_18_16_59.jpg)

A similar problem was here: https://github.com/tzapu/WiFiManager/issues/91
But those solutions did not help.
I don't know why this is happening. Can someone help me in solving this problem?

#### Hardware
**WiFimanager Branch/Release:**
- [ ] Master

**Esp8266/Esp32:**
- [ ] ESP8266

**Hardware:			ESP-12e, esp01, esp25**
- [ ] ESP12 F

### Settings in IDE

Module:  			Generic ESP8266 Module
Flash Size:                "4M(1M SPIFFS)"

### Debug Messages
```
*WM: Scan done
*WM: 
*WM: AutoConnect
*WM: SET AP
*WM: 
*WM: Configuring access point... 
*WM: AutoConnectAP
*WM: password
*WM: AP IP address: 
*WM: 192.168.4.1
*WM: HTTP server started
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Handle root
*WM: Request redirected to captive portal
*WM: Handle root
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Handle root
*WM: Handle root
*WM: Request redirected to captive portal
*WM: Handle root
*WM: Request redirected to captive portal
*WM: Handle root
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: testAP
*WM: -52
*WM: RAZA
*WM: -63
*WM: Sent config page
*WM: Request redirected to captive portal
*WM: Handle root
*WM: WiFi save
*WM: Sent wifi save page
*WM: Connecting to new AP
*WM: Connecting wifi with new parameters...
*WM: previous settings invalidated
*WM: After waiting...
*WM: 5.73
*WM: seconds
*WM: Connection result: 
*WM: WL_CONNECTED
connected...yeey :)
local ip
192.168.0.102
                                /*   i press the reset button here   */
*WM: Scan done
*WM: 
*WM: AutoConnect
*WM: SET AP
*WM: 
*WM: Configuring access point... 
*WM: AutoConnectAP
*WM: password
*WM: AP IP address: 
*WM: 192.168.4.1
*WM: HTTP server started
```

**Comment by Portia-Lin** [comment]
The problem was in the library. I downloaded another version from the internet and everything worked. But why so ... In that case, I used the latest version of the library (master).
Now I used this [Library](http://s000.tinyupload.com/index.php?file_id=24506640731354394613)

**Comment by tablatronix** [comment]
Try hotfixes branch or development , also erase flash
