### ISSUE TITLE
Is it possible to stop the AP on successful connection?

### ISSUE THREAD

**Issue by Alives** [tzapu/WiFiManager#920]
Using development branch on commit 34d9a975b5339bb5510f5718fbd1530dff9de733.

I'd like to turn off the AP mode once there is a successful wifi connection.  I tried stopWebPortal() but that probably just stops the http server.  Is it possible to also turn off the AP?

Thanks

**Comment by Alives** [comment]
WiFi.softAPdisconnect(true) seems to do it properly.

**Comment by dknop97** [comment]
I have tried to use the WiFi.softAPdisconnect(true) in my code, but don't worked. So, I added this line in the library (WiFiManager.cpp file -> line 276, in WiFiManager::connectWiFi..., before the first if condition, and it's worked for me. 
Sorry if I make somes mistakes, I'm improving my English yet.

**Comment by tablatronix** [comment]
```
    //manually stop the config portal if started manually, stop immediatly if non blocking, flag abort if blocking
    bool          stopConfigPortal();
```
