### ISSUE TITLE
Release version conflict with latest Arduino

### ISSUE THREAD

**Issue by roberttidey** [tzapu/WiFiManager#927]
A recent commit in the ESP8266 IDE on github has introduced an enum called HTTP_HEAD in ESP8266WebServer.h which is in conflict with string defined in WifiManager.h file and causes compilation errors.

This string is different in the development branch and using this compiles OK.

**Comment by tablatronix** [comment]
I will hotfix if I have not already

**Comment by tablatronix** [comment]
#928

**Comment by tablatronix** [comment]
Has to use x.x.x-beta, x.x-beta did not work, I changed tag and properties, not sure which one was the fix.
