### ISSUE TITLE
Show ConfigPortal connect result on the screen

### ISSUE THREAD

**Issue by dontsovcmc** [tzapu/WiFiManager#930]
After you click "Save" and wait for connection -  there is no difference on the screen between success and fail result =(. The label "If it fails reconnect to AP to try again" is not obvious.. 
We should print "success" or "fail" result on the screen.

**Comment by connornishijima** [comment]
I agree with this, though it might be tough for the current setup to do an AJAX/long-polling style action like that. I'll take a look and see what I can figure out.

**Comment by tablatronix** [comment]
This is discussed in detail in another issue FYI

**Comment by connornishijima** [comment]
Out of the 292 open issues, which one? Lol

**Comment by tablatronix** [comment]
shrug
