### ISSUE TITLE
A new parameter to allow multiple attempts to connect before falling back to AP

### ISSUE THREAD

**Issue by rharrison** [tzapu/WiFiManager#938]
I have an interesting problem where the esp Client fails to get an IP address from the AP. It then configures itself as an AP for configuration. I have added an option to try multiple times before falling back into AP configuration mode. This has fixed my problem as the IP is often given out on the second attempt. 

Should I send a pull request to you for the code changes or is this not something you’re interested in ?

**Comment by rharrison** [comment]
Excuse my ignorance here but should we be disconnecting from the WiFi network before we leave. I can not see an obvious way to do do this. I see there is a WiFi.Disconnect() routine but I'm not sure how to call that from WiFiManager. Is it ok just to send the data to the server and then power off? or should i be telling the AP i'm disconnecting before powering off.

**Comment by tablatronix** [comment]
What esp version are you using?
I mean disconnect before connecting

**Comment by rharrison** [comment]
ESP8266 2.5.2

This seems to have solved it :-)

```
 wifiManager.disconnect();
 if ( ! wifiManager.autoConnect(ssid.c_str(), "foobar")) {
```

Any idea why we need to do this ?

**Comment by rharrison** [comment]
I'm so pleased you managed to solve this. @tablatronix . It was a real hack I put in to try to connect 3 times :-/
