### ISSUE TITLE
Set "checked" flag on Parameter

### ISSUE THREAD

**Issue by ElVasquito** [tzapu/WiFiManager#944]
I added the 3 radio buttons as parameters, based on the "Advanced.ino" example (dev branch), and they appear OK, but how can I set the "checked" flag depending on value 1, 2 or 3 that is loaded from config.json file? So that each time the Param page loads, the proper button is preselected instead of always the first one...

`  const char* custom_radio_str = "<br/><label for='customfieldid'>Custom Field Label</label><input type='radio' name='customfieldid' value='1' checked> One<br><input type='radio' name='customfieldid' value='2'> Two<br><input type='radio' name='customfieldid' value='3'> Three";
  new (&custom_field) WiFiManagerParameter(custom_radio_str); // custom html input
  wm.addParameter(&custom_field);
`

**Comment by tablatronix** [comment]
ok and ? lol not sure what this is for
