### ISSUE TITLE
Reboot ESP after successful configuration.

### ISSUE THREAD

**Issue by afagard** [tzapu/WiFiManager#947]
#### Hardware
**WiFimanager Branch/Release:**
- [ ] Master
- [ x] Development

**Esp8266/Esp32:**
- [ x] ESP8266
- [ ] ESP32

**Hardware:
Lolin Wemos D1 mini pro

**ESP Core Version:	2.4.0, staging**
- [ ] 2.3.0
- [x] 2.4.0
- [ ] staging (master/dev)

### Description

I don't really have an issue as I have a question. Is there an acceptable way to restart the device after successful configuration in the portal? I am not using any of the fancy additional protocols or anything. Currently, I have a `configModeCallback` that sets a bool variable, but I figured there might be something more ingrained in the library that wasn't documented.

Sorry if this isn't the place for this. Wasn't sure where else to ask.

### Settings in IDE

Module:  			Wemos D1

**Comment by tablatronix** [comment]
Nope, I mean ESP.restart() should work fine
