### ISSUE TITLE
Remove version warning in library.properties 

### ISSUE THREAD

**Issue by vicnevicne** [tzapu/WiFiManager#95]
README.md version history indicates that the current version is compatible with esp core 2.0.0 or newer, but the paragraph in library.properties still says **USE version 0.6 together with stable 2.0.0 ESP8266...**

**Comment by tzapu** [comment]
hi,
does this actually show up anywhere?

**Comment by vicnevicne** [comment]
Well it shows up right in the library manager of the Arduino IDE :-) :
![2016-02-07_1537](https://cloud.githubusercontent.com/assets/842233/12872925/d8a0b05c-cdb0-11e5-8595-51dd2703d84b.png)
Thanks for the fix.

**Comment by tzapu** [comment]
jeez, now i feel stooopid ..:P
i looked for it after adding it and couldn t see it anywhere, must of taken a bit to update.. and when i looked again i obviously didn t notice it. it will probably dissapear once i post 0.10
thanks
