### ISSUE TITLE
Hide Access point(SSID)

### ISSUE THREAD

**Issue by Muzzamil1** [tzapu/WiFiManager#956]
Hi, Thanks for the great library!
Is it possible to hide the access point(SSID)?
and how to connect if there is a network that requires a user name or something like a login key?

**Comment by Muzzamil1** [comment]
Hi @tablatronix
Do you have any idea about it?

**Comment by tablatronix** [comment]
Yes it is possible I think, let me check. 

Logging into portals will be hard though

**Comment by Muzzamil1** [comment]
Let me know when you check.

**Comment by dknop97** [comment]
I have a trouble with the SSID, because after the success login with the captive portal, the AP SSID still detectable, but don't active, that is, I keep seeing the SSID, but I can't connect to it. Do you know something like this and a solution?

**Comment by tablatronix** [comment]
That is the esp doing that, it is the default, you will need to set wifi more to sta in your code

WiFi.mode(WIFI_STA);

**Comment by tablatronix** [comment]
// set ap hidden
    void          setWiFiAPHidden(bool hidden); // default false

**Comment by dknop97** [comment]
> ```
> // set ap hidden
> void          setWiFiAPHidden(bool hidden); // default false
> ```

Sorry, I'm confused. What I need to do with this? Put where? How? Sorry again.

**Comment by tablatronix** [comment]
Just set that before calling autoconnect etc..

`wm.setWiFiAPHidden(true);` // hide the portal ap

**Comment by tihoangyeudau** [comment]
> this is for the feature @Muzzamil1 requested
> 
> Just set that before calling autoconnect etc..
> 
> `wm.setWiFiAPHidden(true);` // hide the portal ap

when i add wm.setWiFiAPHidden(true); before autoconnect, there is access point(SSID) named : "Hidden Wifi".

i think your code is wrong.

**Comment by Muzzamil1** [comment]
> this is for the feature @Muzzamil1 requested
> 
> Just set that before calling autoconnect etc..
> 
> `wm.setWiFiAPHidden(true);` // hide the portal ap

Hi @tablatronix  
Thanks, It worked.
