### ISSUE TITLE
Why "This site can’t be reached" when entered hostname.local:80? 

### ISSUE THREAD

**Issue by notSoTechnical** [tzapu/WiFiManager#962]
I cloned the zip file from https://github.com/tzapu/WiFiManager/tree/development
![image](https://user-images.githubusercontent.com/50722184/68348224-5dc67300-00c7-11ea-97cd-b41bbd5747ec.png)

**Comment by tablatronix** [comment]
There have been some changes to mdns, I will check to see if its still working.

Also provide more info about your hardware please

**Comment by notSoTechnical** [comment]
Hi, it's working now with V2.  I was using esp8266 v3.  Thanks anyway!

**Comment by tablatronix** [comment]
V3 ?

**Comment by notSoTechnical** [comment]
version 3 of esp8266 didn't work.  
https://shopofthings.ch/nodemcu-v2-vs-v3/

**Comment by tablatronix** [comment]
They are both esp-12E, same thing, it has more to do with what library you are using
