### ISSUE TITLE
OTA web update

### ISSUE THREAD

**Issue by tablatronix** [tzapu/WiFiManager#981]
I just realized there is no issue for this PR feature
https://github.com/tzapu/WiFiManager/pull/587

**This is added to the OTA branch as a test for now.**

I was going to abstract it out into an example, but I might just leave it in and fix it up.

This is available by adding it to the menu, and is active in the DEV/ example

It is available if you add it (token is `update`) to the menu
```C++
  std::vector<const char *> menu = {"wifi","info","param","update","close","sep","erase","restart","exit"};
  wm.setMenu(menu); // custom menu, pass vector
```
- [ ] add permissions, make hook/route disabled not just menu!
- [ ] find a good way to document this, as it does not work via captive portals! ( maybe even hide it )
- [ ] Better handling of update success

**Comment by gitcnd** [comment]
How do I download and install your OTA branch?  Why is it not the default?

**Comment by tablatronix** [comment]
- [ ] add check for and get update via http client, users add their own server address, opt url input on ota page, or save in memory

**Comment by tablatronix** [comment]
Excessive logging during binary upload of handle root

**Comment by tablatronix** [comment]
Merged into master
