### ISSUE TITLE
Finally Labels above input box (Solved)

### ISSUE THREAD

**Issue by skjolddesign** [tzapu/WiFiManager#994]
WifiManager has been my favorite config portal, except it does not have labels above input boxes.

The solution is to modify html in two const char in WifiManager.h:
`const char HTTP_FORM_START[] PROGMEM      = "<form method='get' action='wifisave'>SSID:<br><input id='s' name='s' length=32><br/> Password:<br><input id='p' name='p' length=64 type='password'><br/>";`
`const char HTTP_FORM_PARAM[] PROGMEM      = "<br/>{p}:<br><input id='{i}' name='{n}' maxlength={l} value='{v}' {c}>";`

Maybe this can be implemented in master branch so everyone can use this feature?

The result is a better user experience:
![WifiManager_with_labels](https://user-images.githubusercontent.com/2446237/72665862-d2ddef00-3a0c-11ea-8633-e3929035191a.jpg)

**Comment by tablatronix** [comment]
development branch
