### ISSUE TITLE
Can I switch off fall-back to AP/Configuration mdoe?

### ISSUE THREAD

**Issue by CKEA123** [tzapu/WiFiManager#997]
I want to use this library for a device that will be physically remote from humans after initial installation. Once the device has been setup it needs to reliably connect and re-connect to the router it has been configured to use. It should only go into (access point) configuration mode when someone presses a button on the device - perhaps at boot time.

However, the documentation says it will fallback to running its own access point mode instead of tr-trying the connection in station mode to the previously configured router if the connection fails. (e.g. if the router is being rebooted).

Is there any way to configure the library to not fallback to access mode and instead keep reconnecting to the router ?

**Comment by tablatronix** [comment]
Ondemandconfigportal example, dont use autoconnect
