### ISSUE TITLE
Changing AP interface?

### ISSUE THREAD

**Issue by bydoctor** [tzapu/WiFiManager#999]
I try to change template.h and and html file of template and uploaded the sketch it seems same. 
How we can change interface when we go to 192.168.4.1 page?  I want to configure the Page on my language. But i couldnt

**Comment by tablatronix** [comment]
strings are not in that file, they are in the source

**Comment by bydoctor** [comment]
So i must change something on github files with fork right?

**Comment by dknop97** [comment]
> Then where the file? I just see strings in that extras file. I think i must change something on github files with fork and push the files with my name and change the library.json repository line with my link right? If is not how can i do? Please help bro i just want to edit congifure wifi , configure wifi(noscan) ... page .

You need to change the strings in the _WifiManager.h_ file (see the images in the links below). They are the same strings as the _template.h_ file, in the _extras_ folder. For this, while editing, I use the Sublime Text editor to create my html page and, after editing, I select the part of the HTML code to join it in one line (ctrl + j), following the separation of original tags of model.

Sorry for my English, I'm still improving.
[https://i.imgur.com/mMXMSEm.png](url) -> WifiManager.h
[https://i.imgur.com/dLt6E97.png](url) -> Join Lines command in Sublime Text 3

**Comment by bydoctor** [comment]
> > Then where the file? I just see strings in that extras file. I think i must change something on github files with fork and push the files with my name and change the library.json repository line with my link right? If is not how can i do? Please help bro i just want to edit congifure wifi , configure wifi(noscan) ... page .
> 
> You need to change the strings in the _WifiManager.h_ file (see the images in the links below). They are the same strings as the _template.h_ file, in the _extras_ folder. For this, while editing, I use the Sublime Text editor to create my html page and, after editing, I select the part of the HTML code to join it in one line (ctrl + j), following the separation of original tags of model.
> 
> Sorry for my English, I'm still improving.
> [https://i.imgur.com/mMXMSEm.png](url) -> WifiManager.h
> [https://i.imgur.com/dLt6E97.png](url) -> Join Lines command in Sublime Text 3

oh man thank you i missed that part now solved my problem thank all of you :)

**Comment by tablatronix** [comment]
In development branch next version these have been moved to strings.h
